# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Additional information about the cardholder’s account provided by the 3DS
  # Requestor.
  class AcctInfo1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Length of time that the cardholder has had the account with the 3DS
    # Requestor. 
    # Allowed values:
    # * **01** — No account
    # * **02** — Created during this transaction
    # * **03** — Less than 30 days
    # * **04** — 30–60 days
    # * **05** — More than 60 days
    # @return [ChAccAgeInd]
    attr_accessor :ch_acc_age_ind

    # Date that the cardholder’s account with the 3DS Requestor was last
    # changed, including Billing or Shipping address, new payment account, or
    # new user(s) added. 
    # Format: **YYYYMMDD**
    # @return [String]
    attr_accessor :ch_acc_change

    # Length of time since the cardholder’s account information with the 3DS
    # Requestor was last changed, including Billing or Shipping address, new
    # payment account, or new user(s) added. 
    # Allowed values:
    # * **01** — Changed during this transaction
    # * **02** — Less than 30 days
    # * **03** — 30–60 days
    # * **04** — More than 60 days
    # @return [ChAccChangeInd]
    attr_accessor :ch_acc_change_ind

    # Date that cardholder’s account with the 3DS Requestor had a password
    # change or account reset. 
    # Format: **YYYYMMDD**
    # @return [String]
    attr_accessor :ch_acc_pw_change

    # Indicates the length of time since the cardholder’s account with the 3DS
    # Requestor had a password change or account reset. 
    # Allowed values:
    # * **01** — No change
    # * **02** — Changed during this transaction
    # * **03** — Less than 30 days
    # * **04** — 30–60 days
    # * **05** — More than 60 days
    # @return [ChAccPwChangeInd]
    attr_accessor :ch_acc_pw_change_ind

    # Date that the cardholder opened the account with the 3DS Requestor. 
    # Format: **YYYYMMDD**
    # @return [String]
    attr_accessor :ch_acc_string

    # Number of purchases with this cardholder account during the previous six
    # months. Max length: 4 characters.
    # @return [String]
    attr_accessor :nb_purchase_account

    # String that the payment account was enrolled in the cardholder’s account
    # with the 3DS Requestor. 
    # Format: **YYYYMMDD**
    # @return [String]
    attr_accessor :payment_acc_age

    # Indicates the length of time that the payment account was enrolled in the
    # cardholder’s account with the 3DS Requestor. 
    # Allowed values:
    # * **01** — No account (guest checkout)
    # * **02** — During this transaction
    # * **03** — Less than 30 days
    # * **04** — 30–60 days
    # * **05** — More than 60 days
    # @return [PaymentAccInd]
    attr_accessor :payment_acc_ind

    # Number of Add Card attempts in the last 24 hours. Max length: 3
    # characters.
    # @return [String]
    attr_accessor :provision_attempts_day

    # String when the shipping address used for this transaction was first used
    # with the 3DS Requestor. 
    # Format: **YYYYMMDD**
    # @return [String]
    attr_accessor :ship_address_usage

    # Indicates when the shipping address used for this transaction was first
    # used with the 3DS Requestor. 
    # Allowed values:
    # * **01** — This transaction
    # * **02** — Less than 30 days
    # * **03** — 30–60 days
    # * **04** — More than 60 days
    # @return [ShipAddressUsageInd]
    attr_accessor :ship_address_usage_ind

    # Indicates if the Cardholder Name on the account is identical to the
    # shipping Name used for this transaction. 
    # Allowed values:
    # * **01** — Account Name identical to shipping Name
    # * **02** — Account Name different to shipping Name
    # @return [ShipNameIndicator]
    attr_accessor :ship_name_indicator

    # Indicates whether the 3DS Requestor has experienced suspicious activity
    # (including previous fraud) on the cardholder account. 
    # Allowed values:
    # * **01** — No suspicious activity has been observed
    # * **02** — Suspicious activity has been observed
    # @return [SuspiciousAccActivity]
    attr_accessor :suspicious_acc_activity

    # Number of transactions (successful and abandoned) for this cardholder
    # account with the 3DS Requestor across all payment accounts in the previous
    # 24 hours. Max length: 3 characters.
    # @return [String]
    attr_accessor :txn_activity_day

    # Number of transactions (successful and abandoned) for this cardholder
    # account with the 3DS Requestor across all payment accounts in the previous
    # year. Max length: 3 characters.
    # @return [String]
    attr_accessor :txn_activity_year

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ch_acc_age_ind'] = 'chAccAgeInd'
      @_hash['ch_acc_change'] = 'chAccChange'
      @_hash['ch_acc_change_ind'] = 'chAccChangeInd'
      @_hash['ch_acc_pw_change'] = 'chAccPwChange'
      @_hash['ch_acc_pw_change_ind'] = 'chAccPwChangeInd'
      @_hash['ch_acc_string'] = 'chAccString'
      @_hash['nb_purchase_account'] = 'nbPurchaseAccount'
      @_hash['payment_acc_age'] = 'paymentAccAge'
      @_hash['payment_acc_ind'] = 'paymentAccInd'
      @_hash['provision_attempts_day'] = 'provisionAttemptsDay'
      @_hash['ship_address_usage'] = 'shipAddressUsage'
      @_hash['ship_address_usage_ind'] = 'shipAddressUsageInd'
      @_hash['ship_name_indicator'] = 'shipNameIndicator'
      @_hash['suspicious_acc_activity'] = 'suspiciousAccActivity'
      @_hash['txn_activity_day'] = 'txnActivityDay'
      @_hash['txn_activity_year'] = 'txnActivityYear'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        ch_acc_age_ind
        ch_acc_change
        ch_acc_change_ind
        ch_acc_pw_change
        ch_acc_pw_change_ind
        ch_acc_string
        nb_purchase_account
        payment_acc_age
        payment_acc_ind
        provision_attempts_day
        ship_address_usage
        ship_address_usage_ind
        ship_name_indicator
        suspicious_acc_activity
        txn_activity_day
        txn_activity_year
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(ch_acc_age_ind: SKIP, ch_acc_change: SKIP,
                   ch_acc_change_ind: SKIP, ch_acc_pw_change: SKIP,
                   ch_acc_pw_change_ind: SKIP, ch_acc_string: SKIP,
                   nb_purchase_account: SKIP, payment_acc_age: SKIP,
                   payment_acc_ind: SKIP, provision_attempts_day: SKIP,
                   ship_address_usage: SKIP, ship_address_usage_ind: SKIP,
                   ship_name_indicator: SKIP, suspicious_acc_activity: SKIP,
                   txn_activity_day: SKIP, txn_activity_year: SKIP)
      @ch_acc_age_ind = ch_acc_age_ind unless ch_acc_age_ind == SKIP
      @ch_acc_change = ch_acc_change unless ch_acc_change == SKIP
      @ch_acc_change_ind = ch_acc_change_ind unless ch_acc_change_ind == SKIP
      @ch_acc_pw_change = ch_acc_pw_change unless ch_acc_pw_change == SKIP
      @ch_acc_pw_change_ind = ch_acc_pw_change_ind unless ch_acc_pw_change_ind == SKIP
      @ch_acc_string = ch_acc_string unless ch_acc_string == SKIP
      @nb_purchase_account = nb_purchase_account unless nb_purchase_account == SKIP
      @payment_acc_age = payment_acc_age unless payment_acc_age == SKIP
      @payment_acc_ind = payment_acc_ind unless payment_acc_ind == SKIP
      @provision_attempts_day = provision_attempts_day unless provision_attempts_day == SKIP
      @ship_address_usage = ship_address_usage unless ship_address_usage == SKIP
      @ship_address_usage_ind = ship_address_usage_ind unless ship_address_usage_ind == SKIP
      @ship_name_indicator = ship_name_indicator unless ship_name_indicator == SKIP
      @suspicious_acc_activity = suspicious_acc_activity unless suspicious_acc_activity == SKIP
      @txn_activity_day = txn_activity_day unless txn_activity_day == SKIP
      @txn_activity_year = txn_activity_year unless txn_activity_year == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ch_acc_age_ind = hash.key?('chAccAgeInd') ? hash['chAccAgeInd'] : SKIP
      ch_acc_change = hash.key?('chAccChange') ? hash['chAccChange'] : SKIP
      ch_acc_change_ind =
        hash.key?('chAccChangeInd') ? hash['chAccChangeInd'] : SKIP
      ch_acc_pw_change =
        hash.key?('chAccPwChange') ? hash['chAccPwChange'] : SKIP
      ch_acc_pw_change_ind =
        hash.key?('chAccPwChangeInd') ? hash['chAccPwChangeInd'] : SKIP
      ch_acc_string = hash.key?('chAccString') ? hash['chAccString'] : SKIP
      nb_purchase_account =
        hash.key?('nbPurchaseAccount') ? hash['nbPurchaseAccount'] : SKIP
      payment_acc_age =
        hash.key?('paymentAccAge') ? hash['paymentAccAge'] : SKIP
      payment_acc_ind =
        hash.key?('paymentAccInd') ? hash['paymentAccInd'] : SKIP
      provision_attempts_day =
        hash.key?('provisionAttemptsDay') ? hash['provisionAttemptsDay'] : SKIP
      ship_address_usage =
        hash.key?('shipAddressUsage') ? hash['shipAddressUsage'] : SKIP
      ship_address_usage_ind =
        hash.key?('shipAddressUsageInd') ? hash['shipAddressUsageInd'] : SKIP
      ship_name_indicator =
        hash.key?('shipNameIndicator') ? hash['shipNameIndicator'] : SKIP
      suspicious_acc_activity =
        hash.key?('suspiciousAccActivity') ? hash['suspiciousAccActivity'] : SKIP
      txn_activity_day =
        hash.key?('txnActivityDay') ? hash['txnActivityDay'] : SKIP
      txn_activity_year =
        hash.key?('txnActivityYear') ? hash['txnActivityYear'] : SKIP

      # Create object from extracted values.
      AcctInfo1.new(ch_acc_age_ind: ch_acc_age_ind,
                    ch_acc_change: ch_acc_change,
                    ch_acc_change_ind: ch_acc_change_ind,
                    ch_acc_pw_change: ch_acc_pw_change,
                    ch_acc_pw_change_ind: ch_acc_pw_change_ind,
                    ch_acc_string: ch_acc_string,
                    nb_purchase_account: nb_purchase_account,
                    payment_acc_age: payment_acc_age,
                    payment_acc_ind: payment_acc_ind,
                    provision_attempts_day: provision_attempts_day,
                    ship_address_usage: ship_address_usage,
                    ship_address_usage_ind: ship_address_usage_ind,
                    ship_name_indicator: ship_name_indicator,
                    suspicious_acc_activity: suspicious_acc_activity,
                    txn_activity_day: txn_activity_day,
                    txn_activity_year: txn_activity_year)
    end

    # Validates an instance of the object from a given value.
    # @param [AcctInfo1 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} ch_acc_age_ind: #{@ch_acc_age_ind}, ch_acc_change: #{@ch_acc_change},"\
      " ch_acc_change_ind: #{@ch_acc_change_ind}, ch_acc_pw_change: #{@ch_acc_pw_change},"\
      " ch_acc_pw_change_ind: #{@ch_acc_pw_change_ind}, ch_acc_string: #{@ch_acc_string},"\
      " nb_purchase_account: #{@nb_purchase_account}, payment_acc_age: #{@payment_acc_age},"\
      " payment_acc_ind: #{@payment_acc_ind}, provision_attempts_day: #{@provision_attempts_day},"\
      " ship_address_usage: #{@ship_address_usage}, ship_address_usage_ind:"\
      " #{@ship_address_usage_ind}, ship_name_indicator: #{@ship_name_indicator},"\
      " suspicious_acc_activity: #{@suspicious_acc_activity}, txn_activity_day:"\
      " #{@txn_activity_day}, txn_activity_year: #{@txn_activity_year}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} ch_acc_age_ind: #{@ch_acc_age_ind.inspect}, ch_acc_change:"\
      " #{@ch_acc_change.inspect}, ch_acc_change_ind: #{@ch_acc_change_ind.inspect},"\
      " ch_acc_pw_change: #{@ch_acc_pw_change.inspect}, ch_acc_pw_change_ind:"\
      " #{@ch_acc_pw_change_ind.inspect}, ch_acc_string: #{@ch_acc_string.inspect},"\
      " nb_purchase_account: #{@nb_purchase_account.inspect}, payment_acc_age:"\
      " #{@payment_acc_age.inspect}, payment_acc_ind: #{@payment_acc_ind.inspect},"\
      " provision_attempts_day: #{@provision_attempts_day.inspect}, ship_address_usage:"\
      " #{@ship_address_usage.inspect}, ship_address_usage_ind:"\
      " #{@ship_address_usage_ind.inspect}, ship_name_indicator: #{@ship_name_indicator.inspect},"\
      " suspicious_acc_activity: #{@suspicious_acc_activity.inspect}, txn_activity_day:"\
      " #{@txn_activity_day.inspect}, txn_activity_year: #{@txn_activity_year.inspect}>"
    end
  end
end
