# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Defines whether to book an additional commission for payments to your user's
  # balance account. The commission amount can be defined as a fixed amount
  # (specified in minor units), a percentage (specified in basis points), or
  # both.
  class AdditionalCommission1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique identifier of the balance account to which the additional
    # commission is booked.
    # @return [String]
    attr_accessor :balance_account_id

    # A fixed commission fee, in minor units.
    # @return [Integer]
    attr_accessor :fixed_amount

    # A variable commission fee, in basis points.
    # @return [Integer]
    attr_accessor :variable_percentage

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['balance_account_id'] = 'balanceAccountId'
      @_hash['fixed_amount'] = 'fixedAmount'
      @_hash['variable_percentage'] = 'variablePercentage'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        balance_account_id
        fixed_amount
        variable_percentage
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(balance_account_id: SKIP, fixed_amount: SKIP,
                   variable_percentage: SKIP)
      @balance_account_id = balance_account_id unless balance_account_id == SKIP
      @fixed_amount = fixed_amount unless fixed_amount == SKIP
      @variable_percentage = variable_percentage unless variable_percentage == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      balance_account_id =
        hash.key?('balanceAccountId') ? hash['balanceAccountId'] : SKIP
      fixed_amount = hash.key?('fixedAmount') ? hash['fixedAmount'] : SKIP
      variable_percentage =
        hash.key?('variablePercentage') ? hash['variablePercentage'] : SKIP

      # Create object from extracted values.
      AdditionalCommission1.new(balance_account_id: balance_account_id,
                                fixed_amount: fixed_amount,
                                variable_percentage: variable_percentage)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} balance_account_id: #{@balance_account_id}, fixed_amount: #{@fixed_amount},"\
      " variable_percentage: #{@variable_percentage}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} balance_account_id: #{@balance_account_id.inspect}, fixed_amount:"\
      " #{@fixed_amount.inspect}, variable_percentage: #{@variable_percentage.inspect}>"
    end
  end
end
