# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # AdditionalDataSubMerchant Model.
  class AdditionalDataSubMerchant < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Required for transactions performed by registered payment facilitators.
    # Indicates the number of sub-merchants contained in the request. For
    # example, **3**.
    # @return [String]
    attr_accessor :sub_merchant_number_of_sub_sellers

    # Required for transactions performed by registered payment facilitators.
    # The city of the sub-merchant's address.
    # * Format: Alphanumeric
    # * Maximum length: 13 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_city

    # Required for transactions performed by registered payment facilitators.
    # The three-letter country code of the sub-merchant's address. For example,
    # **BRA** for Brazil. 
    # * Format: [ISO 3166-1
    # alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)
    # * Fixed length: 3 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_country

    # Required for transactions performed by registered payment facilitators.
    # The email address of the sub-merchant.
    # * Format: Alphanumeric
    # * Maximum length: 40 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_email

    # Required for transactions performed by registered payment facilitators. A
    # unique identifier that you create for the sub-merchant, used by schemes to
    # identify the sub-merchant. 
    # * Format: Alphanumeric
    # * Maximum length: 15 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_id

    # Required for transactions performed by registered payment facilitators.
    # The sub-merchant's 4-digit Merchant Category Code (MCC). 
    # * Format: Numeric
    # * Fixed length: 4 digits
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_mcc

    # Required for transactions performed by registered payment facilitators.
    # The name of the sub-merchant. Based on scheme specifications, this value
    # will overwrite the shopper statement  that will appear in the card
    # statement.
    # Exception: for acquirers in Brazil, this value does not overwrite the
    # shopper statement.
    # * Format: Alphanumeric
    # * Maximum length: 22 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_name

    # Required for transactions performed by registered payment facilitators.
    # The phone number of the sub-merchant.
    # * Format: Alphanumeric and special characters
    # * Maximum length: 20 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_phone_number

    # Required for transactions performed by registered payment facilitators.
    # The postal code of the sub-merchant's address, without dashes.
    # * Format: Numeric
    # * Fixed length: 8 digits
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_postal_code

    # Required for transactions performed by registered payment facilitators.
    # The state code of the sub-merchant's address, if applicable to the
    # country.
    # * Format: Alphanumeric
    # * Maximum length: 2 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_state

    # Required for transactions performed by registered payment facilitators.
    # The street name and house number of the sub-merchant's address.
    # * Format: Alphanumeric
    # * Maximum length: 60 characters
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_street

    # Required for transactions performed by registered payment facilitators.
    # The tax ID of the sub-merchant.
    # * Format: Numeric
    # * Fixed length: 11 digits for the CPF or 14 digits for the CNPJ
    # @return [String]
    attr_accessor :sub_merchant_sub_seller_sub_seller_nr_tax_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sub_merchant_number_of_sub_sellers'] =
        'subMerchant.numberOfSubSellers'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_city'] =
        'subMerchant.subSeller[subSellerNr].city'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_country'] =
        'subMerchant.subSeller[subSellerNr].country'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_email'] =
        'subMerchant.subSeller[subSellerNr].email'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_id'] =
        'subMerchant.subSeller[subSellerNr].id'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_mcc'] =
        'subMerchant.subSeller[subSellerNr].mcc'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_name'] =
        'subMerchant.subSeller[subSellerNr].name'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_phone_number'] =
        'subMerchant.subSeller[subSellerNr].phoneNumber'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_postal_code'] =
        'subMerchant.subSeller[subSellerNr].postalCode'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_state'] =
        'subMerchant.subSeller[subSellerNr].state'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_street'] =
        'subMerchant.subSeller[subSellerNr].street'
      @_hash['sub_merchant_sub_seller_sub_seller_nr_tax_id'] =
        'subMerchant.subSeller[subSellerNr].taxId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sub_merchant_number_of_sub_sellers
        sub_merchant_sub_seller_sub_seller_nr_city
        sub_merchant_sub_seller_sub_seller_nr_country
        sub_merchant_sub_seller_sub_seller_nr_email
        sub_merchant_sub_seller_sub_seller_nr_id
        sub_merchant_sub_seller_sub_seller_nr_mcc
        sub_merchant_sub_seller_sub_seller_nr_name
        sub_merchant_sub_seller_sub_seller_nr_phone_number
        sub_merchant_sub_seller_sub_seller_nr_postal_code
        sub_merchant_sub_seller_sub_seller_nr_state
        sub_merchant_sub_seller_sub_seller_nr_street
        sub_merchant_sub_seller_sub_seller_nr_tax_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(sub_merchant_number_of_sub_sellers: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_city: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_country: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_email: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_id: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_mcc: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_name: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_phone_number: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_postal_code: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_state: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_street: SKIP,
                   sub_merchant_sub_seller_sub_seller_nr_tax_id: SKIP)
      unless sub_merchant_number_of_sub_sellers == SKIP
        @sub_merchant_number_of_sub_sellers =
          sub_merchant_number_of_sub_sellers
      end
      unless sub_merchant_sub_seller_sub_seller_nr_city == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_city =
          sub_merchant_sub_seller_sub_seller_nr_city
      end
      unless sub_merchant_sub_seller_sub_seller_nr_country == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_country =
          sub_merchant_sub_seller_sub_seller_nr_country
      end
      unless sub_merchant_sub_seller_sub_seller_nr_email == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_email =
          sub_merchant_sub_seller_sub_seller_nr_email
      end
      unless sub_merchant_sub_seller_sub_seller_nr_id == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_id =
          sub_merchant_sub_seller_sub_seller_nr_id
      end
      unless sub_merchant_sub_seller_sub_seller_nr_mcc == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_mcc =
          sub_merchant_sub_seller_sub_seller_nr_mcc
      end
      unless sub_merchant_sub_seller_sub_seller_nr_name == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_name =
          sub_merchant_sub_seller_sub_seller_nr_name
      end
      unless sub_merchant_sub_seller_sub_seller_nr_phone_number == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_phone_number =
          sub_merchant_sub_seller_sub_seller_nr_phone_number
      end
      unless sub_merchant_sub_seller_sub_seller_nr_postal_code == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_postal_code =
          sub_merchant_sub_seller_sub_seller_nr_postal_code
      end
      unless sub_merchant_sub_seller_sub_seller_nr_state == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_state =
          sub_merchant_sub_seller_sub_seller_nr_state
      end
      unless sub_merchant_sub_seller_sub_seller_nr_street == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_street =
          sub_merchant_sub_seller_sub_seller_nr_street
      end
      unless sub_merchant_sub_seller_sub_seller_nr_tax_id == SKIP
        @sub_merchant_sub_seller_sub_seller_nr_tax_id =
          sub_merchant_sub_seller_sub_seller_nr_tax_id
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sub_merchant_number_of_sub_sellers =
        hash.key?('subMerchant.numberOfSubSellers') ? hash['subMerchant.numberOfSubSellers'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_city =
        hash.key?('subMerchant.subSeller[subSellerNr].city') ? hash['subMerchant.subSeller[subSellerNr].city'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_country =
        hash.key?('subMerchant.subSeller[subSellerNr].country') ? hash['subMerchant.subSeller[subSellerNr].country'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_email =
        hash.key?('subMerchant.subSeller[subSellerNr].email') ? hash['subMerchant.subSeller[subSellerNr].email'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_id =
        hash.key?('subMerchant.subSeller[subSellerNr].id') ? hash['subMerchant.subSeller[subSellerNr].id'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_mcc =
        hash.key?('subMerchant.subSeller[subSellerNr].mcc') ? hash['subMerchant.subSeller[subSellerNr].mcc'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_name =
        hash.key?('subMerchant.subSeller[subSellerNr].name') ? hash['subMerchant.subSeller[subSellerNr].name'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_phone_number =
        hash.key?('subMerchant.subSeller[subSellerNr].phoneNumber') ? hash['subMerchant.subSeller[subSellerNr].phoneNumber'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_postal_code =
        hash.key?('subMerchant.subSeller[subSellerNr].postalCode') ? hash['subMerchant.subSeller[subSellerNr].postalCode'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_state =
        hash.key?('subMerchant.subSeller[subSellerNr].state') ? hash['subMerchant.subSeller[subSellerNr].state'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_street =
        hash.key?('subMerchant.subSeller[subSellerNr].street') ? hash['subMerchant.subSeller[subSellerNr].street'] : SKIP
      sub_merchant_sub_seller_sub_seller_nr_tax_id =
        hash.key?('subMerchant.subSeller[subSellerNr].taxId') ? hash['subMerchant.subSeller[subSellerNr].taxId'] : SKIP

      # Create object from extracted values.
      AdditionalDataSubMerchant.new(sub_merchant_number_of_sub_sellers: sub_merchant_number_of_sub_sellers,
                                    sub_merchant_sub_seller_sub_seller_nr_city: sub_merchant_sub_seller_sub_seller_nr_city,
                                    sub_merchant_sub_seller_sub_seller_nr_country: sub_merchant_sub_seller_sub_seller_nr_country,
                                    sub_merchant_sub_seller_sub_seller_nr_email: sub_merchant_sub_seller_sub_seller_nr_email,
                                    sub_merchant_sub_seller_sub_seller_nr_id: sub_merchant_sub_seller_sub_seller_nr_id,
                                    sub_merchant_sub_seller_sub_seller_nr_mcc: sub_merchant_sub_seller_sub_seller_nr_mcc,
                                    sub_merchant_sub_seller_sub_seller_nr_name: sub_merchant_sub_seller_sub_seller_nr_name,
                                    sub_merchant_sub_seller_sub_seller_nr_phone_number: sub_merchant_sub_seller_sub_seller_nr_phone_number,
                                    sub_merchant_sub_seller_sub_seller_nr_postal_code: sub_merchant_sub_seller_sub_seller_nr_postal_code,
                                    sub_merchant_sub_seller_sub_seller_nr_state: sub_merchant_sub_seller_sub_seller_nr_state,
                                    sub_merchant_sub_seller_sub_seller_nr_street: sub_merchant_sub_seller_sub_seller_nr_street,
                                    sub_merchant_sub_seller_sub_seller_nr_tax_id: sub_merchant_sub_seller_sub_seller_nr_tax_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} sub_merchant_number_of_sub_sellers: #{@sub_merchant_number_of_sub_sellers},"\
      ' sub_merchant_sub_seller_sub_seller_nr_city:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_city},"\
      ' sub_merchant_sub_seller_sub_seller_nr_country:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_country},"\
      ' sub_merchant_sub_seller_sub_seller_nr_email:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_email}, sub_merchant_sub_seller_sub_seller_nr_id:"\
      " #{@sub_merchant_sub_seller_sub_seller_nr_id}, sub_merchant_sub_seller_sub_seller_nr_mcc:"\
      " #{@sub_merchant_sub_seller_sub_seller_nr_mcc}, sub_merchant_sub_seller_sub_seller_nr_name:"\
      " #{@sub_merchant_sub_seller_sub_seller_nr_name},"\
      ' sub_merchant_sub_seller_sub_seller_nr_phone_number:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_phone_number},"\
      ' sub_merchant_sub_seller_sub_seller_nr_postal_code:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_postal_code},"\
      ' sub_merchant_sub_seller_sub_seller_nr_state:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_state},"\
      ' sub_merchant_sub_seller_sub_seller_nr_street:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_street},"\
      ' sub_merchant_sub_seller_sub_seller_nr_tax_id:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_tax_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} sub_merchant_number_of_sub_sellers:"\
      " #{@sub_merchant_number_of_sub_sellers.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_city:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_city.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_country:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_country.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_email:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_email.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_id:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_id.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_mcc:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_mcc.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_name:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_name.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_phone_number:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_phone_number.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_postal_code:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_postal_code.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_state:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_state.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_street:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_street.inspect},"\
      ' sub_merchant_sub_seller_sub_seller_nr_tax_id:'\
      " #{@sub_merchant_sub_seller_sub_seller_nr_tax_id.inspect}>"
    end
  end
end
