# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # AdditionalDataWallets Model.
  class AdditionalDataWallets < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The Android Pay token retrieved from the SDK.
    # @return [String]
    attr_accessor :androidpay_token

    # The Mastercard Masterpass Transaction ID retrieved from the SDK.
    # @return [String]
    attr_accessor :masterpass_transaction_id

    # The Apple Pay token retrieved from the SDK.
    # @return [String]
    attr_accessor :payment_token

    # The Google Pay token retrieved from the SDK.
    # @return [String]
    attr_accessor :paywithgoogle_token

    # The Samsung Pay token retrieved from the SDK.
    # @return [String]
    attr_accessor :samsungpay_token

    # The Visa Checkout Call ID retrieved from the SDK.
    # @return [String]
    attr_accessor :visacheckout_call_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['androidpay_token'] = 'androidpay.token'
      @_hash['masterpass_transaction_id'] = 'masterpass.transactionId'
      @_hash['payment_token'] = 'payment.token'
      @_hash['paywithgoogle_token'] = 'paywithgoogle.token'
      @_hash['samsungpay_token'] = 'samsungpay.token'
      @_hash['visacheckout_call_id'] = 'visacheckout.callId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        androidpay_token
        masterpass_transaction_id
        payment_token
        paywithgoogle_token
        samsungpay_token
        visacheckout_call_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(androidpay_token: SKIP, masterpass_transaction_id: SKIP,
                   payment_token: SKIP, paywithgoogle_token: SKIP,
                   samsungpay_token: SKIP, visacheckout_call_id: SKIP)
      @androidpay_token = androidpay_token unless androidpay_token == SKIP
      unless masterpass_transaction_id == SKIP
        @masterpass_transaction_id =
          masterpass_transaction_id
      end
      @payment_token = payment_token unless payment_token == SKIP
      @paywithgoogle_token = paywithgoogle_token unless paywithgoogle_token == SKIP
      @samsungpay_token = samsungpay_token unless samsungpay_token == SKIP
      @visacheckout_call_id = visacheckout_call_id unless visacheckout_call_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      androidpay_token =
        hash.key?('androidpay.token') ? hash['androidpay.token'] : SKIP
      masterpass_transaction_id =
        hash.key?('masterpass.transactionId') ? hash['masterpass.transactionId'] : SKIP
      payment_token = hash.key?('payment.token') ? hash['payment.token'] : SKIP
      paywithgoogle_token =
        hash.key?('paywithgoogle.token') ? hash['paywithgoogle.token'] : SKIP
      samsungpay_token =
        hash.key?('samsungpay.token') ? hash['samsungpay.token'] : SKIP
      visacheckout_call_id =
        hash.key?('visacheckout.callId') ? hash['visacheckout.callId'] : SKIP

      # Create object from extracted values.
      AdditionalDataWallets.new(androidpay_token: androidpay_token,
                                masterpass_transaction_id: masterpass_transaction_id,
                                payment_token: payment_token,
                                paywithgoogle_token: paywithgoogle_token,
                                samsungpay_token: samsungpay_token,
                                visacheckout_call_id: visacheckout_call_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} androidpay_token: #{@androidpay_token}, masterpass_transaction_id:"\
      " #{@masterpass_transaction_id}, payment_token: #{@payment_token}, paywithgoogle_token:"\
      " #{@paywithgoogle_token}, samsungpay_token: #{@samsungpay_token}, visacheckout_call_id:"\
      " #{@visacheckout_call_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} androidpay_token: #{@androidpay_token.inspect}, masterpass_transaction_id:"\
      " #{@masterpass_transaction_id.inspect}, payment_token: #{@payment_token.inspect},"\
      " paywithgoogle_token: #{@paywithgoogle_token.inspect}, samsungpay_token:"\
      " #{@samsungpay_token.inspect}, visacheckout_call_id: #{@visacheckout_call_id.inspect}>"
    end
  end
end
