# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The address details of the shipping location.
  class Address21 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of the city.
    # @return [String]
    attr_accessor :city

    # The name of the company.
    # @return [String]
    attr_accessor :company_name

    # The two-letter country code, in [ISO 3166-1
    # alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
    # @return [String]
    attr_accessor :country

    # The postal code.
    # @return [String]
    attr_accessor :postal_code

    # The state or province as defined in [ISO
    # 3166-2](https://www.iso.org/standard/72483.html). For example, **ON** for
    # Ontario, Canada. 
    # Applicable for the following countries:
    # - Australia
    # - Brazil
    # - Canada
    # - India
    # - Mexico
    # - New Zealand
    # - United States
    # @return [String]
    attr_accessor :state_or_province

    # The name of the street, and the house or building number.
    # @return [String]
    attr_accessor :street_address

    # Additional address details, if any.
    # @return [String]
    attr_accessor :street_address2

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['city'] = 'city'
      @_hash['company_name'] = 'companyName'
      @_hash['country'] = 'country'
      @_hash['postal_code'] = 'postalCode'
      @_hash['state_or_province'] = 'stateOrProvince'
      @_hash['street_address'] = 'streetAddress'
      @_hash['street_address2'] = 'streetAddress2'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        city
        company_name
        country
        postal_code
        state_or_province
        street_address
        street_address2
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(city: SKIP, company_name: SKIP, country: SKIP,
                   postal_code: SKIP, state_or_province: SKIP,
                   street_address: SKIP, street_address2: SKIP)
      @city = city unless city == SKIP
      @company_name = company_name unless company_name == SKIP
      @country = country unless country == SKIP
      @postal_code = postal_code unless postal_code == SKIP
      @state_or_province = state_or_province unless state_or_province == SKIP
      @street_address = street_address unless street_address == SKIP
      @street_address2 = street_address2 unless street_address2 == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      city = hash.key?('city') ? hash['city'] : SKIP
      company_name = hash.key?('companyName') ? hash['companyName'] : SKIP
      country = hash.key?('country') ? hash['country'] : SKIP
      postal_code = hash.key?('postalCode') ? hash['postalCode'] : SKIP
      state_or_province =
        hash.key?('stateOrProvince') ? hash['stateOrProvince'] : SKIP
      street_address = hash.key?('streetAddress') ? hash['streetAddress'] : SKIP
      street_address2 =
        hash.key?('streetAddress2') ? hash['streetAddress2'] : SKIP

      # Create object from extracted values.
      Address21.new(city: city,
                    company_name: company_name,
                    country: country,
                    postal_code: postal_code,
                    state_or_province: state_or_province,
                    street_address: street_address,
                    street_address2: street_address2)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} city: #{@city}, company_name: #{@company_name}, country: #{@country},"\
      " postal_code: #{@postal_code}, state_or_province: #{@state_or_province}, street_address:"\
      " #{@street_address}, street_address2: #{@street_address2}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} city: #{@city.inspect}, company_name: #{@company_name.inspect}, country:"\
      " #{@country.inspect}, postal_code: #{@postal_code.inspect}, state_or_province:"\
      " #{@state_or_province.inspect}, street_address: #{@street_address.inspect},"\
      " street_address2: #{@street_address2.inspect}>"
    end
  end
end
