# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Deducts the transaction fee due to Adyen under [Interchange ++
  # pricing](https://www.adyen.com/what-is-interchange) from the specified
  # balance account. Possible values: **deductFromLiableAccount**,
  # **deductFromOneBalanceAccount**.
  class AdyenMarkup
    ADYEN_MARKUP = [
      # TODO: Write general description for DEDUCTFROMLIABLEACCOUNT
      DEDUCTFROMLIABLEACCOUNT = 'deductFromLiableAccount'.freeze,

      # TODO: Write general description for DEDUCTFROMONEBALANCEACCOUNT
      DEDUCTFROMONEBALANCEACCOUNT = 'deductFromOneBalanceAccount'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ADYEN_MARKUP.include?(value)
    end

    def self.from_value(value, default_value = DEDUCTFROMLIABLEACCOUNT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'deductfromliableaccount' then DEDUCTFROMLIABLEACCOUNT
      when 'deductfromonebalanceaccount' then DEDUCTFROMONEBALANCEACCOUNT
      else
        default_value
      end
    end
  end
end
