# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # ApplePay Model.
  class ApplePay < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The stringified and base64 encoded `paymentData` you retrieved from the
    # Apple framework.
    # @return [String]
    attr_accessor :apple_pay_token

    # The checkout attempt identifier.
    # @return [String]
    attr_accessor :checkout_attempt_id

    # The funding source that should be used when multiple sources are
    # available. For Brazilian combo cards, by default the funding source is
    # credit. To use debit, set this value to **debit**.
    # @return [FundingSource]
    attr_accessor :funding_source

    # This is the `recurringDetailReference` returned in the response when you
    # created the token.
    # @return [String]
    attr_accessor :recurring_detail_reference

    # Base64-encoded JSON object containing SDK related parameters required by
    # the SDK
    # @return [String]
    attr_accessor :sdk_data

    # This is the `recurringDetailReference` returned in the response when you
    # created the token.
    # @return [String]
    attr_accessor :stored_payment_method_id

    # **applepay**
    # @return [Type6]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['apple_pay_token'] = 'applePayToken'
      @_hash['checkout_attempt_id'] = 'checkoutAttemptId'
      @_hash['funding_source'] = 'fundingSource'
      @_hash['recurring_detail_reference'] = 'recurringDetailReference'
      @_hash['sdk_data'] = 'sdkData'
      @_hash['stored_payment_method_id'] = 'storedPaymentMethodId'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        checkout_attempt_id
        funding_source
        recurring_detail_reference
        sdk_data
        stored_payment_method_id
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(apple_pay_token:, checkout_attempt_id: SKIP,
                   funding_source: SKIP, recurring_detail_reference: SKIP,
                   sdk_data: SKIP, stored_payment_method_id: SKIP,
                   type: Type6::APPLEPAY)
      @apple_pay_token = apple_pay_token
      @checkout_attempt_id = checkout_attempt_id unless checkout_attempt_id == SKIP
      @funding_source = funding_source unless funding_source == SKIP
      unless recurring_detail_reference == SKIP
        @recurring_detail_reference =
          recurring_detail_reference
      end
      @sdk_data = sdk_data unless sdk_data == SKIP
      @stored_payment_method_id = stored_payment_method_id unless stored_payment_method_id == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      apple_pay_token = hash.key?('applePayToken') ? hash['applePayToken'] : nil
      checkout_attempt_id =
        hash.key?('checkoutAttemptId') ? hash['checkoutAttemptId'] : SKIP
      funding_source = hash.key?('fundingSource') ? hash['fundingSource'] : SKIP
      recurring_detail_reference =
        hash.key?('recurringDetailReference') ? hash['recurringDetailReference'] : SKIP
      sdk_data = hash.key?('sdkData') ? hash['sdkData'] : SKIP
      stored_payment_method_id =
        hash.key?('storedPaymentMethodId') ? hash['storedPaymentMethodId'] : SKIP
      type = hash['type'] ||= Type6::APPLEPAY

      # Create object from extracted values.
      ApplePay.new(apple_pay_token: apple_pay_token,
                   checkout_attempt_id: checkout_attempt_id,
                   funding_source: funding_source,
                   recurring_detail_reference: recurring_detail_reference,
                   sdk_data: sdk_data,
                   stored_payment_method_id: stored_payment_method_id,
                   type: type)
    end

    # Validates an instance of the object from a given value.
    # @param [ApplePay | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.apple_pay_token,
                                     ->(val) { val.instance_of? String })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['applePayToken'],
                            ->(val) { val.instance_of? String })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} apple_pay_token: #{@apple_pay_token}, checkout_attempt_id:"\
      " #{@checkout_attempt_id}, funding_source: #{@funding_source}, recurring_detail_reference:"\
      " #{@recurring_detail_reference}, sdk_data: #{@sdk_data}, stored_payment_method_id:"\
      " #{@stored_payment_method_id}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} apple_pay_token: #{@apple_pay_token.inspect}, checkout_attempt_id:"\
      " #{@checkout_attempt_id.inspect}, funding_source: #{@funding_source.inspect},"\
      " recurring_detail_reference: #{@recurring_detail_reference.inspect}, sdk_data:"\
      " #{@sdk_data.inspect}, stored_payment_method_id: #{@stored_payment_method_id.inspect},"\
      " type: #{@type.inspect}>"
    end
  end
end
