# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # In 3D Secure 2, this is the `transStatus` from the challenge result. If the
  # transaction was frictionless, omit this parameter.
  class AuthenticationResponse
    AUTHENTICATION_RESPONSE = [
      # TODO: Write general description for Y
      Y = 'Y'.freeze,

      # TODO: Write general description for N
      N = 'N'.freeze,

      # TODO: Write general description for U
      U = 'U'.freeze,

      # TODO: Write general description for A
      A = 'A'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      AUTHENTICATION_RESPONSE.include?(value)
    end

    def self.from_value(value, default_value = Y)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'y' then Y
      when 'n' then N
      when 'u' then U
      when 'a' then A
      else
        default_value
      end
    end
  end
end
