# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module AdyenApIs
  # BalanceCheckRequest Model.
  class BalanceCheckRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Shopper account information for 3D Secure 2.
    # > For 3D Secure 2 transactions, we recommend that you include this object
    # to increase the chances of achieving a frictionless flow.
    # @return [AccountInfo1]
    attr_accessor :account_info

    # If you want a [BIN or card
    # verification](https://docs.adyen.com/payment-methods/cards/bin-data-and-ca
    # rd-verification) request to use a non-zero value, assign this value to
    # `additionalAmount` (while the amount must be still set to 0 to trigger BIN
    # or card verification).
    # Required to be in the same currency as the `amount`.
    # @return [Amount1]
    attr_accessor :additional_amount

    # This field contains additional data, which may be required for a
    # particular payment request.
    # The `additionalData` object consists of entries, each of which includes
    # the key and value.
    # @return [Hash[String, String]]
    attr_accessor :additional_data

    # The amount information for the transaction (in [minor
    # units](https://docs.adyen.com/development-resources/currency-codes)). For
    # [BIN or card
    # verification](https://docs.adyen.com/payment-methods/cards/bin-data-and-ca
    # rd-verification) requests, set amount to 0 (zero).
    # @return [Amount2]
    attr_accessor :amount

    # Information about your application. For more details, see [Building Adyen
    # solutions](https://docs.adyen.com/development-resources/building-adyen-sol
    # utions).
    # @return [ApplicationInfo1]
    attr_accessor :application_info

    # The address where to send the invoice.
    # > The `billingAddress` object is required in the following scenarios.
    # Include all of the fields within this object.
    # >* For 3D Secure 2 transactions in all browser-based and mobile
    # implementations.
    # >* For cross-border payouts to and from Canada.
    # @return [Address1]
    attr_accessor :billing_address

    # The shopper's browser information.
    # > For 3D Secure, the full object is required for web integrations. For
    # mobile app integrations, include the `userAgent` and `acceptHeader` fields
    # to indicate  that your integration can support a redirect in case a
    # payment is routed to 3D Secure 2 redirect.
    # @return [BrowserInfo2]
    attr_accessor :browser_info

    # The delay between the authorisation and scheduled auto-capture, specified
    # in hours.
    # @return [Integer]
    attr_accessor :capture_delay_hours

    # The shopper's date of birth.
    # Format [ISO-8601](https://www.w3.org/TR/NOTE-datetime): YYYY-MM-DD
    # @return [Date]
    attr_accessor :date_of_birth

    # The forex quote as returned in the response of the forex service.
    # @return [ForexQuote2]
    attr_accessor :dcc_quote

    # The address where the purchased goods should be delivered.
    # @return [Address2]
    attr_accessor :delivery_address

    # The date and time the purchased goods should be delivered.
    # Format [ISO 8601](https://www.w3.org/TR/NOTE-datetime):
    # YYYY-MM-DDThh:mm:ss.sssTZD
    # Example: 2017-07-17T13:42:40.428+01:00
    # @return [DateTime]
    attr_accessor :delivery_date

    # A string containing the shopper's device fingerprint. For more
    # information, refer to [Device
    # fingerprinting](https://docs.adyen.com/risk-management/device-fingerprinti
    # ng).
    # @return [String]
    attr_accessor :device_fingerprint

    # An integer value that is added to the normal fraud score. The value can be
    # either positive or negative.
    # @return [Integer]
    attr_accessor :fraud_offset

    # Contains installment settings. For more information, refer to
    # [Installments](https://docs.adyen.com/payment-methods/cards/credit-card-in
    # stallments).
    # @return [Installments2]
    attr_accessor :installments

    # The `localizedShopperStatement` field lets you use dynamic values for your
    # shopper statement in a local character set. If this parameter is left
    # empty, not provided, or not applicable (in case of cross-border
    # transactions), then **shopperStatement** is used.
    # Currently, `localizedShopperStatement` is only supported for payments with
    # Visa, Mastercard, JCB, Diners, and Discover.
    # **Supported characters**: Hiragana, Katakana, Kanji, and alphanumeric.
    # @return [Hash[String, String]]
    attr_accessor :localized_shopper_statement

    # The [merchant category
    # code](https://en.wikipedia.org/wiki/Merchant_category_code) (MCC) is a
    # four-digit number, which relates to a particular market segment. This code
    # reflects the predominant activity that is conducted by the merchant.
    # @return [String]
    attr_accessor :mcc

    # The merchant account identifier, with which you want to process the
    # transaction.
    # @return [String]
    attr_accessor :merchant_account

    # This reference allows linking multiple transactions to each other for
    # reporting purposes (i.e. order auth-rate). The reference should be unique
    # per billing cycle.
    # The same merchant order reference should never be reused after the first
    # authorised attempt. If used, this field should be supplied for all
    # incoming authorisations.
    # > We strongly recommend you send the `merchantOrderReference` value to
    # benefit from linking payment requests when authorisation retries take
    # place. In addition, we recommend you provide `retry.orderAttemptNumber`,
    # `retry.chainAttemptNumber`, and `retry.skipRetry` values in
    # `PaymentRequest.additionalData`.
    # @return [String]
    attr_accessor :merchant_order_reference

    # Additional risk fields for 3D Secure 2.
    # > For 3D Secure 2 transactions, we recommend that you include this object
    # to increase the chances of achieving a frictionless flow.
    # @return [MerchantRiskIndicator1]
    attr_accessor :merchant_risk_indicator

    # Metadata consists of entries, each of which includes a key and a value.
    # Limits:
    # * Maximum 20 key-value pairs per request. When exceeding, the "177" error
    # occurs: "Metadata size exceeds limit".
    # * Maximum 20 characters per key.
    # * Maximum 80 characters per value.
    # @return [Hash[String, String]]
    attr_accessor :metadata

    # When you are doing multiple partial (gift card) payments, this is the
    # `pspReference` of the first payment. We use this to link the multiple
    # payments to each other. As your own reference for linking multiple
    # payments, use the `merchantOrderReference`instead.
    # @return [String]
    attr_accessor :order_reference

    # The collection that contains the type of the payment method and its
    # specific information.
    # @return [Hash[String, String]]
    attr_accessor :payment_method

    # The recurring settings for the payment. Use this property when you want to
    # enable [recurring
    # payments](https://docs.adyen.com/classic-integration/recurring-payments).
    # @return [Recurring2]
    attr_accessor :recurring

    # Defines a recurring payment type. Required when creating a token to store
    # payment details or using stored payment details.
    # Allowed values:
    # * `Subscription` – A transaction for a fixed or variable amount, which
    # follows a fixed schedule.
    # * `CardOnFile` – With a card-on-file (CoF) transaction, card details are
    # stored to enable one-click or omnichannel journeys, or simply to
    # streamline the checkout process. Any subscription not following a fixed
    # schedule is also considered a card-on-file transaction.
    # * `UnscheduledCardOnFile` – An unscheduled card-on-file (UCoF) transaction
    # is a transaction that occurs on a non-fixed schedule and/or have variable
    # amounts. For example, automatic top-ups when a cardholder's balance drops
    # below a certain amount.
    # @return [RecurringProcessingModel]
    attr_accessor :recurring_processing_model

    # The reference to uniquely identify a payment. This reference is used in
    # all communication with you about the payment status. We recommend using a
    # unique value per payment; however, it is not a requirement.
    # If you need to provide multiple references for a transaction, separate
    # them with hyphens ("-").
    # Maximum length: 80 characters.
    # @return [String]
    attr_accessor :reference

    # Some payment methods require defining a value for this field to specify
    # how to process the transaction.
    # For the Bancontact payment method, it can be set to:
    # * `maestro` (default), to be processed like a Maestro card, or
    # * `bcmc`, to be processed like a Bancontact card.
    # @return [String]
    attr_accessor :selected_brand

    # The `recurringDetailReference` you want to use for this payment. The value
    # `LATEST` can be used to select the most recently stored recurring detail.
    # @return [String]
    attr_accessor :selected_recurring_detail_reference

    # A session ID used to identify a payment session.
    # @return [String]
    attr_accessor :session_id

    # The shopper's email address. We recommend that you provide this data, as
    # it is used in velocity fraud checks. > Required for Visa and JCB
    # transactions that require 3D Secure 2 authentication if you did not
    # include the `telephoneNumber`.
    # @return [String]
    attr_accessor :shopper_email

    # The shopper's IP address. We recommend that you provide this data, as it
    # is used in a number of risk checks (for instance, number of payment
    # attempts or location-based checks).
    # > Required for Visa and JCB transactions that require 3D Secure 2
    # authentication for all web and mobile integrations, if you did not include
    # the `shopperEmail`. For native mobile integrations, the field is required
    # to support cases where authentication is routed to the redirect flow. This
    # field is also mandatory for some merchants depending on your business
    # model. For more information, [contact
    # Support](https://www.adyen.help/hc/en-us/requests/new).
    # @return [String]
    attr_accessor :shopper_ip

    # Specifies the sales channel, through which the shopper gives their card
    # details, and whether the shopper is a returning customer.
    # For the web service API, Adyen assumes Ecommerce shopper interaction by
    # default.
    # This field has the following possible values:
    # * `Ecommerce` - Online transactions where the cardholder is present
    # (online). For better authorisation rates, we recommend sending the card
    # security code (CSC) along with the request.
    # * `ContAuth` - Card on file and/or subscription transactions, where the
    # cardholder is known to the merchant (returning customer). If the shopper
    # is present (online), you can supply also the CSC to improve authorisation
    # (one-click payment).
    # * `Moto` - Mail-order and telephone-order transactions where the shopper
    # is in contact with the merchant via email or telephone.
    # * `POS` - Point-of-sale transactions where the shopper is physically
    # present to make a payment using a secure payment terminal.
    # @return [ShopperInteraction]
    attr_accessor :shopper_interaction

    # The combination of a language code and a country code to specify the
    # language to be used in the payment.
    # @return [String]
    attr_accessor :shopper_locale

    # The shopper's full name.
    # @return [Name7]
    attr_accessor :shopper_name

    # Required for recurring payments. 
    # Your reference to uniquely identify this shopper, for example user ID or
    # account ID. The value is case-sensitive and must be at least three
    # characters.
    # > Your reference must not include personally identifiable information
    # (PII) such as name or email address.
    # @return [String]
    attr_accessor :shopper_reference

    # The text to be shown on the shopper's bank statement.
    #  We recommend sending a maximum of 22 characters, otherwise banks might
    # truncate the string.
    #  Allowed characters: **a-z**, **A-Z**, **0-9**, spaces, and special
    # characters **. , ' _ - ? + * /**.
    # @return [String]
    attr_accessor :shopper_statement

    # The shopper's social security number.
    # @return [String]
    attr_accessor :social_security_number

    # An array of objects specifying how the payment should be split when using
    # either Adyen for Platforms for
    # [marketplaces](https://docs.adyen.com/marketplaces/split-payments) or
    # [platforms](https://docs.adyen.com/platforms/split-payments), or
    # standalone
    # [Issuing](https://docs.adyen.com/issuing/add-manage-funds#split).
    # @return [Array[Split]]
    attr_accessor :splits

    # Required for Adyen for Platforms integrations if you are a platform model.
    # This is your
    # [reference](https://docs.adyen.com/api-explorer/Management/3/post/merchant
    # s/(merchantId)/stores#request-reference) (on [balance
    # platform](https://docs.adyen.com/platforms)) or the
    # [storeReference](https://docs.adyen.com/api-explorer/Account/latest/post/u
    # pdateAccountHolder#request-accountHolderDetails-storeDetails-storeReferenc
    # e) (in the [classic
    # integration](https://docs.adyen.com/classic-platforms/processing-payments/
    # route-payment-to-store/#route-a-payment-to-a-store)) for the ecommerce or
    # point-of-sale store that is processing the payment.
    # @return [String]
    attr_accessor :store

    # The shopper's telephone number.
    #  The phone number must include a plus sign (+) and a country code (1-3
    # digits), followed by the number (4-15 digits). If the value you provide
    # does not follow the guidelines, we do not submit it for authentication.
    # > Required for Visa and JCB transactions that require 3D Secure 2
    # authentication, if you did not include the `shopperEmail`.
    # @return [String]
    attr_accessor :telephone_number

    # Request fields for 3D Secure 2. To check if any of the following fields
    # are required for your integration, refer to [Online
    # payments](https://docs.adyen.com/online-payments) or [Classic
    # integration](https://docs.adyen.com/classic-integration) documentation.
    # @return [ThreeDs2RequestData2]
    attr_accessor :three_ds2_request_data

    # Required to trigger the [authentication-only
    # flow](https://docs.adyen.com/online-payments/3d-secure/authentication-only
    # /). If set to **true**, you will only perform the 3D Secure 2
    # authentication, and will not proceed to the payment authorization.Default:
    # **false**.
    # @return [TrueClass | FalseClass]
    attr_accessor :three_ds_authentication_only

    # The reference value to aggregate sales totals in reporting. When not
    # specified, the store field is used (if available).
    # @return [String]
    attr_accessor :totals_group

    # Set to true if the payment should be routed to a trusted MID.
    # @return [TrueClass | FalseClass]
    attr_accessor :trusted_shopper

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_info'] = 'accountInfo'
      @_hash['additional_amount'] = 'additionalAmount'
      @_hash['additional_data'] = 'additionalData'
      @_hash['amount'] = 'amount'
      @_hash['application_info'] = 'applicationInfo'
      @_hash['billing_address'] = 'billingAddress'
      @_hash['browser_info'] = 'browserInfo'
      @_hash['capture_delay_hours'] = 'captureDelayHours'
      @_hash['date_of_birth'] = 'dateOfBirth'
      @_hash['dcc_quote'] = 'dccQuote'
      @_hash['delivery_address'] = 'deliveryAddress'
      @_hash['delivery_date'] = 'deliveryDate'
      @_hash['device_fingerprint'] = 'deviceFingerprint'
      @_hash['fraud_offset'] = 'fraudOffset'
      @_hash['installments'] = 'installments'
      @_hash['localized_shopper_statement'] = 'localizedShopperStatement'
      @_hash['mcc'] = 'mcc'
      @_hash['merchant_account'] = 'merchantAccount'
      @_hash['merchant_order_reference'] = 'merchantOrderReference'
      @_hash['merchant_risk_indicator'] = 'merchantRiskIndicator'
      @_hash['metadata'] = 'metadata'
      @_hash['order_reference'] = 'orderReference'
      @_hash['payment_method'] = 'paymentMethod'
      @_hash['recurring'] = 'recurring'
      @_hash['recurring_processing_model'] = 'recurringProcessingModel'
      @_hash['reference'] = 'reference'
      @_hash['selected_brand'] = 'selectedBrand'
      @_hash['selected_recurring_detail_reference'] =
        'selectedRecurringDetailReference'
      @_hash['session_id'] = 'sessionId'
      @_hash['shopper_email'] = 'shopperEmail'
      @_hash['shopper_ip'] = 'shopperIP'
      @_hash['shopper_interaction'] = 'shopperInteraction'
      @_hash['shopper_locale'] = 'shopperLocale'
      @_hash['shopper_name'] = 'shopperName'
      @_hash['shopper_reference'] = 'shopperReference'
      @_hash['shopper_statement'] = 'shopperStatement'
      @_hash['social_security_number'] = 'socialSecurityNumber'
      @_hash['splits'] = 'splits'
      @_hash['store'] = 'store'
      @_hash['telephone_number'] = 'telephoneNumber'
      @_hash['three_ds2_request_data'] = 'threeDS2RequestData'
      @_hash['three_ds_authentication_only'] = 'threeDSAuthenticationOnly'
      @_hash['totals_group'] = 'totalsGroup'
      @_hash['trusted_shopper'] = 'trustedShopper'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_info
        additional_amount
        additional_data
        application_info
        billing_address
        browser_info
        capture_delay_hours
        date_of_birth
        dcc_quote
        delivery_address
        delivery_date
        device_fingerprint
        fraud_offset
        installments
        localized_shopper_statement
        mcc
        merchant_order_reference
        merchant_risk_indicator
        metadata
        order_reference
        recurring
        recurring_processing_model
        reference
        selected_brand
        selected_recurring_detail_reference
        session_id
        shopper_email
        shopper_ip
        shopper_interaction
        shopper_locale
        shopper_name
        shopper_reference
        shopper_statement
        social_security_number
        splits
        store
        telephone_number
        three_ds2_request_data
        three_ds_authentication_only
        totals_group
        trusted_shopper
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(amount:, merchant_account:, payment_method:,
                   account_info: SKIP, additional_amount: SKIP,
                   additional_data: SKIP, application_info: SKIP,
                   billing_address: SKIP, browser_info: SKIP,
                   capture_delay_hours: SKIP, date_of_birth: SKIP,
                   dcc_quote: SKIP, delivery_address: SKIP, delivery_date: SKIP,
                   device_fingerprint: SKIP, fraud_offset: SKIP,
                   installments: SKIP, localized_shopper_statement: SKIP,
                   mcc: SKIP, merchant_order_reference: SKIP,
                   merchant_risk_indicator: SKIP, metadata: SKIP,
                   order_reference: SKIP, recurring: SKIP,
                   recurring_processing_model: SKIP, reference: SKIP,
                   selected_brand: SKIP,
                   selected_recurring_detail_reference: SKIP, session_id: SKIP,
                   shopper_email: SKIP, shopper_ip: SKIP,
                   shopper_interaction: SKIP, shopper_locale: SKIP,
                   shopper_name: SKIP, shopper_reference: SKIP,
                   shopper_statement: SKIP, social_security_number: SKIP,
                   splits: SKIP, store: SKIP, telephone_number: SKIP,
                   three_ds2_request_data: SKIP,
                   three_ds_authentication_only: false, totals_group: SKIP,
                   trusted_shopper: SKIP)
      @account_info = account_info unless account_info == SKIP
      @additional_amount = additional_amount unless additional_amount == SKIP
      @additional_data = additional_data unless additional_data == SKIP
      @amount = amount
      @application_info = application_info unless application_info == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      @browser_info = browser_info unless browser_info == SKIP
      @capture_delay_hours = capture_delay_hours unless capture_delay_hours == SKIP
      @date_of_birth = date_of_birth unless date_of_birth == SKIP
      @dcc_quote = dcc_quote unless dcc_quote == SKIP
      @delivery_address = delivery_address unless delivery_address == SKIP
      @delivery_date = delivery_date unless delivery_date == SKIP
      @device_fingerprint = device_fingerprint unless device_fingerprint == SKIP
      @fraud_offset = fraud_offset unless fraud_offset == SKIP
      @installments = installments unless installments == SKIP
      unless localized_shopper_statement == SKIP
        @localized_shopper_statement =
          localized_shopper_statement
      end
      @mcc = mcc unless mcc == SKIP
      @merchant_account = merchant_account
      @merchant_order_reference = merchant_order_reference unless merchant_order_reference == SKIP
      @merchant_risk_indicator = merchant_risk_indicator unless merchant_risk_indicator == SKIP
      @metadata = metadata unless metadata == SKIP
      @order_reference = order_reference unless order_reference == SKIP
      @payment_method = payment_method
      @recurring = recurring unless recurring == SKIP
      unless recurring_processing_model == SKIP
        @recurring_processing_model =
          recurring_processing_model
      end
      @reference = reference unless reference == SKIP
      @selected_brand = selected_brand unless selected_brand == SKIP
      unless selected_recurring_detail_reference == SKIP
        @selected_recurring_detail_reference =
          selected_recurring_detail_reference
      end
      @session_id = session_id unless session_id == SKIP
      @shopper_email = shopper_email unless shopper_email == SKIP
      @shopper_ip = shopper_ip unless shopper_ip == SKIP
      @shopper_interaction = shopper_interaction unless shopper_interaction == SKIP
      @shopper_locale = shopper_locale unless shopper_locale == SKIP
      @shopper_name = shopper_name unless shopper_name == SKIP
      @shopper_reference = shopper_reference unless shopper_reference == SKIP
      @shopper_statement = shopper_statement unless shopper_statement == SKIP
      @social_security_number = social_security_number unless social_security_number == SKIP
      @splits = splits unless splits == SKIP
      @store = store unless store == SKIP
      @telephone_number = telephone_number unless telephone_number == SKIP
      @three_ds2_request_data = three_ds2_request_data unless three_ds2_request_data == SKIP
      unless three_ds_authentication_only == SKIP
        @three_ds_authentication_only =
          three_ds_authentication_only
      end
      @totals_group = totals_group unless totals_group == SKIP
      @trusted_shopper = trusted_shopper unless trusted_shopper == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = Amount2.from_hash(hash['amount']) if hash['amount']
      merchant_account =
        hash.key?('merchantAccount') ? hash['merchantAccount'] : nil
      payment_method = hash.key?('paymentMethod') ? hash['paymentMethod'] : nil
      account_info = AccountInfo1.from_hash(hash['accountInfo']) if hash['accountInfo']
      additional_amount = Amount1.from_hash(hash['additionalAmount']) if hash['additionalAmount']
      additional_data =
        hash.key?('additionalData') ? hash['additionalData'] : SKIP
      application_info = ApplicationInfo1.from_hash(hash['applicationInfo']) if
        hash['applicationInfo']
      billing_address = Address1.from_hash(hash['billingAddress']) if hash['billingAddress']
      browser_info = BrowserInfo2.from_hash(hash['browserInfo']) if hash['browserInfo']
      capture_delay_hours =
        hash.key?('captureDelayHours') ? hash['captureDelayHours'] : SKIP
      date_of_birth = hash.key?('dateOfBirth') ? hash['dateOfBirth'] : SKIP
      dcc_quote = ForexQuote2.from_hash(hash['dccQuote']) if hash['dccQuote']
      delivery_address = Address2.from_hash(hash['deliveryAddress']) if hash['deliveryAddress']
      delivery_date = if hash.key?('deliveryDate')
                        (DateTimeHelper.from_rfc3339(hash['deliveryDate']) if hash['deliveryDate'])
                      else
                        SKIP
                      end
      device_fingerprint =
        hash.key?('deviceFingerprint') ? hash['deviceFingerprint'] : SKIP
      fraud_offset = hash.key?('fraudOffset') ? hash['fraudOffset'] : SKIP
      installments = Installments2.from_hash(hash['installments']) if hash['installments']
      localized_shopper_statement =
        hash.key?('localizedShopperStatement') ? hash['localizedShopperStatement'] : SKIP
      mcc = hash.key?('mcc') ? hash['mcc'] : SKIP
      merchant_order_reference =
        hash.key?('merchantOrderReference') ? hash['merchantOrderReference'] : SKIP
      merchant_risk_indicator = MerchantRiskIndicator1.from_hash(hash['merchantRiskIndicator']) if
        hash['merchantRiskIndicator']
      metadata = hash.key?('metadata') ? hash['metadata'] : SKIP
      order_reference =
        hash.key?('orderReference') ? hash['orderReference'] : SKIP
      recurring = Recurring2.from_hash(hash['recurring']) if hash['recurring']
      recurring_processing_model =
        hash.key?('recurringProcessingModel') ? hash['recurringProcessingModel'] : SKIP
      reference = hash.key?('reference') ? hash['reference'] : SKIP
      selected_brand = hash.key?('selectedBrand') ? hash['selectedBrand'] : SKIP
      selected_recurring_detail_reference =
        hash.key?('selectedRecurringDetailReference') ? hash['selectedRecurringDetailReference'] : SKIP
      session_id = hash.key?('sessionId') ? hash['sessionId'] : SKIP
      shopper_email = hash.key?('shopperEmail') ? hash['shopperEmail'] : SKIP
      shopper_ip = hash.key?('shopperIP') ? hash['shopperIP'] : SKIP
      shopper_interaction =
        hash.key?('shopperInteraction') ? hash['shopperInteraction'] : SKIP
      shopper_locale = hash.key?('shopperLocale') ? hash['shopperLocale'] : SKIP
      shopper_name = Name7.from_hash(hash['shopperName']) if hash['shopperName']
      shopper_reference =
        hash.key?('shopperReference') ? hash['shopperReference'] : SKIP
      shopper_statement =
        hash.key?('shopperStatement') ? hash['shopperStatement'] : SKIP
      social_security_number =
        hash.key?('socialSecurityNumber') ? hash['socialSecurityNumber'] : SKIP
      # Parameter is an array, so we need to iterate through it
      splits = nil
      unless hash['splits'].nil?
        splits = []
        hash['splits'].each do |structure|
          splits << (Split.from_hash(structure) if structure)
        end
      end

      splits = SKIP unless hash.key?('splits')
      store = hash.key?('store') ? hash['store'] : SKIP
      telephone_number =
        hash.key?('telephoneNumber') ? hash['telephoneNumber'] : SKIP
      three_ds2_request_data = ThreeDs2RequestData2.from_hash(hash['threeDS2RequestData']) if
        hash['threeDS2RequestData']
      three_ds_authentication_only = hash['threeDSAuthenticationOnly'] ||= false
      totals_group = hash.key?('totalsGroup') ? hash['totalsGroup'] : SKIP
      trusted_shopper =
        hash.key?('trustedShopper') ? hash['trustedShopper'] : SKIP

      # Create object from extracted values.
      BalanceCheckRequest.new(amount: amount,
                              merchant_account: merchant_account,
                              payment_method: payment_method,
                              account_info: account_info,
                              additional_amount: additional_amount,
                              additional_data: additional_data,
                              application_info: application_info,
                              billing_address: billing_address,
                              browser_info: browser_info,
                              capture_delay_hours: capture_delay_hours,
                              date_of_birth: date_of_birth,
                              dcc_quote: dcc_quote,
                              delivery_address: delivery_address,
                              delivery_date: delivery_date,
                              device_fingerprint: device_fingerprint,
                              fraud_offset: fraud_offset,
                              installments: installments,
                              localized_shopper_statement: localized_shopper_statement,
                              mcc: mcc,
                              merchant_order_reference: merchant_order_reference,
                              merchant_risk_indicator: merchant_risk_indicator,
                              metadata: metadata,
                              order_reference: order_reference,
                              recurring: recurring,
                              recurring_processing_model: recurring_processing_model,
                              reference: reference,
                              selected_brand: selected_brand,
                              selected_recurring_detail_reference: selected_recurring_detail_reference,
                              session_id: session_id,
                              shopper_email: shopper_email,
                              shopper_ip: shopper_ip,
                              shopper_interaction: shopper_interaction,
                              shopper_locale: shopper_locale,
                              shopper_name: shopper_name,
                              shopper_reference: shopper_reference,
                              shopper_statement: shopper_statement,
                              social_security_number: social_security_number,
                              splits: splits,
                              store: store,
                              telephone_number: telephone_number,
                              three_ds2_request_data: three_ds2_request_data,
                              three_ds_authentication_only: three_ds_authentication_only,
                              totals_group: totals_group,
                              trusted_shopper: trusted_shopper)
    end

    def to_custom_delivery_date
      DateTimeHelper.to_rfc3339(delivery_date)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_info: #{@account_info}, additional_amount: #{@additional_amount},"\
      " additional_data: #{@additional_data}, amount: #{@amount}, application_info:"\
      " #{@application_info}, billing_address: #{@billing_address}, browser_info:"\
      " #{@browser_info}, capture_delay_hours: #{@capture_delay_hours}, date_of_birth:"\
      " #{@date_of_birth}, dcc_quote: #{@dcc_quote}, delivery_address: #{@delivery_address},"\
      " delivery_date: #{@delivery_date}, device_fingerprint: #{@device_fingerprint},"\
      " fraud_offset: #{@fraud_offset}, installments: #{@installments},"\
      " localized_shopper_statement: #{@localized_shopper_statement}, mcc: #{@mcc},"\
      " merchant_account: #{@merchant_account}, merchant_order_reference:"\
      " #{@merchant_order_reference}, merchant_risk_indicator: #{@merchant_risk_indicator},"\
      " metadata: #{@metadata}, order_reference: #{@order_reference}, payment_method:"\
      " #{@payment_method}, recurring: #{@recurring}, recurring_processing_model:"\
      " #{@recurring_processing_model}, reference: #{@reference}, selected_brand:"\
      " #{@selected_brand}, selected_recurring_detail_reference:"\
      " #{@selected_recurring_detail_reference}, session_id: #{@session_id}, shopper_email:"\
      " #{@shopper_email}, shopper_ip: #{@shopper_ip}, shopper_interaction:"\
      " #{@shopper_interaction}, shopper_locale: #{@shopper_locale}, shopper_name:"\
      " #{@shopper_name}, shopper_reference: #{@shopper_reference}, shopper_statement:"\
      " #{@shopper_statement}, social_security_number: #{@social_security_number}, splits:"\
      " #{@splits}, store: #{@store}, telephone_number: #{@telephone_number},"\
      " three_ds2_request_data: #{@three_ds2_request_data}, three_ds_authentication_only:"\
      " #{@three_ds_authentication_only}, totals_group: #{@totals_group}, trusted_shopper:"\
      " #{@trusted_shopper}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_info: #{@account_info.inspect}, additional_amount:"\
      " #{@additional_amount.inspect}, additional_data: #{@additional_data.inspect}, amount:"\
      " #{@amount.inspect}, application_info: #{@application_info.inspect}, billing_address:"\
      " #{@billing_address.inspect}, browser_info: #{@browser_info.inspect}, capture_delay_hours:"\
      " #{@capture_delay_hours.inspect}, date_of_birth: #{@date_of_birth.inspect}, dcc_quote:"\
      " #{@dcc_quote.inspect}, delivery_address: #{@delivery_address.inspect}, delivery_date:"\
      " #{@delivery_date.inspect}, device_fingerprint: #{@device_fingerprint.inspect},"\
      " fraud_offset: #{@fraud_offset.inspect}, installments: #{@installments.inspect},"\
      " localized_shopper_statement: #{@localized_shopper_statement.inspect}, mcc:"\
      " #{@mcc.inspect}, merchant_account: #{@merchant_account.inspect}, merchant_order_reference:"\
      " #{@merchant_order_reference.inspect}, merchant_risk_indicator:"\
      " #{@merchant_risk_indicator.inspect}, metadata: #{@metadata.inspect}, order_reference:"\
      " #{@order_reference.inspect}, payment_method: #{@payment_method.inspect}, recurring:"\
      " #{@recurring.inspect}, recurring_processing_model: #{@recurring_processing_model.inspect},"\
      " reference: #{@reference.inspect}, selected_brand: #{@selected_brand.inspect},"\
      " selected_recurring_detail_reference: #{@selected_recurring_detail_reference.inspect},"\
      " session_id: #{@session_id.inspect}, shopper_email: #{@shopper_email.inspect}, shopper_ip:"\
      " #{@shopper_ip.inspect}, shopper_interaction: #{@shopper_interaction.inspect},"\
      " shopper_locale: #{@shopper_locale.inspect}, shopper_name: #{@shopper_name.inspect},"\
      " shopper_reference: #{@shopper_reference.inspect}, shopper_statement:"\
      " #{@shopper_statement.inspect}, social_security_number: #{@social_security_number.inspect},"\
      " splits: #{@splits.inspect}, store: #{@store.inspect}, telephone_number:"\
      " #{@telephone_number.inspect}, three_ds2_request_data: #{@three_ds2_request_data.inspect},"\
      " three_ds_authentication_only: #{@three_ds_authentication_only.inspect}, totals_group:"\
      " #{@totals_group.inspect}, trusted_shopper: #{@trusted_shopper.inspect}>"
    end
  end
end
