# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The rule to specify the period, within which the recurring debit can happen,
  # relative to the mandate recurring date. Possible values:  * **on**: On a
  # specific date.  * **before**:  Before and on a specific date.  * **after**:
  # On and after a specific date.
  class BillingAttemptsRule
    BILLING_ATTEMPTS_RULE = [
      # TODO: Write general description for ON
      ON = 'on'.freeze,

      # TODO: Write general description for BEFORE
      BEFORE = 'before'.freeze,

      # TODO: Write general description for AFTER
      AFTER = 'after'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      BILLING_ATTEMPTS_RULE.include?(value)
    end

    def self.from_value(value, default_value = ON)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'on' then ON
      when 'before' then BEFORE
      when 'after' then AFTER
      else
        default_value
      end
    end
  end
end
