# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # BillingAddress Model.
  class BillingAddress < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of the city. Maximum length: 3000 characters.
    # @return [String]
    attr_accessor :city

    # The two-character ISO-3166-1 alpha-2 country code. For example, **US**.
    # > If you don't know the country or are not collecting the country from the
    # shopper, provide `country` as `ZZ`.
    # @return [String]
    attr_accessor :country

    # The number or name of the house. Maximum length: 3000 characters.
    # @return [String]
    attr_accessor :house_number_or_name

    # A maximum of five digits for an address in the US, or a maximum of ten
    # characters for an address in all other countries.
    # @return [String]
    attr_accessor :postal_code

    # The two-character ISO 3166-2 state or province code. For example, **CA**
    # in the US or **ON** in Canada.
    # > Required for the US and Canada.
    # @return [String]
    attr_accessor :state_or_province

    # The name of the street. Maximum length: 3000 characters.
    # > The house number should not be included in this field; it should be
    # separately provided via `houseNumberOrName`.
    # @return [String]
    attr_accessor :street

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['city'] = 'city'
      @_hash['country'] = 'country'
      @_hash['house_number_or_name'] = 'houseNumberOrName'
      @_hash['postal_code'] = 'postalCode'
      @_hash['state_or_province'] = 'stateOrProvince'
      @_hash['street'] = 'street'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        state_or_province
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(city:, country:, house_number_or_name:, postal_code:,
                   street:, state_or_province: SKIP)
      @city = city
      @country = country
      @house_number_or_name = house_number_or_name
      @postal_code = postal_code
      @state_or_province = state_or_province unless state_or_province == SKIP
      @street = street
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      city = hash.key?('city') ? hash['city'] : nil
      country = hash.key?('country') ? hash['country'] : nil
      house_number_or_name =
        hash.key?('houseNumberOrName') ? hash['houseNumberOrName'] : nil
      postal_code = hash.key?('postalCode') ? hash['postalCode'] : nil
      street = hash.key?('street') ? hash['street'] : nil
      state_or_province =
        hash.key?('stateOrProvince') ? hash['stateOrProvince'] : SKIP

      # Create object from extracted values.
      BillingAddress.new(city: city,
                         country: country,
                         house_number_or_name: house_number_or_name,
                         postal_code: postal_code,
                         street: street,
                         state_or_province: state_or_province)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} city: #{@city}, country: #{@country}, house_number_or_name:"\
      " #{@house_number_or_name}, postal_code: #{@postal_code}, state_or_province:"\
      " #{@state_or_province}, street: #{@street}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} city: #{@city.inspect}, country: #{@country.inspect}, house_number_or_name:"\
      " #{@house_number_or_name.inspect}, postal_code: #{@postal_code.inspect}, state_or_province:"\
      " #{@state_or_province.inspect}, street: #{@street.inspect}>"
    end
  end
end
