# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The shopper's browser information. > For 3D Secure, the full object is
  # required for web integrations. For mobile app integrations, include the
  # `userAgent` and `acceptHeader` fields to indicate  that your integration can
  # support a redirect in case a payment is routed to 3D Secure 2 redirect.
  class BrowserInfo2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The accept header value of the shopper's browser.
    # @return [String]
    attr_accessor :accept_header

    # The color depth of the shopper's browser in bits per pixel. This should be
    # obtained by using the browser's `screen.colorDepth` property. Accepted
    # values: 1, 4, 8, 15, 16, 24, 30, 32 or 48 bit color depth.
    # @return [Integer]
    attr_accessor :color_depth

    # Boolean value indicating if the shopper's browser is able to execute Java.
    # @return [TrueClass | FalseClass]
    attr_accessor :java_enabled

    # Boolean value indicating if the shopper's browser is able to execute
    # JavaScript. A default 'true' value is assumed if the field is not present.
    # @return [TrueClass | FalseClass]
    attr_accessor :java_script_enabled

    # The `navigator.language` value of the shopper's browser (as defined in
    # IETF BCP 47).
    # @return [String]
    attr_accessor :language

    # The total height of the shopper's device screen in pixels.
    # @return [Integer]
    attr_accessor :screen_height

    # The total width of the shopper's device screen in pixels.
    # @return [Integer]
    attr_accessor :screen_width

    # Time difference between UTC time and the shopper's browser local time, in
    # minutes.
    # @return [Integer]
    attr_accessor :time_zone_offset

    # The user agent value of the shopper's browser.
    # @return [String]
    attr_accessor :user_agent

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['accept_header'] = 'acceptHeader'
      @_hash['color_depth'] = 'colorDepth'
      @_hash['java_enabled'] = 'javaEnabled'
      @_hash['java_script_enabled'] = 'javaScriptEnabled'
      @_hash['language'] = 'language'
      @_hash['screen_height'] = 'screenHeight'
      @_hash['screen_width'] = 'screenWidth'
      @_hash['time_zone_offset'] = 'timeZoneOffset'
      @_hash['user_agent'] = 'userAgent'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        java_script_enabled
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(accept_header:, color_depth:, java_enabled:, language:,
                   screen_height:, screen_width:, time_zone_offset:,
                   user_agent:, java_script_enabled: true)
      @accept_header = accept_header
      @color_depth = color_depth
      @java_enabled = java_enabled
      @java_script_enabled = java_script_enabled unless java_script_enabled == SKIP
      @language = language
      @screen_height = screen_height
      @screen_width = screen_width
      @time_zone_offset = time_zone_offset
      @user_agent = user_agent
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      accept_header = hash.key?('acceptHeader') ? hash['acceptHeader'] : nil
      color_depth = hash.key?('colorDepth') ? hash['colorDepth'] : nil
      java_enabled = hash.key?('javaEnabled') ? hash['javaEnabled'] : nil
      language = hash.key?('language') ? hash['language'] : nil
      screen_height = hash.key?('screenHeight') ? hash['screenHeight'] : nil
      screen_width = hash.key?('screenWidth') ? hash['screenWidth'] : nil
      time_zone_offset =
        hash.key?('timeZoneOffset') ? hash['timeZoneOffset'] : nil
      user_agent = hash.key?('userAgent') ? hash['userAgent'] : nil
      java_script_enabled = hash['javaScriptEnabled'] ||= true

      # Create object from extracted values.
      BrowserInfo2.new(accept_header: accept_header,
                       color_depth: color_depth,
                       java_enabled: java_enabled,
                       language: language,
                       screen_height: screen_height,
                       screen_width: screen_width,
                       time_zone_offset: time_zone_offset,
                       user_agent: user_agent,
                       java_script_enabled: java_script_enabled)
    end

    # Validates an instance of the object from a given value.
    # @param [BrowserInfo2 | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.accept_header,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.color_depth,
                                  ->(val) { val.instance_of? Integer }) and
            APIHelper.valid_type?(value.java_enabled,
                                  ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass }) and
            APIHelper.valid_type?(value.language,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.screen_height,
                                  ->(val) { val.instance_of? Integer }) and
            APIHelper.valid_type?(value.screen_width,
                                  ->(val) { val.instance_of? Integer }) and
            APIHelper.valid_type?(value.time_zone_offset,
                                  ->(val) { val.instance_of? Integer }) and
            APIHelper.valid_type?(value.user_agent,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['acceptHeader'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['colorDepth'],
                                ->(val) { val.instance_of? Integer }) and
          APIHelper.valid_type?(value['javaEnabled'],
                                ->(val) { val.instance_of? TrueClass or val.instance_of? FalseClass }) and
          APIHelper.valid_type?(value['language'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['screenHeight'],
                                ->(val) { val.instance_of? Integer }) and
          APIHelper.valid_type?(value['screenWidth'],
                                ->(val) { val.instance_of? Integer }) and
          APIHelper.valid_type?(value['timeZoneOffset'],
                                ->(val) { val.instance_of? Integer }) and
          APIHelper.valid_type?(value['userAgent'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} accept_header: #{@accept_header}, color_depth: #{@color_depth},"\
      " java_enabled: #{@java_enabled}, java_script_enabled: #{@java_script_enabled}, language:"\
      " #{@language}, screen_height: #{@screen_height}, screen_width: #{@screen_width},"\
      " time_zone_offset: #{@time_zone_offset}, user_agent: #{@user_agent}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} accept_header: #{@accept_header.inspect}, color_depth:"\
      " #{@color_depth.inspect}, java_enabled: #{@java_enabled.inspect}, java_script_enabled:"\
      " #{@java_script_enabled.inspect}, language: #{@language.inspect}, screen_height:"\
      " #{@screen_height.inspect}, screen_width: #{@screen_width.inspect}, time_zone_offset:"\
      " #{@time_zone_offset.inspect}, user_agent: #{@user_agent.inspect}>"
    end
  end
end
