# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # CancelOrderResponse Model.
  class CancelOrderResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A unique reference of the cancellation request.
    # @return [String]
    attr_accessor :psp_reference

    # The result of the cancellation request.
    # Possible values:
    # * **Received** – Indicates the cancellation has successfully been received
    # by Adyen, and will be processed.
    # @return [String]
    attr_reader :result_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['psp_reference'] = 'pspReference'
      @_hash['result_code'] = 'resultCode'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(psp_reference:)
      @psp_reference = psp_reference
      @result_code = 'Received'
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      psp_reference = hash.key?('pspReference') ? hash['pspReference'] : nil

      # Create object from extracted values.
      CancelOrderResponse.new(psp_reference: psp_reference)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} psp_reference: #{@psp_reference}, result_code: #{@result_code}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} psp_reference: #{@psp_reference.inspect}, result_code:"\
      " #{@result_code.inspect}>"
    end
  end
end
