# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # CardBrandDetails Model.
  class CardBrandDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Indicates if you support the card brand.
    # @return [TrueClass | FalseClass]
    attr_accessor :supported

    # The name of the card brand.
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['supported'] = 'supported'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        supported
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(supported: SKIP, type: SKIP)
      @supported = supported unless supported == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      supported = hash.key?('supported') ? hash['supported'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      CardBrandDetails.new(supported: supported,
                           type: type)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} supported: #{@supported}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} supported: #{@supported.inspect}, type: #{@type.inspect}>"
    end
  end
end
