# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Cellulant Model.
  class Cellulant < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The checkout attempt identifier.
    # @return [String]
    attr_accessor :checkout_attempt_id

    # The Cellulant issuer.
    # @return [String]
    attr_accessor :issuer

    # Base64-encoded JSON object containing SDK related parameters required by
    # the SDK
    # @return [String]
    attr_accessor :sdk_data

    # **Cellulant**
    # @return [Type15]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['checkout_attempt_id'] = 'checkoutAttemptId'
      @_hash['issuer'] = 'issuer'
      @_hash['sdk_data'] = 'sdkData'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        checkout_attempt_id
        issuer
        sdk_data
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(checkout_attempt_id: SKIP, issuer: SKIP, sdk_data: SKIP,
                   type: Type15::CELLULANT)
      @checkout_attempt_id = checkout_attempt_id unless checkout_attempt_id == SKIP
      @issuer = issuer unless issuer == SKIP
      @sdk_data = sdk_data unless sdk_data == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      checkout_attempt_id =
        hash.key?('checkoutAttemptId') ? hash['checkoutAttemptId'] : SKIP
      issuer = hash.key?('issuer') ? hash['issuer'] : SKIP
      sdk_data = hash.key?('sdkData') ? hash['sdkData'] : SKIP
      type = hash['type'] ||= Type15::CELLULANT

      # Create object from extracted values.
      Cellulant.new(checkout_attempt_id: checkout_attempt_id,
                    issuer: issuer,
                    sdk_data: sdk_data,
                    type: type)
    end

    # Validates an instance of the object from a given value.
    # @param [Cellulant | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id}, issuer: #{@issuer}, sdk_data:"\
      " #{@sdk_data}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id.inspect}, issuer:"\
      " #{@issuer.inspect}, sdk_data: #{@sdk_data.inspect}, type: #{@type.inspect}>"
    end
  end
end
