# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The platform where a payment transaction takes place. This field is optional
  # for filtering out payment methods that are only available on specific
  # platforms. If this value is not set, then we will try to infer it from the
  # `sdkVersion` or `token`. Possible values: * iOS * Android * Web
  class Channel2
    CHANNEL2 = [
      # TODO: Write general description for IOS
      IOS = 'iOS'.freeze,

      # TODO: Write general description for ANDROID
      ANDROID = 'Android'.freeze,

      # TODO: Write general description for WEB
      WEB = 'Web'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CHANNEL2.include?(value)
    end

    def self.from_value(value, default_value = IOS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'ios' then IOS
      when 'android' then ANDROID
      when 'web' then WEB
      else
        default_value
      end
    end
  end
end
