# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The card details.
  class CheckoutForwardRequestCard2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The [card verification
    # code](https://docs.adyen.com/payments-fundamentals/payment-glossary#card-s
    # ecurity-code-cvc-cvv-cid) (1-20 characters). Depending on the card brand,
    # it is also known as:
    # * CVV2/CVC2 – length: 3 digits
    # * CID – length: 4 digits
    # @return [String]
    attr_accessor :cvc

    # The encrypted card number.
    # @return [String]
    attr_accessor :encrypted_card_number

    # The encrypted expiryMonth
    # @return [String]
    attr_accessor :encrypted_expiry_month

    # The encrypted card expiry year.
    # @return [String]
    attr_accessor :encrypted_expiry_year

    # The encrypted security code.
    # @return [String]
    attr_accessor :encrypted_security_code

    # The card expiry month.
    # Format: 2 digits, zero-padded for single digits. For example:
    # * 03 = March
    # * 11 = November
    # @return [String]
    attr_accessor :expiry_month

    # The card expiry year.
    # @return [String]
    attr_accessor :expiry_year

    # The name of the cardholder.
    # @return [String]
    attr_accessor :holder_name

    # The card number. Only collect raw card data if you are fully [PCI
    # compliant](https://docs.adyen.com/development-resources/pci-dss-compliance
    # -guide).
    # Format: Do not use separators.
    # @return [String]
    attr_accessor :number

    # Default payment method details. Common for scheme payment methods, and for
    # simple payment method details.
    # @return [Type16]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['cvc'] = 'cvc'
      @_hash['encrypted_card_number'] = 'encryptedCardNumber'
      @_hash['encrypted_expiry_month'] = 'encryptedExpiryMonth'
      @_hash['encrypted_expiry_year'] = 'encryptedExpiryYear'
      @_hash['encrypted_security_code'] = 'encryptedSecurityCode'
      @_hash['expiry_month'] = 'expiryMonth'
      @_hash['expiry_year'] = 'expiryYear'
      @_hash['holder_name'] = 'holderName'
      @_hash['number'] = 'number'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        cvc
        encrypted_card_number
        encrypted_expiry_month
        encrypted_expiry_year
        encrypted_security_code
        expiry_month
        expiry_year
        holder_name
        number
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(cvc: SKIP, encrypted_card_number: SKIP,
                   encrypted_expiry_month: SKIP, encrypted_expiry_year: SKIP,
                   encrypted_security_code: SKIP, expiry_month: SKIP,
                   expiry_year: SKIP, holder_name: SKIP, number: SKIP,
                   type: Type16::SCHEME)
      @cvc = cvc unless cvc == SKIP
      @encrypted_card_number = encrypted_card_number unless encrypted_card_number == SKIP
      @encrypted_expiry_month = encrypted_expiry_month unless encrypted_expiry_month == SKIP
      @encrypted_expiry_year = encrypted_expiry_year unless encrypted_expiry_year == SKIP
      @encrypted_security_code = encrypted_security_code unless encrypted_security_code == SKIP
      @expiry_month = expiry_month unless expiry_month == SKIP
      @expiry_year = expiry_year unless expiry_year == SKIP
      @holder_name = holder_name unless holder_name == SKIP
      @number = number unless number == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      cvc = hash.key?('cvc') ? hash['cvc'] : SKIP
      encrypted_card_number =
        hash.key?('encryptedCardNumber') ? hash['encryptedCardNumber'] : SKIP
      encrypted_expiry_month =
        hash.key?('encryptedExpiryMonth') ? hash['encryptedExpiryMonth'] : SKIP
      encrypted_expiry_year =
        hash.key?('encryptedExpiryYear') ? hash['encryptedExpiryYear'] : SKIP
      encrypted_security_code =
        hash.key?('encryptedSecurityCode') ? hash['encryptedSecurityCode'] : SKIP
      expiry_month = hash.key?('expiryMonth') ? hash['expiryMonth'] : SKIP
      expiry_year = hash.key?('expiryYear') ? hash['expiryYear'] : SKIP
      holder_name = hash.key?('holderName') ? hash['holderName'] : SKIP
      number = hash.key?('number') ? hash['number'] : SKIP
      type = hash['type'] ||= Type16::SCHEME

      # Create object from extracted values.
      CheckoutForwardRequestCard2.new(cvc: cvc,
                                      encrypted_card_number: encrypted_card_number,
                                      encrypted_expiry_month: encrypted_expiry_month,
                                      encrypted_expiry_year: encrypted_expiry_year,
                                      encrypted_security_code: encrypted_security_code,
                                      expiry_month: expiry_month,
                                      expiry_year: expiry_year,
                                      holder_name: holder_name,
                                      number: number,
                                      type: type)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} cvc: #{@cvc}, encrypted_card_number: #{@encrypted_card_number},"\
      " encrypted_expiry_month: #{@encrypted_expiry_month}, encrypted_expiry_year:"\
      " #{@encrypted_expiry_year}, encrypted_security_code: #{@encrypted_security_code},"\
      " expiry_month: #{@expiry_month}, expiry_year: #{@expiry_year}, holder_name:"\
      " #{@holder_name}, number: #{@number}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} cvc: #{@cvc.inspect}, encrypted_card_number:"\
      " #{@encrypted_card_number.inspect}, encrypted_expiry_month:"\
      " #{@encrypted_expiry_month.inspect}, encrypted_expiry_year:"\
      " #{@encrypted_expiry_year.inspect}, encrypted_security_code:"\
      " #{@encrypted_security_code.inspect}, expiry_month: #{@expiry_month.inspect}, expiry_year:"\
      " #{@expiry_year.inspect}, holder_name: #{@holder_name.inspect}, number: #{@number.inspect},"\
      " type: #{@type.inspect}>"
    end
  end
end
