# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # CheckoutVoucherAction Model.
  class CheckoutVoucherAction < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The voucher alternative reference code.
    # @return [String]
    attr_accessor :alternative_reference

    # A collection institution number (store number) for Econtext Pay-Easy ATM.
    # @return [String]
    attr_accessor :collection_institution_number

    # The URL to download the voucher.
    # @return [String]
    attr_accessor :download_url

    # An entity number of Multibanco.
    # @return [String]
    attr_accessor :entity

    # The date time of the voucher expiry.
    # @return [String]
    attr_accessor :expires_at

    # The initial amount.
    # @return [Amount13]
    attr_accessor :initial_amount

    # The URL to the detailed instructions to make payment using the voucher.
    # @return [String]
    attr_accessor :instructions_url

    # The issuer of the voucher.
    # @return [String]
    attr_accessor :issuer

    # The shopper telephone number (partially masked).
    # @return [String]
    attr_accessor :masked_telephone_number

    # The merchant name.
    # @return [String]
    attr_accessor :merchant_name

    # The merchant reference.
    # @return [String]
    attr_accessor :merchant_reference

    # A Base64-encoded token containing all properties of the voucher. For iOS,
    # you can use this to pass a voucher to Apple Wallet.
    # @return [String]
    attr_accessor :pass_creation_token

    # Encoded payment data.
    # @return [String]
    attr_accessor :payment_data

    # Specifies the payment method.
    # @return [String]
    attr_accessor :payment_method_type

    # The voucher reference code.
    # @return [String]
    attr_accessor :reference

    # The shopper email.
    # @return [String]
    attr_accessor :shopper_email

    # The shopper name.
    # @return [String]
    attr_accessor :shopper_name

    # The surcharge amount.
    # @return [Amount14]
    attr_accessor :surcharge

    # The total amount (initial plus surcharge amount).
    # @return [Amount15]
    attr_accessor :total_amount

    # **voucher**
    # @return [String]
    attr_reader :type

    # Specifies the URL to redirect to.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['alternative_reference'] = 'alternativeReference'
      @_hash['collection_institution_number'] = 'collectionInstitutionNumber'
      @_hash['download_url'] = 'downloadUrl'
      @_hash['entity'] = 'entity'
      @_hash['expires_at'] = 'expiresAt'
      @_hash['initial_amount'] = 'initialAmount'
      @_hash['instructions_url'] = 'instructionsUrl'
      @_hash['issuer'] = 'issuer'
      @_hash['masked_telephone_number'] = 'maskedTelephoneNumber'
      @_hash['merchant_name'] = 'merchantName'
      @_hash['merchant_reference'] = 'merchantReference'
      @_hash['pass_creation_token'] = 'passCreationToken'
      @_hash['payment_data'] = 'paymentData'
      @_hash['payment_method_type'] = 'paymentMethodType'
      @_hash['reference'] = 'reference'
      @_hash['shopper_email'] = 'shopperEmail'
      @_hash['shopper_name'] = 'shopperName'
      @_hash['surcharge'] = 'surcharge'
      @_hash['total_amount'] = 'totalAmount'
      @_hash['type'] = 'type'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        alternative_reference
        collection_institution_number
        download_url
        entity
        expires_at
        initial_amount
        instructions_url
        issuer
        masked_telephone_number
        merchant_name
        merchant_reference
        pass_creation_token
        payment_data
        payment_method_type
        reference
        shopper_email
        shopper_name
        surcharge
        total_amount
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(alternative_reference: SKIP,
                   collection_institution_number: SKIP, download_url: SKIP,
                   entity: SKIP, expires_at: SKIP, initial_amount: SKIP,
                   instructions_url: SKIP, issuer: SKIP,
                   masked_telephone_number: SKIP, merchant_name: SKIP,
                   merchant_reference: SKIP, pass_creation_token: SKIP,
                   payment_data: SKIP, payment_method_type: SKIP,
                   reference: SKIP, shopper_email: SKIP, shopper_name: SKIP,
                   surcharge: SKIP, total_amount: SKIP, url: SKIP)
      @alternative_reference = alternative_reference unless alternative_reference == SKIP
      unless collection_institution_number == SKIP
        @collection_institution_number =
          collection_institution_number
      end
      @download_url = download_url unless download_url == SKIP
      @entity = entity unless entity == SKIP
      @expires_at = expires_at unless expires_at == SKIP
      @initial_amount = initial_amount unless initial_amount == SKIP
      @instructions_url = instructions_url unless instructions_url == SKIP
      @issuer = issuer unless issuer == SKIP
      @masked_telephone_number = masked_telephone_number unless masked_telephone_number == SKIP
      @merchant_name = merchant_name unless merchant_name == SKIP
      @merchant_reference = merchant_reference unless merchant_reference == SKIP
      @pass_creation_token = pass_creation_token unless pass_creation_token == SKIP
      @payment_data = payment_data unless payment_data == SKIP
      @payment_method_type = payment_method_type unless payment_method_type == SKIP
      @reference = reference unless reference == SKIP
      @shopper_email = shopper_email unless shopper_email == SKIP
      @shopper_name = shopper_name unless shopper_name == SKIP
      @surcharge = surcharge unless surcharge == SKIP
      @total_amount = total_amount unless total_amount == SKIP
      @type = 'voucher'
      @url = url unless url == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      alternative_reference =
        hash.key?('alternativeReference') ? hash['alternativeReference'] : SKIP
      collection_institution_number =
        hash.key?('collectionInstitutionNumber') ? hash['collectionInstitutionNumber'] : SKIP
      download_url = hash.key?('downloadUrl') ? hash['downloadUrl'] : SKIP
      entity = hash.key?('entity') ? hash['entity'] : SKIP
      expires_at = hash.key?('expiresAt') ? hash['expiresAt'] : SKIP
      initial_amount = Amount13.from_hash(hash['initialAmount']) if hash['initialAmount']
      instructions_url =
        hash.key?('instructionsUrl') ? hash['instructionsUrl'] : SKIP
      issuer = hash.key?('issuer') ? hash['issuer'] : SKIP
      masked_telephone_number =
        hash.key?('maskedTelephoneNumber') ? hash['maskedTelephoneNumber'] : SKIP
      merchant_name = hash.key?('merchantName') ? hash['merchantName'] : SKIP
      merchant_reference =
        hash.key?('merchantReference') ? hash['merchantReference'] : SKIP
      pass_creation_token =
        hash.key?('passCreationToken') ? hash['passCreationToken'] : SKIP
      payment_data = hash.key?('paymentData') ? hash['paymentData'] : SKIP
      payment_method_type =
        hash.key?('paymentMethodType') ? hash['paymentMethodType'] : SKIP
      reference = hash.key?('reference') ? hash['reference'] : SKIP
      shopper_email = hash.key?('shopperEmail') ? hash['shopperEmail'] : SKIP
      shopper_name = hash.key?('shopperName') ? hash['shopperName'] : SKIP
      surcharge = Amount14.from_hash(hash['surcharge']) if hash['surcharge']
      total_amount = Amount15.from_hash(hash['totalAmount']) if hash['totalAmount']
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create object from extracted values.
      CheckoutVoucherAction.new(alternative_reference: alternative_reference,
                                collection_institution_number: collection_institution_number,
                                download_url: download_url,
                                entity: entity,
                                expires_at: expires_at,
                                initial_amount: initial_amount,
                                instructions_url: instructions_url,
                                issuer: issuer,
                                masked_telephone_number: masked_telephone_number,
                                merchant_name: merchant_name,
                                merchant_reference: merchant_reference,
                                pass_creation_token: pass_creation_token,
                                payment_data: payment_data,
                                payment_method_type: payment_method_type,
                                reference: reference,
                                shopper_email: shopper_email,
                                shopper_name: shopper_name,
                                surcharge: surcharge,
                                total_amount: total_amount,
                                url: url)
    end

    # Validates an instance of the object from a given value.
    # @param [CheckoutVoucherAction | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.type,
                                     ->(val) { val.instance_of? String })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['type'],
                            ->(val) { val.instance_of? String })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} alternative_reference: #{@alternative_reference},"\
      " collection_institution_number: #{@collection_institution_number}, download_url:"\
      " #{@download_url}, entity: #{@entity}, expires_at: #{@expires_at}, initial_amount:"\
      " #{@initial_amount}, instructions_url: #{@instructions_url}, issuer: #{@issuer},"\
      " masked_telephone_number: #{@masked_telephone_number}, merchant_name: #{@merchant_name},"\
      " merchant_reference: #{@merchant_reference}, pass_creation_token: #{@pass_creation_token},"\
      " payment_data: #{@payment_data}, payment_method_type: #{@payment_method_type}, reference:"\
      " #{@reference}, shopper_email: #{@shopper_email}, shopper_name: #{@shopper_name},"\
      " surcharge: #{@surcharge}, total_amount: #{@total_amount}, type: #{@type}, url: #{@url}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} alternative_reference: #{@alternative_reference.inspect},"\
      " collection_institution_number: #{@collection_institution_number.inspect}, download_url:"\
      " #{@download_url.inspect}, entity: #{@entity.inspect}, expires_at: #{@expires_at.inspect},"\
      " initial_amount: #{@initial_amount.inspect}, instructions_url:"\
      " #{@instructions_url.inspect}, issuer: #{@issuer.inspect}, masked_telephone_number:"\
      " #{@masked_telephone_number.inspect}, merchant_name: #{@merchant_name.inspect},"\
      " merchant_reference: #{@merchant_reference.inspect}, pass_creation_token:"\
      " #{@pass_creation_token.inspect}, payment_data: #{@payment_data.inspect},"\
      " payment_method_type: #{@payment_method_type.inspect}, reference: #{@reference.inspect},"\
      " shopper_email: #{@shopper_email.inspect}, shopper_name: #{@shopper_name.inspect},"\
      " surcharge: #{@surcharge.inspect}, total_amount: #{@total_amount.inspect}, type:"\
      " #{@type.inspect}, url: #{@url.inspect}>"
    end
  end
end
