# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Company2 Model.
  class Company2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # References to resources connected with this company.
    # @return [CompanyLinks2]
    attr_accessor :links

    # List of available data centers.
    # Adyen has several data centers around the world.In the URL that you use
    # for making API requests, we recommend you use the live URL prefix from the
    # data center closest to your shoppers.
    # @return [Array[DataCenter]]
    attr_accessor :data_centers

    # Your description for the company account, maximum 300 characters
    # @return [String]
    attr_accessor :description

    # The unique identifier of the company account.
    # @return [String]
    attr_accessor :id

    # The legal or trading name of the company.
    # @return [String]
    attr_accessor :name

    # Your reference to the account
    # @return [String]
    attr_accessor :reference

    # The status of the company account.
    # Possible values:
    # * **Active**: Users can log in. Processing and payout capabilities depend
    # on the status of the merchant account.
    # * **Inactive**: Users can log in. Payment processing and payouts are
    # disabled.
    # * **Closed**: The company account is closed and this cannot be reversed.
    # Users cannot log in. Payment processing and payouts are disabled.
    # @return [String]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['links'] = '_links'
      @_hash['data_centers'] = 'dataCenters'
      @_hash['description'] = 'description'
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['reference'] = 'reference'
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        links
        data_centers
        description
        id
        name
        reference
        status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(links: SKIP, data_centers: SKIP, description: SKIP, id: SKIP,
                   name: SKIP, reference: SKIP, status: SKIP)
      @links = links unless links == SKIP
      @data_centers = data_centers unless data_centers == SKIP
      @description = description unless description == SKIP
      @id = id unless id == SKIP
      @name = name unless name == SKIP
      @reference = reference unless reference == SKIP
      @status = status unless status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      links = CompanyLinks2.from_hash(hash['_links']) if hash['_links']
      # Parameter is an array, so we need to iterate through it
      data_centers = nil
      unless hash['dataCenters'].nil?
        data_centers = []
        hash['dataCenters'].each do |structure|
          data_centers << (DataCenter.from_hash(structure) if structure)
        end
      end

      data_centers = SKIP unless hash.key?('dataCenters')
      description = hash.key?('description') ? hash['description'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      reference = hash.key?('reference') ? hash['reference'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP

      # Create object from extracted values.
      Company2.new(links: links,
                   data_centers: data_centers,
                   description: description,
                   id: id,
                   name: name,
                   reference: reference,
                   status: status)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links}, data_centers: #{@data_centers}, description:"\
      " #{@description}, id: #{@id}, name: #{@name}, reference: #{@reference}, status:"\
      " #{@status}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links.inspect}, data_centers: #{@data_centers.inspect},"\
      " description: #{@description.inspect}, id: #{@id.inspect}, name: #{@name.inspect},"\
      " reference: #{@reference.inspect}, status: #{@status.inspect}>"
    end
  end
end
