# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Configuration Model.
  class Configuration < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Payment method, like **eftpos_australia** or **mc**. See the [possible
    # values](https://docs.adyen.com/development-resources/paymentmethodvariant#
    # management-api).
    # @return [String]
    attr_accessor :brand

    # Set to **true** to apply surcharges only to commercial/business cards.
    # @return [TrueClass | FalseClass]
    attr_accessor :commercial

    # The country/region of the card issuer. If used, the surcharge settings
    # only apply to the card issued in that country/region.
    # @return [Array[String]]
    attr_accessor :country

    # Currency and percentage or amount of the surcharge.
    # @return [Array[Currency]]
    attr_accessor :currencies

    # Funding source. Possible values:
    # * **Credit**
    # * **Debit**
    # @return [Array[String]]
    attr_accessor :sources

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['brand'] = 'brand'
      @_hash['commercial'] = 'commercial'
      @_hash['country'] = 'country'
      @_hash['currencies'] = 'currencies'
      @_hash['sources'] = 'sources'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        commercial
        country
        sources
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(brand:, currencies:, commercial: SKIP, country: SKIP,
                   sources: SKIP)
      @brand = brand
      @commercial = commercial unless commercial == SKIP
      @country = country unless country == SKIP
      @currencies = currencies
      @sources = sources unless sources == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      brand = hash.key?('brand') ? hash['brand'] : nil
      # Parameter is an array, so we need to iterate through it
      currencies = nil
      unless hash['currencies'].nil?
        currencies = []
        hash['currencies'].each do |structure|
          currencies << (Currency.from_hash(structure) if structure)
        end
      end

      currencies = nil unless hash.key?('currencies')
      commercial = hash.key?('commercial') ? hash['commercial'] : SKIP
      country = hash.key?('country') ? hash['country'] : SKIP
      sources = hash.key?('sources') ? hash['sources'] : SKIP

      # Create object from extracted values.
      Configuration.new(brand: brand,
                        currencies: currencies,
                        commercial: commercial,
                        country: country,
                        sources: sources)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} brand: #{@brand}, commercial: #{@commercial}, country: #{@country},"\
      " currencies: #{@currencies}, sources: #{@sources}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} brand: #{@brand.inspect}, commercial: #{@commercial.inspect}, country:"\
      " #{@country.inspect}, currencies: #{@currencies.inspect}, sources: #{@sources.inspect}>"
    end
  end
end
