# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Connectivity Model.
  class Connectivity < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Indicates the status of the SIM card in the payment terminal. Can be
    # updated and received only at terminal level, and only for models that
    # support cellular connectivity.
    # Possible values:
    # * **ACTIVATED**: the SIM card is activated. Cellular connectivity may
    # still need to be enabled on the terminal itself, in the **Network**
    # settings.
    # * **INVENTORY**: the SIM card is not activated. The terminal can't use
    # cellular connectivity.
    # @return [SimcardStatus]
    attr_accessor :simcard_status

    # The list of local and public URLs to send notifications to when using
    # local integrations.
    # @return [EventUrl3]
    attr_accessor :terminal_ip_address_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['simcard_status'] = 'simcardStatus'
      @_hash['terminal_ip_address_url'] = 'terminalIPAddressURL'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        simcard_status
        terminal_ip_address_url
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(simcard_status: SKIP, terminal_ip_address_url: SKIP)
      @simcard_status = simcard_status unless simcard_status == SKIP
      @terminal_ip_address_url = terminal_ip_address_url unless terminal_ip_address_url == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      simcard_status = hash.key?('simcardStatus') ? hash['simcardStatus'] : SKIP
      terminal_ip_address_url = EventUrl3.from_hash(hash['terminalIPAddressURL']) if
        hash['terminalIPAddressURL']

      # Create object from extracted values.
      Connectivity.new(simcard_status: simcard_status,
                       terminal_ip_address_url: terminal_ip_address_url)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} simcard_status: #{@simcard_status}, terminal_ip_address_url:"\
      " #{@terminal_ip_address_url}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} simcard_status: #{@simcard_status.inspect}, terminal_ip_address_url:"\
      " #{@terminal_ip_address_url.inspect}>"
    end
  end
end
