# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # CreateAllowedOriginRequest Model.
  class CreateAllowedOriginRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # References to resources linked to the allowed origin.
    # @return [Links2]
    attr_accessor :links

    # Domain of the allowed origin.
    # @return [String]
    attr_accessor :domain

    # Unique identifier of the allowed origin.
    # @return [String]
    attr_accessor :id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['links'] = '_links'
      @_hash['domain'] = 'domain'
      @_hash['id'] = 'id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        links
        id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(domain:, links: SKIP, id: SKIP)
      @links = links unless links == SKIP
      @domain = domain
      @id = id unless id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      domain = hash.key?('domain') ? hash['domain'] : nil
      links = Links2.from_hash(hash['_links']) if hash['_links']
      id = hash.key?('id') ? hash['id'] : SKIP

      # Create object from extracted values.
      CreateAllowedOriginRequest.new(domain: domain,
                                     links: links,
                                     id: id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links}, domain: #{@domain}, id: #{@id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links.inspect}, domain: #{@domain.inspect}, id: #{@id.inspect}>"
    end
  end
end
