# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The estimated delivery time for the shopper to receive the goods. Allowed
  # values: * `electronicDelivery` * `sameDayShipping` * `overnightShipping` *
  # `twoOrMoreDaysShipping`
  class DeliveryTimeframe
    DELIVERY_TIMEFRAME = [
      # TODO: Write general description for ELECTRONICDELIVERY
      ELECTRONICDELIVERY = 'electronicDelivery'.freeze,

      # TODO: Write general description for SAMEDAYSHIPPING
      SAMEDAYSHIPPING = 'sameDayShipping'.freeze,

      # TODO: Write general description for OVERNIGHTSHIPPING
      OVERNIGHTSHIPPING = 'overnightShipping'.freeze,

      # TODO: Write general description for TWOORMOREDAYSSHIPPING
      TWOORMOREDAYSSHIPPING = 'twoOrMoreDaysShipping'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      DELIVERY_TIMEFRAME.include?(value)
    end

    def self.from_value(value, default_value = ELECTRONICDELIVERY)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'electronicdelivery' then ELECTRONICDELIVERY
      when 'samedayshipping' then SAMEDAYSHIPPING
      when 'overnightshipping' then OVERNIGHTSHIPPING
      when 'twoormoredaysshipping' then TWOORMOREDAYSSHIPPING
      else
        default_value
      end
    end
  end
end
