# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module AdyenApIs
  # DonationPaymentRequest Model.
  class DonationPaymentRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Shopper account information for 3D Secure 2.
    # > For 3D Secure 2 transactions, we recommend that you include this object
    # to increase the chances of achieving a frictionless flow.
    # @return [AccountInfo1]
    attr_accessor :account_info

    # This field contains additional data, which may be required for a
    # particular payment request.
    # The `additionalData` object consists of entries, each of which includes
    # the key and value.
    # @return [Hash[String, String]]
    attr_accessor :additional_data

    # The amount information for the transaction (in [minor
    # units](https://docs.adyen.com/development-resources/currency-codes)). For
    # [BIN or card
    # verification](https://docs.adyen.com/payment-methods/cards/bin-data-and-ca
    # rd-verification) requests, set amount to 0 (zero).
    # @return [Amount2]
    attr_accessor :amount

    # Information about your application. For more details, see [Building Adyen
    # solutions](https://docs.adyen.com/development-resources/building-adyen-sol
    # utions).
    # @return [ApplicationInfo1]
    attr_accessor :application_info

    # Data for 3DS authentication.
    # @return [AuthenticationData3]
    attr_accessor :authentication_data

    # The address where to send the invoice.
    # > The `billingAddress` object is required in the following scenarios.
    # Include all of the fields within this object.
    # >* For 3D Secure 2 transactions in all browser-based and mobile
    # implementations.
    # >* For cross-border payouts to and from Canada.
    # @return [BillingAddress3]
    attr_accessor :billing_address

    # The shopper's browser information.
    # > For 3D Secure, the full object is required for web integrations. For
    # mobile app integrations, include the `userAgent` and `acceptHeader` fields
    # to indicate  that your integration can support a redirect in case a
    # payment is routed to 3D Secure 2 redirect.
    # @return [BrowserInfo2]
    attr_accessor :browser_info

    # The platform where a payment transaction takes place. This field is
    # optional for filtering out payment methods that are only available on
    # specific platforms. If this value is not set, then we will try to infer it
    # from the `sdkVersion` or `token`.
    # Possible values:
    # * iOS
    # * Android
    # * Web
    # @return [Channel2]
    attr_accessor :channel

    # Checkout attempt ID that corresponds to the Id generated by the client SDK
    # for tracking user payment journey.
    # @return [String]
    attr_accessor :checkout_attempt_id

    # Conversion ID that corresponds to the Id generated by the client SDK for
    # tracking user payment journey.
    # @return [String]
    attr_accessor :conversion_id

    # The shopper country.
    # Format: [ISO 3166-1
    # alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
    # Example: NL or DE
    # @return [String]
    attr_accessor :country_code

    # The shopper's date of birth.
    # Format [ISO-8601](https://www.w3.org/TR/NOTE-datetime): YYYY-MM-DD
    # @return [DateTime]
    attr_accessor :date_of_birth

    # The date and time the purchased goods should be delivered.
    # Format [ISO 8601](https://www.w3.org/TR/NOTE-datetime):
    # YYYY-MM-DDThh:mm:ss.sssTZD
    # Example: 2017-07-17T13:42:40.428+01:00
    # @return [DateTime]
    attr_accessor :deliver_at

    # The address where the purchased goods should be delivered.
    # @return [DeliveryAddress1]
    attr_accessor :delivery_address

    # A string containing the shopper's device fingerprint. For more
    # information, refer to [Device
    # fingerprinting](https://docs.adyen.com/risk-management/device-fingerprinti
    # ng).
    # @return [String]
    attr_accessor :device_fingerprint

    # Donation account to which the transaction is credited.
    # @return [String]
    attr_accessor :donation_account

    # The donation campaign ID received in the `/donationCampaigns` call.
    # @return [String]
    attr_accessor :donation_campaign_id

    # PSP reference of the transaction from which the donation token is
    # generated. Required when `donationToken` is provided.
    # @return [String]
    attr_accessor :donation_original_psp_reference

    # Donation token received in the `/payments` call.
    # @return [String]
    attr_accessor :donation_token

    # Price and product information about the purchased items, to be included on
    # the invoice sent to the shopper.
    # > This field is required for 3x 4x Oney, Affirm, Afterpay, Clearpay,
    # Klarna, Ratepay, and Riverty.
    # @return [Array[LineItem]]
    attr_accessor :line_items

    # The merchant account identifier, with which you want to process the
    # transaction.
    # @return [String]
    attr_accessor :merchant_account

    # Additional risk fields for 3D Secure 2.
    # > For 3D Secure 2 transactions, we recommend that you include this object
    # to increase the chances of achieving a frictionless flow.
    # @return [MerchantRiskIndicator1]
    attr_accessor :merchant_risk_indicator

    # Metadata consists of entries, each of which includes a key and a value.
    # Limits:
    # * Maximum 20 key-value pairs per request. When exceeding, the "177" error
    # occurs: "Metadata size exceeds limit".
    # * Maximum 20 characters per key.
    # * Maximum 80 characters per value.
    # @return [Hash[String, String]]
    attr_accessor :metadata

    # Authentication data produced by an MPI (Mastercard SecureCode, Visa
    # Secure, or Cartes Bancaires).
    # @return [ThreeDSecureData1]
    attr_accessor :mpi_data

    # > Required for browser-based (`channel` **Web**) 3D Secure 2
    # transactions.Set this to the origin URL of the page where you are
    # rendering the Drop-in/Component. Do not include subdirectories and a
    # trailing slash.
    # @return [String]
    attr_accessor :origin

    # The type and required details of a payment method to use.
    # When `donationToken` is provided, the payment method is derived from the
    # token and this field becomes optional.
    # If you are [PCI
    # compliant](https://docs.adyen.com/development-resources/pci-dss-compliance
    # -guide), and make donations using raw card details, you must explicitly
    # provide the payment method details.
    # @return [Object]
    attr_accessor :payment_method

    # Defines a recurring payment type. Required when creating a token to store
    # payment details or using stored payment details.
    # Allowed values:
    # * `Subscription` – A transaction for a fixed or variable amount, which
    # follows a fixed schedule.
    # * `CardOnFile` – With a card-on-file (CoF) transaction, card details are
    # stored to enable one-click or omnichannel journeys, or simply to
    # streamline the checkout process. Any subscription not following a fixed
    # schedule is also considered a card-on-file transaction.
    # * `UnscheduledCardOnFile` – An unscheduled card-on-file (UCoF) transaction
    # is a transaction that occurs on a non-fixed schedule and/or have variable
    # amounts. For example, automatic top-ups when a cardholder's balance drops
    # below a certain amount.
    # @return [RecurringProcessingModel]
    attr_accessor :recurring_processing_model

    # Specifies the redirect method (GET or POST) when redirecting back from the
    # issuer.
    # @return [String]
    attr_accessor :redirect_from_issuer_method

    # Specifies the redirect method (GET or POST) when redirecting to the
    # issuer.
    # @return [String]
    attr_accessor :redirect_to_issuer_method

    # The reference to uniquely identify a payment. This reference is used in
    # all communication with you about the payment status. We recommend using a
    # unique value per payment; however, it is not a requirement.
    # If you need to provide multiple references for a transaction, separate
    # them with hyphens ("-").
    # Maximum length: 80 characters.
    # @return [String]
    attr_accessor :reference

    # The URL to return to in case of a redirection.
    # The format depends on the channel. 
    # * For web, include the protocol `http://` or `https://`. You can also
    # include your own additional query parameters, for example, shopper ID or
    # order reference number.
    # Example: `https://your-company.example.com/checkout?shopperOrder=12xy`
    # * For iOS, use the custom URL for your app. To know more about setting
    # custom URL schemes, refer to the [Apple Developer
    # documentation](https://developer.apple.com/documentation/uikit/inter-proce
    # ss_communication/allowing_apps_and_websites_to_link_to_your_content/defini
    # ng_a_custom_url_scheme_for_your_app).
    # Example: `my-app://`
    # * For Android, use a custom URL handled by an Activity on your app. You
    # can configure it with an [intent
    # filter](https://developer.android.com/guide/components/intents-filters).
    # Example: `my-app://your.package.name`
    # If the URL to return to includes non-ASCII characters, like spaces or
    # special letters, URL encode the value.
    # We strongly recommend that you use a maximum of 1024 characters.
    # > The URL must not include personally identifiable information (PII), for
    # example name or email address.
    # @return [String]
    attr_accessor :return_url

    # The date and time until when the session remains valid, in [ISO
    # 8601](https://www.w3.org/TR/NOTE-datetime) format.
    # For example: 2020-07-18T15:42:40.428+01:00
    # @return [String]
    attr_accessor :session_validity

    # The shopper's email address. We recommend that you provide this data, as
    # it is used in velocity fraud checks. > Required for Visa and JCB
    # transactions that require 3D Secure 2 authentication if you did not
    # include the `telephoneNumber`.
    # @return [String]
    attr_accessor :shopper_email

    # The shopper's IP address. We recommend that you provide this data, as it
    # is used in a number of risk checks (for instance, number of payment
    # attempts or location-based checks).
    # > Required for Visa and JCB transactions that require 3D Secure 2
    # authentication for all web and mobile integrations, if you did not include
    # the `shopperEmail`. For native mobile integrations, the field is required
    # to support cases where authentication is routed to the redirect flow. This
    # field is also mandatory for some merchants depending on your business
    # model. For more information, [contact
    # Support](https://www.adyen.help/hc/en-us/requests/new).
    # @return [String]
    attr_accessor :shopper_ip

    # Specifies the sales channel, through which the shopper gives their card
    # details, and whether the shopper is a returning customer.
    # For the web service API, Adyen assumes Ecommerce shopper interaction by
    # default.
    # This field has the following possible values:
    # * `Ecommerce` - Online transactions where the cardholder is present
    # (online). For better authorization rates, we recommend sending the card
    # security code (CSC) along with the request.
    # * `ContAuth` - Card on file and/or subscription transactions, where the
    # cardholder is known to the merchant (returning customer). If the shopper
    # is present (online), you can supply also the CSC to improve authorization
    # (one-click payment).
    # * `Moto` - Mail-order and telephone-order transactions where the shopper
    # is in contact with the merchant via email or telephone.
    # * `POS` - Point-of-sale transactions where the shopper is physically
    # present to make a payment using a secure payment terminal.
    # @return [ShopperInteraction3]
    attr_accessor :shopper_interaction

    # The combination of a language code and a country code to specify the
    # language to be used in the payment.
    # @return [String]
    attr_accessor :shopper_locale

    # The shopper's full name.
    # @return [ShopperName2]
    attr_accessor :shopper_name

    # Required for recurring payments. 
    # Your reference to uniquely identify this shopper, for example user ID or
    # account ID. Minimum length: 3 characters.
    # > Your reference must not include personally identifiable information
    # (PII), for example name or email address.
    # @return [String]
    attr_accessor :shopper_reference

    # The shopper's social security number.
    # @return [String]
    attr_accessor :social_security_number

    # The shopper's telephone number.
    #  The phone number must include a plus sign (+) and a country code (1-3
    # digits), followed by the number (4-15 digits). If the value you provide
    # does not follow the guidelines, we do not submit it for authentication.
    # > Required for Visa and JCB transactions that require 3D Secure 2
    # authentication, if you did not include the `shopperEmail`.
    # @return [String]
    attr_accessor :telephone_number

    # Request fields for 3D Secure 2. To check if any of the following fields
    # are required for your integration, refer to [Online
    # payments](https://docs.adyen.com/online-payments) or [Classic
    # integration](https://docs.adyen.com/classic-integration) documentation.
    # @return [ThreeDs2RequestFields1]
    attr_accessor :three_ds2_request_data

    # Required to trigger the [authentication-only
    # flow](https://docs.adyen.com/online-payments/3d-secure/authentication-only
    # /). If set to **true**, you will only perform the 3D Secure 2
    # authentication, and will not proceed to the payment authorization.Default:
    # **false**.
    # @return [TrueClass | FalseClass]
    attr_accessor :three_ds_authentication_only

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_info'] = 'accountInfo'
      @_hash['additional_data'] = 'additionalData'
      @_hash['amount'] = 'amount'
      @_hash['application_info'] = 'applicationInfo'
      @_hash['authentication_data'] = 'authenticationData'
      @_hash['billing_address'] = 'billingAddress'
      @_hash['browser_info'] = 'browserInfo'
      @_hash['channel'] = 'channel'
      @_hash['checkout_attempt_id'] = 'checkoutAttemptId'
      @_hash['conversion_id'] = 'conversionId'
      @_hash['country_code'] = 'countryCode'
      @_hash['date_of_birth'] = 'dateOfBirth'
      @_hash['deliver_at'] = 'deliverAt'
      @_hash['delivery_address'] = 'deliveryAddress'
      @_hash['device_fingerprint'] = 'deviceFingerprint'
      @_hash['donation_account'] = 'donationAccount'
      @_hash['donation_campaign_id'] = 'donationCampaignId'
      @_hash['donation_original_psp_reference'] =
        'donationOriginalPspReference'
      @_hash['donation_token'] = 'donationToken'
      @_hash['line_items'] = 'lineItems'
      @_hash['merchant_account'] = 'merchantAccount'
      @_hash['merchant_risk_indicator'] = 'merchantRiskIndicator'
      @_hash['metadata'] = 'metadata'
      @_hash['mpi_data'] = 'mpiData'
      @_hash['origin'] = 'origin'
      @_hash['payment_method'] = 'paymentMethod'
      @_hash['recurring_processing_model'] = 'recurringProcessingModel'
      @_hash['redirect_from_issuer_method'] = 'redirectFromIssuerMethod'
      @_hash['redirect_to_issuer_method'] = 'redirectToIssuerMethod'
      @_hash['reference'] = 'reference'
      @_hash['return_url'] = 'returnUrl'
      @_hash['session_validity'] = 'sessionValidity'
      @_hash['shopper_email'] = 'shopperEmail'
      @_hash['shopper_ip'] = 'shopperIP'
      @_hash['shopper_interaction'] = 'shopperInteraction'
      @_hash['shopper_locale'] = 'shopperLocale'
      @_hash['shopper_name'] = 'shopperName'
      @_hash['shopper_reference'] = 'shopperReference'
      @_hash['social_security_number'] = 'socialSecurityNumber'
      @_hash['telephone_number'] = 'telephoneNumber'
      @_hash['three_ds2_request_data'] = 'threeDS2RequestData'
      @_hash['three_ds_authentication_only'] = 'threeDSAuthenticationOnly'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_info
        additional_data
        application_info
        authentication_data
        billing_address
        browser_info
        channel
        checkout_attempt_id
        conversion_id
        country_code
        date_of_birth
        deliver_at
        delivery_address
        device_fingerprint
        donation_account
        donation_campaign_id
        donation_original_psp_reference
        donation_token
        line_items
        merchant_risk_indicator
        metadata
        mpi_data
        origin
        payment_method
        recurring_processing_model
        redirect_from_issuer_method
        redirect_to_issuer_method
        session_validity
        shopper_email
        shopper_ip
        shopper_interaction
        shopper_locale
        shopper_name
        shopper_reference
        social_security_number
        telephone_number
        three_ds2_request_data
        three_ds_authentication_only
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(amount:, merchant_account:, reference:, return_url:,
                   account_info: SKIP, additional_data: SKIP,
                   application_info: SKIP, authentication_data: SKIP,
                   billing_address: SKIP, browser_info: SKIP, channel: SKIP,
                   checkout_attempt_id: SKIP, conversion_id: SKIP,
                   country_code: SKIP, date_of_birth: SKIP, deliver_at: SKIP,
                   delivery_address: SKIP, device_fingerprint: SKIP,
                   donation_account: SKIP, donation_campaign_id: SKIP,
                   donation_original_psp_reference: SKIP, donation_token: SKIP,
                   line_items: SKIP, merchant_risk_indicator: SKIP,
                   metadata: SKIP, mpi_data: SKIP, origin: SKIP,
                   payment_method: SKIP, recurring_processing_model: SKIP,
                   redirect_from_issuer_method: SKIP,
                   redirect_to_issuer_method: SKIP, session_validity: SKIP,
                   shopper_email: SKIP, shopper_ip: SKIP,
                   shopper_interaction: SKIP, shopper_locale: SKIP,
                   shopper_name: SKIP, shopper_reference: SKIP,
                   social_security_number: SKIP, telephone_number: SKIP,
                   three_ds2_request_data: SKIP,
                   three_ds_authentication_only: false)
      @account_info = account_info unless account_info == SKIP
      @additional_data = additional_data unless additional_data == SKIP
      @amount = amount
      @application_info = application_info unless application_info == SKIP
      @authentication_data = authentication_data unless authentication_data == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      @browser_info = browser_info unless browser_info == SKIP
      @channel = channel unless channel == SKIP
      @checkout_attempt_id = checkout_attempt_id unless checkout_attempt_id == SKIP
      @conversion_id = conversion_id unless conversion_id == SKIP
      @country_code = country_code unless country_code == SKIP
      @date_of_birth = date_of_birth unless date_of_birth == SKIP
      @deliver_at = deliver_at unless deliver_at == SKIP
      @delivery_address = delivery_address unless delivery_address == SKIP
      @device_fingerprint = device_fingerprint unless device_fingerprint == SKIP
      @donation_account = donation_account unless donation_account == SKIP
      @donation_campaign_id = donation_campaign_id unless donation_campaign_id == SKIP
      unless donation_original_psp_reference == SKIP
        @donation_original_psp_reference =
          donation_original_psp_reference
      end
      @donation_token = donation_token unless donation_token == SKIP
      @line_items = line_items unless line_items == SKIP
      @merchant_account = merchant_account
      @merchant_risk_indicator = merchant_risk_indicator unless merchant_risk_indicator == SKIP
      @metadata = metadata unless metadata == SKIP
      @mpi_data = mpi_data unless mpi_data == SKIP
      @origin = origin unless origin == SKIP
      @payment_method = payment_method unless payment_method == SKIP
      unless recurring_processing_model == SKIP
        @recurring_processing_model =
          recurring_processing_model
      end
      unless redirect_from_issuer_method == SKIP
        @redirect_from_issuer_method =
          redirect_from_issuer_method
      end
      unless redirect_to_issuer_method == SKIP
        @redirect_to_issuer_method =
          redirect_to_issuer_method
      end
      @reference = reference
      @return_url = return_url
      @session_validity = session_validity unless session_validity == SKIP
      @shopper_email = shopper_email unless shopper_email == SKIP
      @shopper_ip = shopper_ip unless shopper_ip == SKIP
      @shopper_interaction = shopper_interaction unless shopper_interaction == SKIP
      @shopper_locale = shopper_locale unless shopper_locale == SKIP
      @shopper_name = shopper_name unless shopper_name == SKIP
      @shopper_reference = shopper_reference unless shopper_reference == SKIP
      @social_security_number = social_security_number unless social_security_number == SKIP
      @telephone_number = telephone_number unless telephone_number == SKIP
      @three_ds2_request_data = three_ds2_request_data unless three_ds2_request_data == SKIP
      unless three_ds_authentication_only == SKIP
        @three_ds_authentication_only =
          three_ds_authentication_only
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = Amount2.from_hash(hash['amount']) if hash['amount']
      merchant_account =
        hash.key?('merchantAccount') ? hash['merchantAccount'] : nil
      reference = hash.key?('reference') ? hash['reference'] : nil
      return_url = hash.key?('returnUrl') ? hash['returnUrl'] : nil
      account_info = AccountInfo1.from_hash(hash['accountInfo']) if hash['accountInfo']
      additional_data =
        hash.key?('additionalData') ? hash['additionalData'] : SKIP
      application_info = ApplicationInfo1.from_hash(hash['applicationInfo']) if
        hash['applicationInfo']
      authentication_data = AuthenticationData3.from_hash(hash['authenticationData']) if
        hash['authenticationData']
      billing_address = BillingAddress3.from_hash(hash['billingAddress']) if
        hash['billingAddress']
      browser_info = BrowserInfo2.from_hash(hash['browserInfo']) if hash['browserInfo']
      channel = hash.key?('channel') ? hash['channel'] : SKIP
      checkout_attempt_id =
        hash.key?('checkoutAttemptId') ? hash['checkoutAttemptId'] : SKIP
      conversion_id = hash.key?('conversionId') ? hash['conversionId'] : SKIP
      country_code = hash.key?('countryCode') ? hash['countryCode'] : SKIP
      date_of_birth = if hash.key?('dateOfBirth')
                        (DateTimeHelper.from_rfc3339(hash['dateOfBirth']) if hash['dateOfBirth'])
                      else
                        SKIP
                      end
      deliver_at = if hash.key?('deliverAt')
                     (DateTimeHelper.from_rfc3339(hash['deliverAt']) if hash['deliverAt'])
                   else
                     SKIP
                   end
      delivery_address = DeliveryAddress1.from_hash(hash['deliveryAddress']) if
        hash['deliveryAddress']
      device_fingerprint =
        hash.key?('deviceFingerprint') ? hash['deviceFingerprint'] : SKIP
      donation_account =
        hash.key?('donationAccount') ? hash['donationAccount'] : SKIP
      donation_campaign_id =
        hash.key?('donationCampaignId') ? hash['donationCampaignId'] : SKIP
      donation_original_psp_reference =
        hash.key?('donationOriginalPspReference') ? hash['donationOriginalPspReference'] : SKIP
      donation_token = hash.key?('donationToken') ? hash['donationToken'] : SKIP
      # Parameter is an array, so we need to iterate through it
      line_items = nil
      unless hash['lineItems'].nil?
        line_items = []
        hash['lineItems'].each do |structure|
          line_items << (LineItem.from_hash(structure) if structure)
        end
      end

      line_items = SKIP unless hash.key?('lineItems')
      merchant_risk_indicator = MerchantRiskIndicator1.from_hash(hash['merchantRiskIndicator']) if
        hash['merchantRiskIndicator']
      metadata = hash.key?('metadata') ? hash['metadata'] : SKIP
      mpi_data = ThreeDSecureData1.from_hash(hash['mpiData']) if hash['mpiData']
      origin = hash.key?('origin') ? hash['origin'] : SKIP
      payment_method = hash.key?('paymentMethod') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:DonationPaymentRequestPaymentMethod), hash['paymentMethod']
      ) : SKIP
      recurring_processing_model =
        hash.key?('recurringProcessingModel') ? hash['recurringProcessingModel'] : SKIP
      redirect_from_issuer_method =
        hash.key?('redirectFromIssuerMethod') ? hash['redirectFromIssuerMethod'] : SKIP
      redirect_to_issuer_method =
        hash.key?('redirectToIssuerMethod') ? hash['redirectToIssuerMethod'] : SKIP
      session_validity =
        hash.key?('sessionValidity') ? hash['sessionValidity'] : SKIP
      shopper_email = hash.key?('shopperEmail') ? hash['shopperEmail'] : SKIP
      shopper_ip = hash.key?('shopperIP') ? hash['shopperIP'] : SKIP
      shopper_interaction =
        hash.key?('shopperInteraction') ? hash['shopperInteraction'] : SKIP
      shopper_locale = hash.key?('shopperLocale') ? hash['shopperLocale'] : SKIP
      shopper_name = ShopperName2.from_hash(hash['shopperName']) if hash['shopperName']
      shopper_reference =
        hash.key?('shopperReference') ? hash['shopperReference'] : SKIP
      social_security_number =
        hash.key?('socialSecurityNumber') ? hash['socialSecurityNumber'] : SKIP
      telephone_number =
        hash.key?('telephoneNumber') ? hash['telephoneNumber'] : SKIP
      three_ds2_request_data = ThreeDs2RequestFields1.from_hash(hash['threeDS2RequestData']) if
        hash['threeDS2RequestData']
      three_ds_authentication_only = hash['threeDSAuthenticationOnly'] ||= false

      # Create object from extracted values.
      DonationPaymentRequest.new(amount: amount,
                                 merchant_account: merchant_account,
                                 reference: reference,
                                 return_url: return_url,
                                 account_info: account_info,
                                 additional_data: additional_data,
                                 application_info: application_info,
                                 authentication_data: authentication_data,
                                 billing_address: billing_address,
                                 browser_info: browser_info,
                                 channel: channel,
                                 checkout_attempt_id: checkout_attempt_id,
                                 conversion_id: conversion_id,
                                 country_code: country_code,
                                 date_of_birth: date_of_birth,
                                 deliver_at: deliver_at,
                                 delivery_address: delivery_address,
                                 device_fingerprint: device_fingerprint,
                                 donation_account: donation_account,
                                 donation_campaign_id: donation_campaign_id,
                                 donation_original_psp_reference: donation_original_psp_reference,
                                 donation_token: donation_token,
                                 line_items: line_items,
                                 merchant_risk_indicator: merchant_risk_indicator,
                                 metadata: metadata,
                                 mpi_data: mpi_data,
                                 origin: origin,
                                 payment_method: payment_method,
                                 recurring_processing_model: recurring_processing_model,
                                 redirect_from_issuer_method: redirect_from_issuer_method,
                                 redirect_to_issuer_method: redirect_to_issuer_method,
                                 session_validity: session_validity,
                                 shopper_email: shopper_email,
                                 shopper_ip: shopper_ip,
                                 shopper_interaction: shopper_interaction,
                                 shopper_locale: shopper_locale,
                                 shopper_name: shopper_name,
                                 shopper_reference: shopper_reference,
                                 social_security_number: social_security_number,
                                 telephone_number: telephone_number,
                                 three_ds2_request_data: three_ds2_request_data,
                                 three_ds_authentication_only: three_ds_authentication_only)
    end

    def to_custom_date_of_birth
      DateTimeHelper.to_rfc3339(date_of_birth)
    end

    def to_custom_deliver_at
      DateTimeHelper.to_rfc3339(deliver_at)
    end

    # Validates an instance of the object from a given value.
    # @param [DonationPaymentRequest | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.amount,
                                ->(val) { Amount2.validate(val) },
                                is_model_hash: true) and
            APIHelper.valid_type?(value.merchant_account,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.reference,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.return_url,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['amount'],
                              ->(val) { Amount2.validate(val) },
                              is_model_hash: true) and
          APIHelper.valid_type?(value['merchantAccount'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['reference'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['returnUrl'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_info: #{@account_info}, additional_data: #{@additional_data},"\
      " amount: #{@amount}, application_info: #{@application_info}, authentication_data:"\
      " #{@authentication_data}, billing_address: #{@billing_address}, browser_info:"\
      " #{@browser_info}, channel: #{@channel}, checkout_attempt_id: #{@checkout_attempt_id},"\
      " conversion_id: #{@conversion_id}, country_code: #{@country_code}, date_of_birth:"\
      " #{@date_of_birth}, deliver_at: #{@deliver_at}, delivery_address: #{@delivery_address},"\
      " device_fingerprint: #{@device_fingerprint}, donation_account: #{@donation_account},"\
      " donation_campaign_id: #{@donation_campaign_id}, donation_original_psp_reference:"\
      " #{@donation_original_psp_reference}, donation_token: #{@donation_token}, line_items:"\
      " #{@line_items}, merchant_account: #{@merchant_account}, merchant_risk_indicator:"\
      " #{@merchant_risk_indicator}, metadata: #{@metadata}, mpi_data: #{@mpi_data}, origin:"\
      " #{@origin}, payment_method: #{@payment_method}, recurring_processing_model:"\
      " #{@recurring_processing_model}, redirect_from_issuer_method:"\
      " #{@redirect_from_issuer_method}, redirect_to_issuer_method: #{@redirect_to_issuer_method},"\
      " reference: #{@reference}, return_url: #{@return_url}, session_validity:"\
      " #{@session_validity}, shopper_email: #{@shopper_email}, shopper_ip: #{@shopper_ip},"\
      " shopper_interaction: #{@shopper_interaction}, shopper_locale: #{@shopper_locale},"\
      " shopper_name: #{@shopper_name}, shopper_reference: #{@shopper_reference},"\
      " social_security_number: #{@social_security_number}, telephone_number:"\
      " #{@telephone_number}, three_ds2_request_data: #{@three_ds2_request_data},"\
      " three_ds_authentication_only: #{@three_ds_authentication_only}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_info: #{@account_info.inspect}, additional_data:"\
      " #{@additional_data.inspect}, amount: #{@amount.inspect}, application_info:"\
      " #{@application_info.inspect}, authentication_data: #{@authentication_data.inspect},"\
      " billing_address: #{@billing_address.inspect}, browser_info: #{@browser_info.inspect},"\
      " channel: #{@channel.inspect}, checkout_attempt_id: #{@checkout_attempt_id.inspect},"\
      " conversion_id: #{@conversion_id.inspect}, country_code: #{@country_code.inspect},"\
      " date_of_birth: #{@date_of_birth.inspect}, deliver_at: #{@deliver_at.inspect},"\
      " delivery_address: #{@delivery_address.inspect}, device_fingerprint:"\
      " #{@device_fingerprint.inspect}, donation_account: #{@donation_account.inspect},"\
      " donation_campaign_id: #{@donation_campaign_id.inspect}, donation_original_psp_reference:"\
      " #{@donation_original_psp_reference.inspect}, donation_token: #{@donation_token.inspect},"\
      " line_items: #{@line_items.inspect}, merchant_account: #{@merchant_account.inspect},"\
      " merchant_risk_indicator: #{@merchant_risk_indicator.inspect}, metadata:"\
      " #{@metadata.inspect}, mpi_data: #{@mpi_data.inspect}, origin: #{@origin.inspect},"\
      " payment_method: #{@payment_method.inspect}, recurring_processing_model:"\
      " #{@recurring_processing_model.inspect}, redirect_from_issuer_method:"\
      " #{@redirect_from_issuer_method.inspect}, redirect_to_issuer_method:"\
      " #{@redirect_to_issuer_method.inspect}, reference: #{@reference.inspect}, return_url:"\
      " #{@return_url.inspect}, session_validity: #{@session_validity.inspect}, shopper_email:"\
      " #{@shopper_email.inspect}, shopper_ip: #{@shopper_ip.inspect}, shopper_interaction:"\
      " #{@shopper_interaction.inspect}, shopper_locale: #{@shopper_locale.inspect}, shopper_name:"\
      " #{@shopper_name.inspect}, shopper_reference: #{@shopper_reference.inspect},"\
      " social_security_number: #{@social_security_number.inspect}, telephone_number:"\
      " #{@telephone_number.inspect}, three_ds2_request_data: #{@three_ds2_request_data.inspect},"\
      " three_ds_authentication_only: #{@three_ds_authentication_only.inspect}>"
    end
  end
end
