# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # DonationCampaignsResponse Model.
  class DonationCampaignsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # List of active donation campaigns for your merchant account.
    # @return [Array[DonationCampaign]]
    attr_accessor :donation_campaigns

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['donation_campaigns'] = 'donationCampaigns'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        donation_campaigns
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(donation_campaigns: SKIP)
      @donation_campaigns = donation_campaigns unless donation_campaigns == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      donation_campaigns = nil
      unless hash['donationCampaigns'].nil?
        donation_campaigns = []
        hash['donationCampaigns'].each do |structure|
          donation_campaigns << (DonationCampaign.from_hash(structure) if structure)
        end
      end

      donation_campaigns = SKIP unless hash.key?('donationCampaigns')

      # Create object from extracted values.
      DonationCampaignsResponse.new(donation_campaigns: donation_campaigns)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} donation_campaigns: #{@donation_campaigns}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} donation_campaigns: #{@donation_campaigns.inspect}>"
    end
  end
end
