# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Dragonpay Model.
  class Dragonpay < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The checkout attempt identifier.
    # @return [String]
    attr_accessor :checkout_attempt_id

    # The Dragonpay issuer value of the shopper's selected bank. Set this to an
    # **id** of a Dragonpay issuer to preselect it.
    # @return [String]
    attr_accessor :issuer

    # Base64-encoded JSON object containing SDK related parameters required by
    # the SDK
    # @return [String]
    attr_accessor :sdk_data

    # The shopper’s email address.
    # @return [String]
    attr_accessor :shopper_email

    # **dragonpay**
    # @return [Type23]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['checkout_attempt_id'] = 'checkoutAttemptId'
      @_hash['issuer'] = 'issuer'
      @_hash['sdk_data'] = 'sdkData'
      @_hash['shopper_email'] = 'shopperEmail'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        checkout_attempt_id
        sdk_data
        shopper_email
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(issuer:, type:, checkout_attempt_id: SKIP, sdk_data: SKIP,
                   shopper_email: SKIP)
      @checkout_attempt_id = checkout_attempt_id unless checkout_attempt_id == SKIP
      @issuer = issuer
      @sdk_data = sdk_data unless sdk_data == SKIP
      @shopper_email = shopper_email unless shopper_email == SKIP
      @type = type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      issuer = hash.key?('issuer') ? hash['issuer'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      checkout_attempt_id =
        hash.key?('checkoutAttemptId') ? hash['checkoutAttemptId'] : SKIP
      sdk_data = hash.key?('sdkData') ? hash['sdkData'] : SKIP
      shopper_email = hash.key?('shopperEmail') ? hash['shopperEmail'] : SKIP

      # Create object from extracted values.
      Dragonpay.new(issuer: issuer,
                    type: type,
                    checkout_attempt_id: checkout_attempt_id,
                    sdk_data: sdk_data,
                    shopper_email: shopper_email)
    end

    # Validates an instance of the object from a given value.
    # @param [Dragonpay | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.issuer,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.type,
                                  ->(val) { Type23.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['issuer'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['type'],
                                ->(val) { Type23.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id}, issuer: #{@issuer}, sdk_data:"\
      " #{@sdk_data}, shopper_email: #{@shopper_email}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id.inspect}, issuer:"\
      " #{@issuer.inspect}, sdk_data: #{@sdk_data.inspect}, shopper_email:"\
      " #{@shopper_email.inspect}, type: #{@type.inspect}>"
    end
  end
end
