# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # SSL version to access the public webhook URL specified in the `url` field.
  # Possible values: * **TLSv1.3** * **TLSv1.2** * **HTTP** - Only allowed on
  # Test environment. If not specified, the webhook will use `sslVersion`:
  # **TLSv1.2**.
  class EncryptionProtocol
    ENCRYPTION_PROTOCOL = [
      # TODO: Write general description for HTTP
      HTTP = 'HTTP'.freeze,

      # TODO: Write general description for ENUM_TLSV12
      ENUM_TLSV12 = 'TLSv1.2'.freeze,

      # TODO: Write general description for ENUM_TLSV13
      ENUM_TLSV13 = 'TLSv1.3'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ENCRYPTION_PROTOCOL.include?(value)
    end

    def self.from_value(value, default_value = HTTP)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'http' then HTTP
      when 'enum_tlsv12' then ENUM_TLSV12
      when 'enum_tlsv13' then ENUM_TLSV13
      else
        default_value
      end
    end
  end
end
