# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The order information required for partial payments.
  class EncryptedOrderData2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The encrypted order data.
    # @return [String]
    attr_accessor :order_data

    # The `pspReference` that belongs to the order.
    # @return [String]
    attr_accessor :psp_reference

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['order_data'] = 'orderData'
      @_hash['psp_reference'] = 'pspReference'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(order_data:, psp_reference:)
      @order_data = order_data
      @psp_reference = psp_reference
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      order_data = hash.key?('orderData') ? hash['orderData'] : nil
      psp_reference = hash.key?('pspReference') ? hash['pspReference'] : nil

      # Create object from extracted values.
      EncryptedOrderData2.new(order_data: order_data,
                              psp_reference: psp_reference)
    end

    # Validates an instance of the object from a given value.
    # @param [EncryptedOrderData2 | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.order_data,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.psp_reference,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['orderData'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['pspReference'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} order_data: #{@order_data}, psp_reference: #{@psp_reference}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} order_data: #{@order_data.inspect}, psp_reference:"\
      " #{@psp_reference.inspect}>"
    end
  end
end
