# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Third-party developed platform used to initiate payment requests. For
  # example, Magento, Zuora, etc.
  class ExternalPlatform2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # External platform integrator.
    # @return [String]
    attr_accessor :integrator

    # Name of the field. For example, Name of External Platform.
    # @return [String]
    attr_accessor :name

    # Version of the field. For example, Version of External Platform.
    # @return [String]
    attr_accessor :version

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['integrator'] = 'integrator'
      @_hash['name'] = 'name'
      @_hash['version'] = 'version'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        integrator
        name
        version
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(integrator: SKIP, name: SKIP, version: SKIP)
      @integrator = integrator unless integrator == SKIP
      @name = name unless name == SKIP
      @version = version unless version == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      integrator = hash.key?('integrator') ? hash['integrator'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      version = hash.key?('version') ? hash['version'] : SKIP

      # Create object from extracted values.
      ExternalPlatform2.new(integrator: integrator,
                            name: name,
                            version: version)
    end

    # Validates an instance of the object from a given value.
    # @param [ExternalPlatform2 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} integrator: #{@integrator}, name: #{@name}, version: #{@version}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} integrator: #{@integrator.inspect}, name: #{@name.inspect}, version:"\
      " #{@version.inspect}>"
    end
  end
end
