# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module AdyenApIs
  # The forex quote as returned in the response of the forex service.
  class ForexQuote2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The account name.
    # @return [String]
    attr_accessor :account

    # The account type.
    # @return [String]
    attr_accessor :account_type

    # The base amount.
    # @return [Amount3]
    attr_accessor :base_amount

    # The base points.
    # @return [Integer]
    attr_accessor :base_points

    # The buy rate.
    # @return [Amount4]
    attr_accessor :buy

    # The interbank amount.
    # @return [Amount5]
    attr_accessor :interbank

    # The reference assigned to the forex quote request.
    # @return [String]
    attr_accessor :reference

    # The sell rate.
    # @return [Amount6]
    attr_accessor :sell

    # The signature to validate the integrity.
    # @return [String]
    attr_accessor :signature

    # The source of the forex quote.
    # @return [String]
    attr_accessor :source

    # The type of forex.
    # @return [String]
    attr_accessor :type

    # The date until which the forex quote is valid.
    # @return [DateTime]
    attr_accessor :valid_till

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account'] = 'account'
      @_hash['account_type'] = 'accountType'
      @_hash['base_amount'] = 'baseAmount'
      @_hash['base_points'] = 'basePoints'
      @_hash['buy'] = 'buy'
      @_hash['interbank'] = 'interbank'
      @_hash['reference'] = 'reference'
      @_hash['sell'] = 'sell'
      @_hash['signature'] = 'signature'
      @_hash['source'] = 'source'
      @_hash['type'] = 'type'
      @_hash['valid_till'] = 'validTill'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account
        account_type
        base_amount
        buy
        interbank
        reference
        sell
        signature
        source
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(base_points:, valid_till:, account: SKIP, account_type: SKIP,
                   base_amount: SKIP, buy: SKIP, interbank: SKIP,
                   reference: SKIP, sell: SKIP, signature: SKIP, source: SKIP,
                   type: SKIP)
      @account = account unless account == SKIP
      @account_type = account_type unless account_type == SKIP
      @base_amount = base_amount unless base_amount == SKIP
      @base_points = base_points
      @buy = buy unless buy == SKIP
      @interbank = interbank unless interbank == SKIP
      @reference = reference unless reference == SKIP
      @sell = sell unless sell == SKIP
      @signature = signature unless signature == SKIP
      @source = source unless source == SKIP
      @type = type unless type == SKIP
      @valid_till = valid_till
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      base_points = hash.key?('basePoints') ? hash['basePoints'] : nil
      valid_till = if hash.key?('validTill')
                     (DateTimeHelper.from_rfc3339(hash['validTill']) if hash['validTill'])
                   end
      account = hash.key?('account') ? hash['account'] : SKIP
      account_type = hash.key?('accountType') ? hash['accountType'] : SKIP
      base_amount = Amount3.from_hash(hash['baseAmount']) if hash['baseAmount']
      buy = Amount4.from_hash(hash['buy']) if hash['buy']
      interbank = Amount5.from_hash(hash['interbank']) if hash['interbank']
      reference = hash.key?('reference') ? hash['reference'] : SKIP
      sell = Amount6.from_hash(hash['sell']) if hash['sell']
      signature = hash.key?('signature') ? hash['signature'] : SKIP
      source = hash.key?('source') ? hash['source'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      ForexQuote2.new(base_points: base_points,
                      valid_till: valid_till,
                      account: account,
                      account_type: account_type,
                      base_amount: base_amount,
                      buy: buy,
                      interbank: interbank,
                      reference: reference,
                      sell: sell,
                      signature: signature,
                      source: source,
                      type: type)
    end

    def to_custom_valid_till
      DateTimeHelper.to_rfc3339(valid_till)
    end

    # Validates an instance of the object from a given value.
    # @param [ForexQuote2 | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.base_points,
                                ->(val) { val.instance_of? Integer }) and
            APIHelper.valid_type?(value.valid_till,
                                  ->(val) { val.instance_of? DateTime })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['basePoints'],
                              ->(val) { val.instance_of? Integer }) and
          APIHelper.valid_type?(value['validTill'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account: #{@account}, account_type: #{@account_type}, base_amount:"\
      " #{@base_amount}, base_points: #{@base_points}, buy: #{@buy}, interbank: #{@interbank},"\
      " reference: #{@reference}, sell: #{@sell}, signature: #{@signature}, source: #{@source},"\
      " type: #{@type}, valid_till: #{@valid_till}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account: #{@account.inspect}, account_type: #{@account_type.inspect},"\
      " base_amount: #{@base_amount.inspect}, base_points: #{@base_points.inspect}, buy:"\
      " #{@buy.inspect}, interbank: #{@interbank.inspect}, reference: #{@reference.inspect}, sell:"\
      " #{@sell.inspect}, signature: #{@signature.inspect}, source: #{@source.inspect}, type:"\
      " #{@type.inspect}, valid_till: #{@valid_till.inspect}>"
    end
  end
end
