# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The risk level of the transaction as classified by the [machine
  # learning](https://docs.adyen.com/risk-management/configure-your-risk-profile
  # /machine-learning-rules/) fraud risk rule. The risk level indicates the
  # likelihood that a transaction will result in a fraudulent dispute. Possible
  # values: * veryLow * low * medium * high * veryHigh
  class FraudRiskLevel
    FRAUD_RISK_LEVEL = [
      # TODO: Write general description for VERYLOW
      VERYLOW = 'veryLow'.freeze,

      # TODO: Write general description for LOW
      LOW = 'low'.freeze,

      # TODO: Write general description for MEDIUM
      MEDIUM = 'medium'.freeze,

      # TODO: Write general description for HIGH
      HIGH = 'high'.freeze,

      # TODO: Write general description for VERYHIGH
      VERYHIGH = 'veryHigh'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      FRAUD_RISK_LEVEL.include?(value)
    end

    def self.from_value(value, default_value = VERYLOW)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'verylow' then VERYLOW
      when 'low' then LOW
      when 'medium' then MEDIUM
      when 'high' then HIGH
      when 'veryhigh' then VERYHIGH
      else
        default_value
      end
    end
  end
end
