# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The funding source of the payment method.
  class FundingSource9
    FUNDING_SOURCE9 = [
      # TODO: Write general description for CREDIT
      CREDIT = 'credit'.freeze,

      # TODO: Write general description for DEBIT
      DEBIT = 'debit'.freeze,

      # TODO: Write general description for PREPAID
      PREPAID = 'prepaid'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      FUNDING_SOURCE9.include?(value)
    end

    def self.from_value(value, default_value = CREDIT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'credit' then CREDIT
      when 'debit' then DEBIT
      when 'prepaid' then PREPAID
      else
        default_value
      end
    end
  end
end
