# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The person or entity funding the money.
  class FundOrigin1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The address where to send the invoice.
    # @return [Address3]
    attr_accessor :billing_address

    # The email address of the person funding the money.
    # @return [String]
    attr_accessor :shopper_email

    # The name of the person funding the money.
    # @return [Name1]
    attr_accessor :shopper_name

    # The phone number of the person funding the money.
    # @return [String]
    attr_accessor :telephone_number

    # The unique identifier of the wallet where the funds are coming from.
    # @return [String]
    attr_accessor :wallet_identifier

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['billing_address'] = 'billingAddress'
      @_hash['shopper_email'] = 'shopperEmail'
      @_hash['shopper_name'] = 'shopperName'
      @_hash['telephone_number'] = 'telephoneNumber'
      @_hash['wallet_identifier'] = 'walletIdentifier'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        billing_address
        shopper_email
        shopper_name
        telephone_number
        wallet_identifier
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(billing_address: SKIP, shopper_email: SKIP,
                   shopper_name: SKIP, telephone_number: SKIP,
                   wallet_identifier: SKIP)
      @billing_address = billing_address unless billing_address == SKIP
      @shopper_email = shopper_email unless shopper_email == SKIP
      @shopper_name = shopper_name unless shopper_name == SKIP
      @telephone_number = telephone_number unless telephone_number == SKIP
      @wallet_identifier = wallet_identifier unless wallet_identifier == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      billing_address = Address3.from_hash(hash['billingAddress']) if hash['billingAddress']
      shopper_email = hash.key?('shopperEmail') ? hash['shopperEmail'] : SKIP
      shopper_name = Name1.from_hash(hash['shopperName']) if hash['shopperName']
      telephone_number =
        hash.key?('telephoneNumber') ? hash['telephoneNumber'] : SKIP
      wallet_identifier =
        hash.key?('walletIdentifier') ? hash['walletIdentifier'] : SKIP

      # Create object from extracted values.
      FundOrigin1.new(billing_address: billing_address,
                      shopper_email: shopper_email,
                      shopper_name: shopper_name,
                      telephone_number: telephone_number,
                      wallet_identifier: wallet_identifier)
    end

    # Validates an instance of the object from a given value.
    # @param [FundOrigin1 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_address: #{@billing_address}, shopper_email: #{@shopper_email},"\
      " shopper_name: #{@shopper_name}, telephone_number: #{@telephone_number}, wallet_identifier:"\
      " #{@wallet_identifier}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_address: #{@billing_address.inspect}, shopper_email:"\
      " #{@shopper_email.inspect}, shopper_name: #{@shopper_name.inspect}, telephone_number:"\
      " #{@telephone_number.inspect}, wallet_identifier: #{@wallet_identifier.inspect}>"
    end
  end
end
