# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The funding source of the payment method. Possible values: * **credit** *
  # **debit** * **prepaid** * **deferred_debit** * **charged** * **ANY**
  class FundingSource1
    FUNDING_SOURCE1 = [
      # TODO: Write general description for CHARGED
      CHARGED = 'charged'.freeze,

      # TODO: Write general description for CREDIT
      CREDIT = 'credit'.freeze,

      # TODO: Write general description for DEBIT
      DEBIT = 'debit'.freeze,

      # TODO: Write general description for DEFERRED_DEBIT
      DEFERRED_DEBIT = 'deferred_debit'.freeze,

      # TODO: Write general description for PREPAID
      PREPAID = 'prepaid'.freeze,

      # TODO: Write general description for ANY
      ANY = 'ANY'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      FUNDING_SOURCE1.include?(value)
    end

    def self.from_value(value, default_value = CHARGED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'charged' then CHARGED
      when 'credit' then CREDIT
      when 'debit' then DEBIT
      when 'deferred_debit' then DEFERRED_DEBIT
      when 'prepaid' then PREPAID
      when 'any' then ANY
      else
        default_value
      end
    end
  end
end
