# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Details to provide if `type` is **eft_directdebit_CA** (EFT PAD).
  class GenericPmWithTdiInfo3 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Information regarding the transaction description.
    # > You cannot configure the transaction description in the test
    # environment.
    # @return [TransactionDescriptionInfo1]
    attr_accessor :transaction_description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['transaction_description'] = 'transactionDescription'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        transaction_description
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(transaction_description: SKIP)
      @transaction_description = transaction_description unless transaction_description == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      if hash['transactionDescription']
        transaction_description = TransactionDescriptionInfo1.from_hash(hash['transactionDescription'])
      end

      # Create object from extracted values.
      GenericPmWithTdiInfo3.new(transaction_description: transaction_description)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} transaction_description: #{@transaction_description}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} transaction_description: #{@transaction_description.inspect}>"
    end
  end
end
