# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # GenerateApiKeyResponse Model.
  class GenerateApiKeyResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The generated API key.
    # @return [String]
    attr_accessor :api_key

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['api_key'] = 'apiKey'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(api_key:)
      @api_key = api_key
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      api_key = hash.key?('apiKey') ? hash['apiKey'] : nil

      # Create object from extracted values.
      GenerateApiKeyResponse.new(api_key: api_key)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} api_key: #{@api_key}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} api_key: #{@api_key.inspect}>"
    end
  end
end
