# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Hardware Model.
  class Hardware < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The brightness of the display when the terminal is being used, expressed
    # as a percentage.
    # @return [Integer]
    attr_accessor :display_maximum_back_light

    # The hour of the day when the terminal is set to reset the Totals report.
    # By default, the reset hour is at 6:00 AM in the timezone of the terminal.
    # Minimum value: 0, maximum value: 23.
    # @return [Integer]
    attr_accessor :reset_totals_hour

    # The hour of the day when the terminal is set to reboot to apply the
    # configuration and software updates. By default, the restart hour is at
    # 6:00 AM in the timezone of the terminal. Minimum value: 0, maximum value:
    # 23.
    # @return [Integer]
    attr_accessor :restart_hour

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['display_maximum_back_light'] = 'displayMaximumBackLight'
      @_hash['reset_totals_hour'] = 'resetTotalsHour'
      @_hash['restart_hour'] = 'restartHour'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        display_maximum_back_light
        reset_totals_hour
        restart_hour
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(display_maximum_back_light: SKIP, reset_totals_hour: SKIP,
                   restart_hour: SKIP)
      unless display_maximum_back_light == SKIP
        @display_maximum_back_light =
          display_maximum_back_light
      end
      @reset_totals_hour = reset_totals_hour unless reset_totals_hour == SKIP
      @restart_hour = restart_hour unless restart_hour == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      display_maximum_back_light =
        hash.key?('displayMaximumBackLight') ? hash['displayMaximumBackLight'] : SKIP
      reset_totals_hour =
        hash.key?('resetTotalsHour') ? hash['resetTotalsHour'] : SKIP
      restart_hour = hash.key?('restartHour') ? hash['restartHour'] : SKIP

      # Create object from extracted values.
      Hardware.new(display_maximum_back_light: display_maximum_back_light,
                   reset_totals_hour: reset_totals_hour,
                   restart_hour: restart_hour)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} display_maximum_back_light: #{@display_maximum_back_light},"\
      " reset_totals_hour: #{@reset_totals_hour}, restart_hour: #{@restart_hour}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} display_maximum_back_light: #{@display_maximum_back_light.inspect},"\
      " reset_totals_hour: #{@reset_totals_hour.inspect}, restart_hour: #{@restart_hour.inspect}>"
    end
  end
end
