# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The HTTP method to use for the request Adyen makes on your behalf to the
  # third party.
  class HttpMethod
    HTTP_METHOD = [
      # TODO: Write general description for POST
      POST = 'post'.freeze,

      # TODO: Write general description for PUT
      PUT = 'put'.freeze,

      # TODO: Write general description for PATCH
      PATCH = 'patch'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      HTTP_METHOD.include?(value)
    end

    def self.from_value(value, default_value = POST)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'post' then POST
      when 'put' then PUT
      when 'patch' then PATCH
      else
        default_value
      end
    end
  end
end
