# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # In case of [asynchronous authorisation
  # adjustment](https://docs.adyen.com/online-payments/adjust-authorisation#adju
  # st-authorisation), this field denotes why the additional payment is made.
  # Possible values:  * **NoShow**: An incremental charge is carried out because
  # of a no-show for a guaranteed reservation.  * **DelayedCharge**: An
  # incremental charge is carried out to process an additional payment after the
  # original services have been rendered and the respective payment has been
  # processed.
  class IndustryUsage
    INDUSTRY_USAGE = [
      # TODO: Write general description for NOSHOW
      NOSHOW = 'NoShow'.freeze,

      # TODO: Write general description for DELAYEDCHARGE
      DELAYEDCHARGE = 'DelayedCharge'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      INDUSTRY_USAGE.include?(value)
    end

    def self.from_value(value, default_value = NOSHOW)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'noshow' then NOSHOW
      when 'delayedcharge' then DELAYEDCHARGE
      else
        default_value
      end
    end
  end
end
