# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Details to provide if `type` is **jcb**. For merchants operating in Japan,
  # `midNumber`, `reuseMidNumber`, and `serviceLevel` fields are required. For
  # merchants operating outside of Japan, these fields are not required.
  class JcbInfo1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # MID (Merchant ID) number. Required for merchants operating in Japan or
    # merchants operating in Canada, Australia and New Zealand when requesting
    # `gatewayContract` or `paymentDesignatorContract` service levels.Format: 14
    # numeric characters for Japan, 10 numeric characters for Canada, Australia
    # and New Zealand.
    # @return [String]
    attr_accessor :mid_number

    # Indicates whether the JCB Merchant ID is reused from a previously setup
    # JCB payment method. 
    # The default value is **false**.For merchants operating in Japan, this
    # field is required and must be set to **true**.
    # @return [TrueClass | FalseClass]
    attr_accessor :reuse_mid_number

    # Specifies the service level (settlement type) of this payment method.
    # Required for merchants operating in Japan.
    # Possible values:
    # * **noContract**: Adyen holds the contract with JCB for merchants
    # operating in Japan or American Express for merchants operating in Canada,
    # Australia and New Zealand.
    # * **gatewayContract**: JCB or American Express receives the settlement and
    # handles disputes, then pays out to you or your sub-merchant directly.
    # * **paymentDesignatorContract**: Available only for merchants operating in
    # Canada, Australia and New Zealand. Adyen receives the settlement, and
    # handles disputes and payouts.
    # @return [ServiceLevel2]
    attr_accessor :service_level

    # Information regarding the transaction description.
    # > You cannot configure the transaction description in the test
    # environment.
    # @return [TransactionDescriptionInfo1]
    attr_accessor :transaction_description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['mid_number'] = 'midNumber'
      @_hash['reuse_mid_number'] = 'reuseMidNumber'
      @_hash['service_level'] = 'serviceLevel'
      @_hash['transaction_description'] = 'transactionDescription'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        mid_number
        reuse_mid_number
        service_level
        transaction_description
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(mid_number: SKIP, reuse_mid_number: false,
                   service_level: SKIP, transaction_description: SKIP)
      @mid_number = mid_number unless mid_number == SKIP
      @reuse_mid_number = reuse_mid_number unless reuse_mid_number == SKIP
      @service_level = service_level unless service_level == SKIP
      @transaction_description = transaction_description unless transaction_description == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      mid_number = hash.key?('midNumber') ? hash['midNumber'] : SKIP
      reuse_mid_number = hash['reuseMidNumber'] ||= false
      service_level = hash.key?('serviceLevel') ? hash['serviceLevel'] : SKIP
      if hash['transactionDescription']
        transaction_description = TransactionDescriptionInfo1.from_hash(hash['transactionDescription'])
      end

      # Create object from extracted values.
      JcbInfo1.new(mid_number: mid_number,
                   reuse_mid_number: reuse_mid_number,
                   service_level: service_level,
                   transaction_description: transaction_description)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} mid_number: #{@mid_number}, reuse_mid_number: #{@reuse_mid_number},"\
      " service_level: #{@service_level}, transaction_description: #{@transaction_description}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} mid_number: #{@mid_number.inspect}, reuse_mid_number:"\
      " #{@reuse_mid_number.inspect}, service_level: #{@service_level.inspect},"\
      " transaction_description: #{@transaction_description.inspect}>"
    end
  end
end
