# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # ListStoresResponse Model.
  class ListStoresResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Pagination references.
    # @return [PaginationLinks1]
    attr_accessor :links

    # List of stores
    # @return [Array[Store]]
    attr_accessor :data

    # Total number of items.
    # @return [Integer]
    attr_accessor :items_total

    # Total number of pages.
    # @return [Integer]
    attr_accessor :pages_total

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['links'] = '_links'
      @_hash['data'] = 'data'
      @_hash['items_total'] = 'itemsTotal'
      @_hash['pages_total'] = 'pagesTotal'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        links
        data
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(items_total:, pages_total:, links: SKIP, data: SKIP)
      @links = links unless links == SKIP
      @data = data unless data == SKIP
      @items_total = items_total
      @pages_total = pages_total
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      items_total = hash.key?('itemsTotal') ? hash['itemsTotal'] : nil
      pages_total = hash.key?('pagesTotal') ? hash['pagesTotal'] : nil
      links = PaginationLinks1.from_hash(hash['_links']) if hash['_links']
      # Parameter is an array, so we need to iterate through it
      data = nil
      unless hash['data'].nil?
        data = []
        hash['data'].each do |structure|
          data << (Store.from_hash(structure) if structure)
        end
      end

      data = SKIP unless hash.key?('data')

      # Create object from extracted values.
      ListStoresResponse.new(items_total: items_total,
                             pages_total: pages_total,
                             links: links,
                             data: data)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links}, data: #{@data}, items_total: #{@items_total},"\
      " pages_total: #{@pages_total}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links.inspect}, data: #{@data.inspect}, items_total:"\
      " #{@items_total.inspect}, pages_total: #{@pages_total.inspect}>"
    end
  end
end
