# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # LocalShopperStatement Model.
  class LocalShopperStatement < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The character set of the local shopper statement.
    # Possible values: **ja-Hani**, **ja-Kana**.
    # @return [String]
    attr_accessor :script

    # The text of the local shopper statement in the specified character set.
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['script'] = 'script'
      @_hash['value'] = 'value'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(script:, value:)
      @script = script
      @value = value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      script = hash.key?('script') ? hash['script'] : nil
      value = hash.key?('value') ? hash['value'] : nil

      # Create object from extracted values.
      LocalShopperStatement.new(script: script,
                                value: value)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} script: #{@script}, value: #{@value}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} script: #{@script.inspect}, value: #{@value.inspect}>"
    end
  end
end
