# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # MealVoucherFrInfo Model.
  class MealVoucherFrInfo < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Meal Voucher conecsId. Format: digits only
    # @return [String]
    attr_accessor :conecs_id

    # Meal Voucher siret. Format: 14 digits.
    # @return [String]
    attr_accessor :siret

    # The list of additional payment methods. Allowed values:
    # **mealVoucher_FR_edenred**, **mealVoucher_FR_groupeup**,
    # **mealVoucher_FR_natixis**, **mealVoucher_FR_sodexo**.
    # @return [Array[String]]
    attr_accessor :sub_types

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['conecs_id'] = 'conecsId'
      @_hash['siret'] = 'siret'
      @_hash['sub_types'] = 'subTypes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(conecs_id:, siret:, sub_types:)
      @conecs_id = conecs_id
      @siret = siret
      @sub_types = sub_types
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      conecs_id = hash.key?('conecsId') ? hash['conecsId'] : nil
      siret = hash.key?('siret') ? hash['siret'] : nil
      sub_types = hash.key?('subTypes') ? hash['subTypes'] : nil

      # Create object from extracted values.
      MealVoucherFrInfo.new(conecs_id: conecs_id,
                            siret: siret,
                            sub_types: sub_types)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} conecs_id: #{@conecs_id}, siret: #{@siret}, sub_types: #{@sub_types}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} conecs_id: #{@conecs_id.inspect}, siret: #{@siret.inspect}, sub_types:"\
      " #{@sub_types.inspect}>"
    end
  end
end
