# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The shopper's full name. This object is required for some payment methods
  # such as AfterPay, Klarna, or if you're enrolled in the PayPal Seller
  # Protection program.
  class Name4 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The first name.
    # @return [String]
    attr_accessor :first_name

    # The last name.
    # @return [String]
    attr_accessor :last_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first_name'] = 'firstName'
      @_hash['last_name'] = 'lastName'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(first_name:, last_name:)
      @first_name = first_name
      @last_name = last_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      first_name = hash.key?('firstName') ? hash['firstName'] : nil
      last_name = hash.key?('lastName') ? hash['lastName'] : nil

      # Create object from extracted values.
      Name4.new(first_name: first_name,
                last_name: last_name)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} first_name: #{@first_name}, last_name: #{@last_name}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} first_name: #{@first_name.inspect}, last_name: #{@last_name.inspect}>"
    end
  end
end
