# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # PaginationLinks Model.
  class PaginationLinks < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The first page.
    # @return [LinksElement9]
    attr_accessor :first

    # The last page.
    # @return [LinksElement10]
    attr_accessor :last

    # The next page. Only present if there is a next page.
    # @return [LinksElement11]
    attr_accessor :mnext

    # The previous page. Only present if there is a previous page.
    # @return [LinksElement12]
    attr_accessor :prev

    # The current page.
    # @return [LinksElement13]
    attr_accessor :mself

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first'] = 'first'
      @_hash['last'] = 'last'
      @_hash['mnext'] = 'next'
      @_hash['prev'] = 'prev'
      @_hash['mself'] = 'self'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        mnext
        prev
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(first:, last:, mself:, mnext: SKIP, prev: SKIP)
      @first = first
      @last = last
      @mnext = mnext unless mnext == SKIP
      @prev = prev unless prev == SKIP
      @mself = mself
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      first = LinksElement9.from_hash(hash['first']) if hash['first']
      last = LinksElement10.from_hash(hash['last']) if hash['last']
      mself = LinksElement13.from_hash(hash['self']) if hash['self']
      mnext = LinksElement11.from_hash(hash['next']) if hash['next']
      prev = LinksElement12.from_hash(hash['prev']) if hash['prev']

      # Create object from extracted values.
      PaginationLinks.new(first: first,
                          last: last,
                          mself: mself,
                          mnext: mnext,
                          prev: prev)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} first: #{@first}, last: #{@last}, mnext: #{@mnext}, prev: #{@prev}, mself:"\
      " #{@mself}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} first: #{@first.inspect}, last: #{@last.inspect}, mnext: #{@mnext.inspect},"\
      " prev: #{@prev.inspect}, mself: #{@mself.inspect}>"
    end
  end
end
