# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Passenger Model.
  class Passenger < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The passenger's date of birth.
    # * Format `yyyy-MM-dd`
    # * minLength: 10
    # * maxLength: 10
    # @return [Date]
    attr_accessor :date_of_birth

    # The passenger's first name.
    # > This field is required if the airline data includes passenger details or
    # leg details.
    # * Encoding: ASCII
    # @return [String]
    attr_accessor :first_name

    # The passenger's last name.
    # > This field is required if the airline data includes passenger details or
    # leg details.
    # * Encoding: ASCII
    # @return [String]
    attr_accessor :last_name

    # The passenger's phone number, including country code. This is an
    # alphanumeric field that can include the '+' and '-' signs.
    # * Encoding: ASCII
    # * minLength: 3 characters
    # * maxLength: 30 characters
    # @return [String]
    attr_accessor :phone_number

    # The IATA passenger type code (PTC).
    # * Encoding: ASCII
    # * minLength: 3 characters
    # * maxLength: 6 characters
    # @return [String]
    attr_accessor :traveller_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['date_of_birth'] = 'dateOfBirth'
      @_hash['first_name'] = 'firstName'
      @_hash['last_name'] = 'lastName'
      @_hash['phone_number'] = 'phoneNumber'
      @_hash['traveller_type'] = 'travellerType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        date_of_birth
        first_name
        last_name
        phone_number
        traveller_type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(date_of_birth: SKIP, first_name: SKIP, last_name: SKIP,
                   phone_number: SKIP, traveller_type: SKIP)
      @date_of_birth = date_of_birth unless date_of_birth == SKIP
      @first_name = first_name unless first_name == SKIP
      @last_name = last_name unless last_name == SKIP
      @phone_number = phone_number unless phone_number == SKIP
      @traveller_type = traveller_type unless traveller_type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      date_of_birth = hash.key?('dateOfBirth') ? hash['dateOfBirth'] : SKIP
      first_name = hash.key?('firstName') ? hash['firstName'] : SKIP
      last_name = hash.key?('lastName') ? hash['lastName'] : SKIP
      phone_number = hash.key?('phoneNumber') ? hash['phoneNumber'] : SKIP
      traveller_type = hash.key?('travellerType') ? hash['travellerType'] : SKIP

      # Create object from extracted values.
      Passenger.new(date_of_birth: date_of_birth,
                    first_name: first_name,
                    last_name: last_name,
                    phone_number: phone_number,
                    traveller_type: traveller_type)
    end

    # Validates an instance of the object from a given value.
    # @param [Passenger | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} date_of_birth: #{@date_of_birth}, first_name: #{@first_name}, last_name:"\
      " #{@last_name}, phone_number: #{@phone_number}, traveller_type: #{@traveller_type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} date_of_birth: #{@date_of_birth.inspect}, first_name:"\
      " #{@first_name.inspect}, last_name: #{@last_name.inspect}, phone_number:"\
      " #{@phone_number.inspect}, traveller_type: #{@traveller_type.inspect}>"
    end
  end
end
