# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Object that contains the status and outcomes of the [name
  # validation](https://docs.adyen.com/payment-methods/cards/name-validation).
  class PaymentValidationsNameResponse2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains the raw response(s) returned by the scheme for the name
    # validation.
    # @return [PaymentValidationsNameResultRawResponse2]
    attr_accessor :raw_response

    # Contains the scheme-agnostic match values returned by Adyen.
    # @return [PaymentValidationsNameResultResponse2]
    attr_accessor :result

    # Informs you if the name validation was performed. Possible values:
    # **performed**, **notPerformed**, **notSupported**
    # @return [Status]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['raw_response'] = 'rawResponse'
      @_hash['result'] = 'result'
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        raw_response
        result
        status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(raw_response: SKIP, result: SKIP, status: SKIP)
      @raw_response = raw_response unless raw_response == SKIP
      @result = result unless result == SKIP
      @status = status unless status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      raw_response = PaymentValidationsNameResultRawResponse2.from_hash(hash['rawResponse']) if
        hash['rawResponse']
      result = PaymentValidationsNameResultResponse2.from_hash(hash['result']) if hash['result']
      status = hash.key?('status') ? hash['status'] : SKIP

      # Create object from extracted values.
      PaymentValidationsNameResponse2.new(raw_response: raw_response,
                                          result: result,
                                          status: status)
    end

    # Validates an instance of the object from a given value.
    # @param [PaymentValidationsNameResponse2 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} raw_response: #{@raw_response}, result: #{@result}, status: #{@status}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} raw_response: #{@raw_response.inspect}, result: #{@result.inspect}, status:"\
      " #{@status.inspect}>"
    end
  end
end
