# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # PaymentDetails Model.
  class PaymentDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The checkout attempt identifier.
    # @return [String]
    attr_accessor :checkout_attempt_id

    # Base64-encoded JSON object containing SDK related parameters required by
    # the SDK
    # @return [String]
    attr_accessor :sdk_data

    # The payment method type.
    # @return [Type38]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['checkout_attempt_id'] = 'checkoutAttemptId'
      @_hash['sdk_data'] = 'sdkData'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        checkout_attempt_id
        sdk_data
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(checkout_attempt_id: SKIP, sdk_data: SKIP, type: SKIP)
      @checkout_attempt_id = checkout_attempt_id unless checkout_attempt_id == SKIP
      @sdk_data = sdk_data unless sdk_data == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      checkout_attempt_id =
        hash.key?('checkoutAttemptId') ? hash['checkoutAttemptId'] : SKIP
      sdk_data = hash.key?('sdkData') ? hash['sdkData'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      PaymentDetails.new(checkout_attempt_id: checkout_attempt_id,
                         sdk_data: sdk_data,
                         type: type)
    end

    # Validates an instance of the object from a given value.
    # @param [PaymentDetails | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id}, sdk_data: #{@sdk_data}, type:"\
      " #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id.inspect}, sdk_data:"\
      " #{@sdk_data.inspect}, type: #{@type.inspect}>"
    end
  end
end
