# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Sets the allowed payment instrument for Pay at table transactions.  Can be:
  # **cash** or **card**. If not set, the terminal presents both options.
  class PaymentInstrument
    PAYMENT_INSTRUMENT = [
      # TODO: Write general description for CASH
      CASH = 'Cash'.freeze,

      # TODO: Write general description for CARD
      CARD = 'Card'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYMENT_INSTRUMENT.include?(value)
    end

    def self.from_value(value, default_value = CASH)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'cash' then CASH
      when 'card' then CARD
      else
        default_value
      end
    end
  end
end
