# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The object that contains the validation outcomes. Only returned if
  # `resultCode` is **Authorised** and if you have requested a payment
  # validation in the request.
  class PaymentResponse2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Object that contains the status and outcomes of the [name
    # validation](https://docs.adyen.com/payment-methods/cards/name-validation).
    # @return [PaymentValidationsNameResponse2]
    attr_accessor :name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP)
      @name = name unless name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = PaymentValidationsNameResponse2.from_hash(hash['name']) if hash['name']

      # Create object from extracted values.
      PaymentResponse2.new(name: name)
    end

    # Validates an instance of the object from a given value.
    # @param [PaymentResponse2 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name.inspect}>"
    end
  end
end
