# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # PaypalUpdateOrderRequest Model.
  class PaypalUpdateOrderRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The updated final payment amount. This amount is the item total plus the
    # shipping costs of the selected `deliveryMethod`.
    # @return [Amount43]
    attr_accessor :amount

    # The list of new delivery methods and the cost of each.
    # @return [Array[DeliveryMethod]]
    attr_accessor :delivery_methods

    # The `paymentData` from the client side. This value changes every time you
    # make a `/paypal/updateOrder` request.
    # @return [String]
    attr_accessor :payment_data

    # The original `pspReference` from the `/payments` response.
    # @return [String]
    attr_accessor :psp_reference

    # The original `sessionId` from the `/sessions` response.
    # @return [String]
    attr_accessor :session_id

    # Total tax amount from the order.
    # @return [TaxTotal2]
    attr_accessor :tax_total

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount'] = 'amount'
      @_hash['delivery_methods'] = 'deliveryMethods'
      @_hash['payment_data'] = 'paymentData'
      @_hash['psp_reference'] = 'pspReference'
      @_hash['session_id'] = 'sessionId'
      @_hash['tax_total'] = 'taxTotal'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        amount
        delivery_methods
        payment_data
        psp_reference
        session_id
        tax_total
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(amount: SKIP, delivery_methods: SKIP, payment_data: SKIP,
                   psp_reference: SKIP, session_id: SKIP, tax_total: SKIP)
      @amount = amount unless amount == SKIP
      @delivery_methods = delivery_methods unless delivery_methods == SKIP
      @payment_data = payment_data unless payment_data == SKIP
      @psp_reference = psp_reference unless psp_reference == SKIP
      @session_id = session_id unless session_id == SKIP
      @tax_total = tax_total unless tax_total == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = Amount43.from_hash(hash['amount']) if hash['amount']
      # Parameter is an array, so we need to iterate through it
      delivery_methods = nil
      unless hash['deliveryMethods'].nil?
        delivery_methods = []
        hash['deliveryMethods'].each do |structure|
          delivery_methods << (DeliveryMethod.from_hash(structure) if structure)
        end
      end

      delivery_methods = SKIP unless hash.key?('deliveryMethods')
      payment_data = hash.key?('paymentData') ? hash['paymentData'] : SKIP
      psp_reference = hash.key?('pspReference') ? hash['pspReference'] : SKIP
      session_id = hash.key?('sessionId') ? hash['sessionId'] : SKIP
      tax_total = TaxTotal2.from_hash(hash['taxTotal']) if hash['taxTotal']

      # Create object from extracted values.
      PaypalUpdateOrderRequest.new(amount: amount,
                                   delivery_methods: delivery_methods,
                                   payment_data: payment_data,
                                   psp_reference: psp_reference,
                                   session_id: session_id,
                                   tax_total: tax_total)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount}, delivery_methods: #{@delivery_methods}, payment_data:"\
      " #{@payment_data}, psp_reference: #{@psp_reference}, session_id: #{@session_id}, tax_total:"\
      " #{@tax_total}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount.inspect}, delivery_methods: #{@delivery_methods.inspect},"\
      " payment_data: #{@payment_data.inspect}, psp_reference: #{@psp_reference.inspect},"\
      " session_id: #{@session_id.inspect}, tax_total: #{@tax_total.inspect}>"
    end
  end
end
