# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Phone Model.
  class Phone < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Country code. Length: 1–3 digits.
    # @return [String]
    attr_accessor :cc

    # Subscriber number. Length: 4-15  digits.
    # @return [String]
    attr_accessor :subscriber

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['cc'] = 'cc'
      @_hash['subscriber'] = 'subscriber'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        cc
        subscriber
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(cc: SKIP, subscriber: SKIP)
      @cc = cc unless cc == SKIP
      @subscriber = subscriber unless subscriber == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      cc = hash.key?('cc') ? hash['cc'] : SKIP
      subscriber = hash.key?('subscriber') ? hash['subscriber'] : SKIP

      # Create object from extracted values.
      Phone.new(cc: cc,
                subscriber: subscriber)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} cc: #{@cc}, subscriber: #{@subscriber}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} cc: #{@cc.inspect}, subscriber: #{@subscriber.inspect}>"
    end
  end
end
