# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Merchant price plan
  class PricePlan
    PRICE_PLAN = [
      # TODO: Write general description for BRONZE
      BRONZE = 'BRONZE'.freeze,

      # TODO: Write general description for SILVER
      SILVER = 'SILVER'.freeze,

      # TODO: Write general description for GOLD
      GOLD = 'GOLD'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PRICE_PLAN.include?(value)
    end

    def self.from_value(value, default_value = BRONZE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'bronze' then BRONZE
      when 'silver' then SILVER
      when 'gold' then GOLD
      else
        default_value
      end
    end
  end
end
