# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Settings for refunds.
  class Refunds1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Settings for referenced refunds.
    # @return [Referenced1]
    attr_accessor :referenced

    # Settings for unreferenced refunds.
    # @return [Unreferenced2]
    attr_accessor :unreferenced

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['referenced'] = 'referenced'
      @_hash['unreferenced'] = 'unreferenced'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        referenced
        unreferenced
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(referenced: SKIP, unreferenced: SKIP)
      @referenced = referenced unless referenced == SKIP
      @unreferenced = unreferenced unless unreferenced == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      referenced = Referenced1.from_hash(hash['referenced']) if hash['referenced']
      unreferenced = Unreferenced2.from_hash(hash['unreferenced']) if hash['unreferenced']

      # Create object from extracted values.
      Refunds1.new(referenced: referenced,
                   unreferenced: unreferenced)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} referenced: #{@referenced}, unreferenced: #{@unreferenced}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} referenced: #{@referenced.inspect}, unreferenced:"\
      " #{@unreferenced.inspect}>"
    end
  end
end
