# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # ReleaseUpdateDetails Model.
  class ReleaseUpdateDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Type of terminal action: Update Release.
    # @return [Type53]
    attr_accessor :type

    # Boolean flag that tells if the terminal should update at the first next
    # maintenance call. If false, terminal will update on its configured reboot
    # time.
    # @return [TrueClass | FalseClass]
    attr_accessor :update_at_first_maintenance_call

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['update_at_first_maintenance_call'] =
        'updateAtFirstMaintenanceCall'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        update_at_first_maintenance_call
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type: Type53::RELEASEUPDATE,
                   update_at_first_maintenance_call: SKIP)
      @type = type unless type == SKIP
      unless update_at_first_maintenance_call == SKIP
        @update_at_first_maintenance_call =
          update_at_first_maintenance_call
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash['type'] ||= Type53::RELEASEUPDATE
      update_at_first_maintenance_call =
        hash.key?('updateAtFirstMaintenanceCall') ? hash['updateAtFirstMaintenanceCall'] : SKIP

      # Create object from extracted values.
      ReleaseUpdateDetails.new(type: type,
                               update_at_first_maintenance_call: update_at_first_maintenance_call)
    end

    # Validates an instance of the object from a given value.
    # @param [ReleaseUpdateDetails | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, update_at_first_maintenance_call:"\
      " #{@update_at_first_maintenance_call}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, update_at_first_maintenance_call:"\
      " #{@update_at_first_maintenance_call.inspect}>"
    end
  end
end
