# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # RequiredShopperField.
  class RequiredShopperField
    REQUIRED_SHOPPER_FIELD = [
      # TODO: Write general description for BILLINGADDRESS
      BILLINGADDRESS = 'billingAddress'.freeze,

      # TODO: Write general description for DELIVERYADDRESS
      DELIVERYADDRESS = 'deliveryAddress'.freeze,

      # TODO: Write general description for SHOPPEREMAIL
      SHOPPEREMAIL = 'shopperEmail'.freeze,

      # TODO: Write general description for SHOPPERNAME
      SHOPPERNAME = 'shopperName'.freeze,

      # TODO: Write general description for TELEPHONENUMBER
      TELEPHONENUMBER = 'telephoneNumber'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      REQUIRED_SHOPPER_FIELD.include?(value)
    end

    def self.from_value(value, default_value = BILLINGADDRESS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'billingaddress' then BILLINGADDRESS
      when 'deliveryaddress' then DELIVERYADDRESS
      when 'shopperemail' then SHOPPEREMAIL
      when 'shoppername' then SHOPPERNAME
      when 'telephonenumber' then TELEPHONENUMBER
      else
        default_value
      end
    end
  end
end
