# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # SdkUiType.
  class SdkUiType
    SDK_UI_TYPE = [
      # TODO: Write general description for MULTISELECT
      MULTISELECT = 'multiSelect'.freeze,

      # TODO: Write general description for OTHERHTML
      OTHERHTML = 'otherHtml'.freeze,

      # TODO: Write general description for OUTOFBAND
      OUTOFBAND = 'outOfBand'.freeze,

      # TODO: Write general description for SINGLESELECT
      SINGLESELECT = 'singleSelect'.freeze,

      # TODO: Write general description for TEXT
      TEXT = 'text'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      SDK_UI_TYPE.include?(value)
    end

    def self.from_value(value, default_value = MULTISELECT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'multiselect' then MULTISELECT
      when 'otherhtml' then OTHERHTML
      when 'outofband' then OUTOFBAND
      when 'singleselect' then SINGLESELECT
      when 'text' then TEXT
      else
        default_value
      end
    end
  end
end
