# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # StandalonePaymentCancelResponse Model.
  class StandalonePaymentCancelResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The merchant account that is used to process the payment.
    # @return [String]
    attr_accessor :merchant_account

    # The
    # [`reference`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest
    # /post/payments__reqParam_reference) of the payment to cancel.
    # @return [String]
    attr_accessor :payment_reference

    # Adyen's 16-character reference associated with the cancel request.
    # @return [String]
    attr_accessor :psp_reference

    # Your reference for the cancel request.
    # @return [String]
    attr_accessor :reference

    # The status of your request. This will always have the value **received**.
    # @return [String]
    attr_reader :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['merchant_account'] = 'merchantAccount'
      @_hash['payment_reference'] = 'paymentReference'
      @_hash['psp_reference'] = 'pspReference'
      @_hash['reference'] = 'reference'
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        reference
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(merchant_account:, payment_reference:, psp_reference:,
                   reference: SKIP)
      @merchant_account = merchant_account
      @payment_reference = payment_reference
      @psp_reference = psp_reference
      @reference = reference unless reference == SKIP
      @status = 'received'
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      merchant_account =
        hash.key?('merchantAccount') ? hash['merchantAccount'] : nil
      payment_reference =
        hash.key?('paymentReference') ? hash['paymentReference'] : nil
      psp_reference = hash.key?('pspReference') ? hash['pspReference'] : nil
      reference = hash.key?('reference') ? hash['reference'] : SKIP

      # Create object from extracted values.
      StandalonePaymentCancelResponse.new(merchant_account: merchant_account,
                                          payment_reference: payment_reference,
                                          psp_reference: psp_reference,
                                          reference: reference)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} merchant_account: #{@merchant_account}, payment_reference:"\
      " #{@payment_reference}, psp_reference: #{@psp_reference}, reference: #{@reference}, status:"\
      " #{@status}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} merchant_account: #{@merchant_account.inspect}, payment_reference:"\
      " #{@payment_reference.inspect}, psp_reference: #{@psp_reference.inspect}, reference:"\
      " #{@reference.inspect}, status: #{@status.inspect}>"
    end
  end
end
