# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The status of the store. Possible values are: - **active**: This value is
  # assigned automatically when a store is created.  - **inactive**: The maximum
  # [transaction limits and number of Store-and-Forward
  # transactions](https://docs.adyen.com/point-of-sale/determine-account-structu
  # re/configure-features#payment-features) for the store are set to 0. This
  # blocks new transactions, but captures are still possible. - **closed**: The
  # terminals of the store are reassigned to the merchant inventory, so they
  # can't process payments. You can change the status from **active** to
  # **inactive**, and from **inactive** to **active** or **closed**.  Once
  # **closed**, a store can't be reopened.
  class Status41
    STATUS41 = [
      # TODO: Write general description for ACTIVE
      ACTIVE = 'active'.freeze,

      # TODO: Write general description for CLOSED
      CLOSED = 'closed'.freeze,

      # TODO: Write general description for INACTIVE
      INACTIVE = 'inactive'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS41.include?(value)
    end

    def self.from_value(value, default_value = ACTIVE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'active' then ACTIVE
      when 'closed' then CLOSED
      when 'inactive' then INACTIVE
      else
        default_value
      end
    end
  end
end
