# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The status of the reassignment. Possible values:   *
  # `reassignmentInProgress`: the terminal was boarded and is now scheduled to
  # remove the configuration. Wait for the terminal to synchronize with the
  # Adyen platform.  * `deployed`: the terminal is deployed and reassigned.   *
  # `inventory`: the terminal is in inventory and cannot process transactions.
  # * `boarded`: the terminal is boarded to a store, or a merchant account
  # representing a store, and can process transactions.
  class Status21
    STATUS21 = [
      # TODO: Write general description for BOARDED
      BOARDED = 'boarded'.freeze,

      # TODO: Write general description for DEPLOYED
      DEPLOYED = 'deployed'.freeze,

      # TODO: Write general description for INVENTORY
      INVENTORY = 'inventory'.freeze,

      # TODO: Write general description for REASSIGNMENTINPROGRESS
      REASSIGNMENTINPROGRESS = 'reassignmentInProgress'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS21.include?(value)
    end

    def self.from_value(value, default_value = BOARDED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'boarded' then BOARDED
      when 'deployed' then DEPLOYED
      when 'inventory' then INVENTORY
      when 'reassignmentinprogress' then REASSIGNMENTINPROGRESS
      else
        default_value
      end
    end
  end
end
