# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The status of the request. This indicates whether the order was successfully
  # updated with PayPal.
  class Status3
    STATUS3 = [
      # TODO: Write general description for ERROR
      ERROR = 'error'.freeze,

      # TODO: Write general description for SUCCESS
      SUCCESS = 'success'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS3.include?(value)
    end

    def self.from_value(value, default_value = ERROR)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'error' then ERROR
      when 'success' then SUCCESS
      else
        default_value
      end
    end
  end
end
