# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # StoredPaymentMethod1 Model.
  class StoredPaymentMethod1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The checkout attempt identifier.
    # @return [String]
    attr_accessor :checkout_attempt_id

    # The issuer id of the shopper's selected bank.
    # @return [String]
    attr_accessor :issuer

    # This is the `recurringDetailReference` returned in the response when you
    # created the token.
    # @return [String]
    attr_accessor :recurring_detail_reference

    # Base64-encoded JSON object containing SDK related parameters required by
    # the SDK
    # @return [String]
    attr_accessor :sdk_data

    # This is the `recurringDetailReference` returned in the response when you
    # created the token.
    # @return [String]
    attr_accessor :stored_payment_method_id

    # **genericissuer**
    # @return [Type26]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['checkout_attempt_id'] = 'checkoutAttemptId'
      @_hash['issuer'] = 'issuer'
      @_hash['recurring_detail_reference'] = 'recurringDetailReference'
      @_hash['sdk_data'] = 'sdkData'
      @_hash['stored_payment_method_id'] = 'storedPaymentMethodId'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        checkout_attempt_id
        recurring_detail_reference
        sdk_data
        stored_payment_method_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(issuer:, type:, checkout_attempt_id: SKIP,
                   recurring_detail_reference: SKIP, sdk_data: SKIP,
                   stored_payment_method_id: SKIP)
      @checkout_attempt_id = checkout_attempt_id unless checkout_attempt_id == SKIP
      @issuer = issuer
      unless recurring_detail_reference == SKIP
        @recurring_detail_reference =
          recurring_detail_reference
      end
      @sdk_data = sdk_data unless sdk_data == SKIP
      @stored_payment_method_id = stored_payment_method_id unless stored_payment_method_id == SKIP
      @type = type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      issuer = hash.key?('issuer') ? hash['issuer'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      checkout_attempt_id =
        hash.key?('checkoutAttemptId') ? hash['checkoutAttemptId'] : SKIP
      recurring_detail_reference =
        hash.key?('recurringDetailReference') ? hash['recurringDetailReference'] : SKIP
      sdk_data = hash.key?('sdkData') ? hash['sdkData'] : SKIP
      stored_payment_method_id =
        hash.key?('storedPaymentMethodId') ? hash['storedPaymentMethodId'] : SKIP

      # Create object from extracted values.
      StoredPaymentMethod1.new(issuer: issuer,
                               type: type,
                               checkout_attempt_id: checkout_attempt_id,
                               recurring_detail_reference: recurring_detail_reference,
                               sdk_data: sdk_data,
                               stored_payment_method_id: stored_payment_method_id)
    end

    # Validates an instance of the object from a given value.
    # @param [StoredPaymentMethod1 | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.issuer,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.type,
                                  ->(val) { Type26.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['issuer'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['type'],
                                ->(val) { Type26.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id}, issuer: #{@issuer},"\
      " recurring_detail_reference: #{@recurring_detail_reference}, sdk_data: #{@sdk_data},"\
      " stored_payment_method_id: #{@stored_payment_method_id}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} checkout_attempt_id: #{@checkout_attempt_id.inspect}, issuer:"\
      " #{@issuer.inspect}, recurring_detail_reference: #{@recurring_detail_reference.inspect},"\
      " sdk_data: #{@sdk_data.inspect}, stored_payment_method_id:"\
      " #{@stored_payment_method_id.inspect}, type: #{@type.inspect}>"
    end
  end
end
