# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Indicates if the details of the payment method will be stored for the
  # shopper. Possible values: * **disabled** – No details will be stored
  # (default). * **askForConsent** – If the `shopperReference` is provided, the
  # Drop-in/Component shows a checkbox where the shopper can select to store
  # their payment details for card payments. * **enabled** – If the
  # `shopperReference` is provided, the details will be stored without asking
  # the shopper for consent.   When set to **askForConsent** or **enabled**, you
  # must also include the `recurringProcessingModel` parameter.
  class StorePaymentMethodMode2
    STORE_PAYMENT_METHOD_MODE2 = [
      # TODO: Write general description for ASKFORCONSENT
      ASKFORCONSENT = 'askForConsent'.freeze,

      # TODO: Write general description for DISABLED
      DISABLED = 'disabled'.freeze,

      # TODO: Write general description for ENABLED
      ENABLED = 'enabled'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STORE_PAYMENT_METHOD_MODE2.include?(value)
    end

    def self.from_value(value, default_value = ASKFORCONSENT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'askforconsent' then ASKFORCONSENT
      when 'disabled' then DISABLED
      when 'enabled' then ENABLED
      else
        default_value
      end
    end
  end
end
