# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Details to provide if `type` is **swish**.  - This field is required only if
  # you have a contract with Swish. Swish handles settlement directly with you
  # (not through Adyen).  - If not specified then it's assumed that you are
  # using Adyen's contract with Swish.You don't have a direct relationship with
  # Swish.
  class SwishInfo1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Swish number. Format: 10 digits without spaces. For example,
    # **1231111111**.
    # @return [String]
    attr_accessor :swish_number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['swish_number'] = 'swishNumber'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(swish_number:)
      @swish_number = swish_number
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      swish_number = hash.key?('swishNumber') ? hash['swishNumber'] : nil

      # Create object from extracted values.
      SwishInfo1.new(swish_number: swish_number)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} swish_number: #{@swish_number}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} swish_number: #{@swish_number.inspect}>"
    end
  end
end
