# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Settings for Tap to Pay.
  class TapToPay1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The text shown on the screen during the Tap to Pay transaction.
    # @return [String]
    attr_accessor :merchant_display_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['merchant_display_name'] = 'merchantDisplayName'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        merchant_display_name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(merchant_display_name: SKIP)
      @merchant_display_name = merchant_display_name unless merchant_display_name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      merchant_display_name =
        hash.key?('merchantDisplayName') ? hash['merchantDisplayName'] : SKIP

      # Create object from extracted values.
      TapToPay1.new(merchant_display_name: merchant_display_name)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} merchant_display_name: #{@merchant_display_name}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} merchant_display_name: #{@merchant_display_name.inspect}>"
    end
  end
end
