# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # TerminalConnectivityEthernet Model.
  class TerminalConnectivityEthernet < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The terminal's ethernet IP address.
    # @return [String]
    attr_accessor :ip_address

    # The ethernet link negotiation that the terminal uses.
    # @return [String]
    attr_accessor :link_negotiation

    # The terminal's ethernet MAC address.
    # @return [String]
    attr_accessor :mac_address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ip_address'] = 'ipAddress'
      @_hash['link_negotiation'] = 'linkNegotiation'
      @_hash['mac_address'] = 'macAddress'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        ip_address
        link_negotiation
        mac_address
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(ip_address: SKIP, link_negotiation: SKIP, mac_address: SKIP)
      @ip_address = ip_address unless ip_address == SKIP
      @link_negotiation = link_negotiation unless link_negotiation == SKIP
      @mac_address = mac_address unless mac_address == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ip_address = hash.key?('ipAddress') ? hash['ipAddress'] : SKIP
      link_negotiation =
        hash.key?('linkNegotiation') ? hash['linkNegotiation'] : SKIP
      mac_address = hash.key?('macAddress') ? hash['macAddress'] : SKIP

      # Create object from extracted values.
      TerminalConnectivityEthernet.new(ip_address: ip_address,
                                       link_negotiation: link_negotiation,
                                       mac_address: mac_address)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} ip_address: #{@ip_address}, link_negotiation: #{@link_negotiation},"\
      " mac_address: #{@mac_address}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} ip_address: #{@ip_address.inspect}, link_negotiation:"\
      " #{@link_negotiation.inspect}, mac_address: #{@mac_address.inspect}>"
    end
  end
end
