# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Indicates where the terminal is in the process of being reassigned to.
  class TerminalReassignmentTarget2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique identifier of the company account to which the terminal is
    # reassigned.
    # @return [String]
    attr_accessor :company_id

    # Indicates if the terminal is reassigned to the inventory of the merchant
    # account.
    # - If **true**, the terminal is in the inventory of the merchant account
    # and cannot process transactions.
    # - If **false**, the terminal is reassigned directly to the merchant
    # account and can process transactions.
    # @return [TrueClass | FalseClass]
    attr_accessor :inventory

    # The unique identifier of the merchant account to which the terminal is
    # reassigned.
    # @return [String]
    attr_accessor :merchant_id

    # The unique identifier of the store to which the terminal is reassigned.
    # @return [String]
    attr_accessor :store_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['company_id'] = 'companyId'
      @_hash['inventory'] = 'inventory'
      @_hash['merchant_id'] = 'merchantId'
      @_hash['store_id'] = 'storeId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        company_id
        merchant_id
        store_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(inventory:, company_id: SKIP, merchant_id: SKIP,
                   store_id: SKIP)
      @company_id = company_id unless company_id == SKIP
      @inventory = inventory
      @merchant_id = merchant_id unless merchant_id == SKIP
      @store_id = store_id unless store_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      inventory = hash.key?('inventory') ? hash['inventory'] : nil
      company_id = hash.key?('companyId') ? hash['companyId'] : SKIP
      merchant_id = hash.key?('merchantId') ? hash['merchantId'] : SKIP
      store_id = hash.key?('storeId') ? hash['storeId'] : SKIP

      # Create object from extracted values.
      TerminalReassignmentTarget2.new(inventory: inventory,
                                      company_id: company_id,
                                      merchant_id: merchant_id,
                                      store_id: store_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} company_id: #{@company_id}, inventory: #{@inventory}, merchant_id:"\
      " #{@merchant_id}, store_id: #{@store_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} company_id: #{@company_id.inspect}, inventory: #{@inventory.inspect},"\
      " merchant_id: #{@merchant_id.inspect}, store_id: #{@store_id.inspect}>"
    end
  end
end
