# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # TerminalOrder Model.
  class TerminalOrder < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The details of the entity that the order is billed to.
    # @return [BillingEntity1]
    attr_accessor :billing_entity

    # The merchant-defined purchase order number. This will be printed on the
    # packing list.
    # @return [String]
    attr_accessor :customer_order_reference

    # The unique identifier of the order.
    # @return [String]
    attr_accessor :id

    # The products included in the order.
    # @return [Array[OrderItem]]
    attr_accessor :items

    # The date and time that the order was placed, in UTC ISO 8601 format. For
    # example, "2011-12-03T10:15:30Z".
    # @return [String]
    attr_accessor :order_date

    # The details of the location where the order is shipped to.
    # @return [ShippingLocation1]
    attr_accessor :shipping_location

    # The processing status of the order.
    # @return [String]
    attr_accessor :status

    # The URL, provided by the carrier company, where the shipment can be
    # tracked.
    # @return [String]
    attr_accessor :tracking_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['billing_entity'] = 'billingEntity'
      @_hash['customer_order_reference'] = 'customerOrderReference'
      @_hash['id'] = 'id'
      @_hash['items'] = 'items'
      @_hash['order_date'] = 'orderDate'
      @_hash['shipping_location'] = 'shippingLocation'
      @_hash['status'] = 'status'
      @_hash['tracking_url'] = 'trackingUrl'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        billing_entity
        customer_order_reference
        id
        items
        order_date
        shipping_location
        status
        tracking_url
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(billing_entity: SKIP, customer_order_reference: SKIP,
                   id: SKIP, items: SKIP, order_date: SKIP,
                   shipping_location: SKIP, status: SKIP, tracking_url: SKIP)
      @billing_entity = billing_entity unless billing_entity == SKIP
      @customer_order_reference = customer_order_reference unless customer_order_reference == SKIP
      @id = id unless id == SKIP
      @items = items unless items == SKIP
      @order_date = order_date unless order_date == SKIP
      @shipping_location = shipping_location unless shipping_location == SKIP
      @status = status unless status == SKIP
      @tracking_url = tracking_url unless tracking_url == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      billing_entity = BillingEntity1.from_hash(hash['billingEntity']) if hash['billingEntity']
      customer_order_reference =
        hash.key?('customerOrderReference') ? hash['customerOrderReference'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      # Parameter is an array, so we need to iterate through it
      items = nil
      unless hash['items'].nil?
        items = []
        hash['items'].each do |structure|
          items << (OrderItem.from_hash(structure) if structure)
        end
      end

      items = SKIP unless hash.key?('items')
      order_date = hash.key?('orderDate') ? hash['orderDate'] : SKIP
      shipping_location = ShippingLocation1.from_hash(hash['shippingLocation']) if
        hash['shippingLocation']
      status = hash.key?('status') ? hash['status'] : SKIP
      tracking_url = hash.key?('trackingUrl') ? hash['trackingUrl'] : SKIP

      # Create object from extracted values.
      TerminalOrder.new(billing_entity: billing_entity,
                        customer_order_reference: customer_order_reference,
                        id: id,
                        items: items,
                        order_date: order_date,
                        shipping_location: shipping_location,
                        status: status,
                        tracking_url: tracking_url)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_entity: #{@billing_entity}, customer_order_reference:"\
      " #{@customer_order_reference}, id: #{@id}, items: #{@items}, order_date: #{@order_date},"\
      " shipping_location: #{@shipping_location}, status: #{@status}, tracking_url:"\
      " #{@tracking_url}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_entity: #{@billing_entity.inspect}, customer_order_reference:"\
      " #{@customer_order_reference.inspect}, id: #{@id.inspect}, items: #{@items.inspect},"\
      " order_date: #{@order_date.inspect}, shipping_location: #{@shipping_location.inspect},"\
      " status: #{@status.inspect}, tracking_url: #{@tracking_url.inspect}>"
    end
  end
end
