# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # ThreeDSecureData Model.
  class ThreeDSecureData < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # In 3D Secure 2, this is the `transStatus` from the challenge result. If
    # the transaction was frictionless, omit this parameter.
    # @return [AuthenticationResponse]
    attr_accessor :authentication_response

    # The cardholder authentication value (base64 encoded, 20 bytes in a decoded
    # form).
    # @return [String]
    attr_accessor :cavv

    # The CAVV algorithm used. Include this only for 3D Secure 1.
    # @return [String]
    attr_accessor :cavv_algorithm

    # Indicator informing the Access Control Server (ACS) and the Directory
    # Server (DS) that the authentication has been cancelled. For possible
    # values, refer to [3D Secure API
    # reference](https://docs.adyen.com/online-payments/3d-secure/api-reference#
    # mpidata).
    # @return [ChallengeCancel]
    attr_accessor :challenge_cancel

    # In 3D Secure 2, this is the `transStatus` from the `ARes`.
    # @return [DirectoryResponse]
    attr_accessor :directory_response

    # Supported for 3D Secure 2. The unique transaction identifier assigned by
    # the Directory Server (DS) to identify a single transaction.
    # @return [String]
    attr_accessor :ds_trans_id

    # The electronic commerce indicator.
    # @return [String]
    attr_accessor :eci

    # Risk score calculated by Directory Server (DS). Required for Cartes
    # Bancaires integrations.
    # @return [String]
    attr_accessor :risk_score

    # The version of the 3D Secure protocol.
    # @return [String]
    attr_accessor :three_ds_version

    # Network token authentication verification value (TAVV). The network token
    # cryptogram.
    # @return [String]
    attr_accessor :token_authentication_verification_value

    # Provides information on why the `transStatus` field has the specified
    # value. For possible values, refer to [our
    # docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possi
    # ble-transstatusreason-values).
    # @return [String]
    attr_accessor :trans_status_reason

    # Supported for 3D Secure 1. The transaction identifier (Base64-encoded, 20
    # bytes in a decoded form).
    # @return [String]
    attr_accessor :xid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['authentication_response'] = 'authenticationResponse'
      @_hash['cavv'] = 'cavv'
      @_hash['cavv_algorithm'] = 'cavvAlgorithm'
      @_hash['challenge_cancel'] = 'challengeCancel'
      @_hash['directory_response'] = 'directoryResponse'
      @_hash['ds_trans_id'] = 'dsTransID'
      @_hash['eci'] = 'eci'
      @_hash['risk_score'] = 'riskScore'
      @_hash['three_ds_version'] = 'threeDSVersion'
      @_hash['token_authentication_verification_value'] =
        'tokenAuthenticationVerificationValue'
      @_hash['trans_status_reason'] = 'transStatusReason'
      @_hash['xid'] = 'xid'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        authentication_response
        cavv
        cavv_algorithm
        challenge_cancel
        directory_response
        ds_trans_id
        eci
        risk_score
        three_ds_version
        token_authentication_verification_value
        trans_status_reason
        xid
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(authentication_response: SKIP, cavv: SKIP,
                   cavv_algorithm: SKIP, challenge_cancel: SKIP,
                   directory_response: SKIP, ds_trans_id: SKIP, eci: SKIP,
                   risk_score: SKIP, three_ds_version: SKIP,
                   token_authentication_verification_value: SKIP,
                   trans_status_reason: SKIP, xid: SKIP)
      @authentication_response = authentication_response unless authentication_response == SKIP
      @cavv = cavv unless cavv == SKIP
      @cavv_algorithm = cavv_algorithm unless cavv_algorithm == SKIP
      @challenge_cancel = challenge_cancel unless challenge_cancel == SKIP
      @directory_response = directory_response unless directory_response == SKIP
      @ds_trans_id = ds_trans_id unless ds_trans_id == SKIP
      @eci = eci unless eci == SKIP
      @risk_score = risk_score unless risk_score == SKIP
      @three_ds_version = three_ds_version unless three_ds_version == SKIP
      unless token_authentication_verification_value == SKIP
        @token_authentication_verification_value =
          token_authentication_verification_value
      end
      @trans_status_reason = trans_status_reason unless trans_status_reason == SKIP
      @xid = xid unless xid == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      authentication_response =
        hash.key?('authenticationResponse') ? hash['authenticationResponse'] : SKIP
      cavv = hash.key?('cavv') ? hash['cavv'] : SKIP
      cavv_algorithm = hash.key?('cavvAlgorithm') ? hash['cavvAlgorithm'] : SKIP
      challenge_cancel =
        hash.key?('challengeCancel') ? hash['challengeCancel'] : SKIP
      directory_response =
        hash.key?('directoryResponse') ? hash['directoryResponse'] : SKIP
      ds_trans_id = hash.key?('dsTransID') ? hash['dsTransID'] : SKIP
      eci = hash.key?('eci') ? hash['eci'] : SKIP
      risk_score = hash.key?('riskScore') ? hash['riskScore'] : SKIP
      three_ds_version =
        hash.key?('threeDSVersion') ? hash['threeDSVersion'] : SKIP
      token_authentication_verification_value =
        hash.key?('tokenAuthenticationVerificationValue') ? hash['tokenAuthenticationVerificationValue'] : SKIP
      trans_status_reason =
        hash.key?('transStatusReason') ? hash['transStatusReason'] : SKIP
      xid = hash.key?('xid') ? hash['xid'] : SKIP

      # Create object from extracted values.
      ThreeDSecureData.new(authentication_response: authentication_response,
                           cavv: cavv,
                           cavv_algorithm: cavv_algorithm,
                           challenge_cancel: challenge_cancel,
                           directory_response: directory_response,
                           ds_trans_id: ds_trans_id,
                           eci: eci,
                           risk_score: risk_score,
                           three_ds_version: three_ds_version,
                           token_authentication_verification_value: token_authentication_verification_value,
                           trans_status_reason: trans_status_reason,
                           xid: xid)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} authentication_response: #{@authentication_response}, cavv: #{@cavv},"\
      " cavv_algorithm: #{@cavv_algorithm}, challenge_cancel: #{@challenge_cancel},"\
      " directory_response: #{@directory_response}, ds_trans_id: #{@ds_trans_id}, eci: #{@eci},"\
      " risk_score: #{@risk_score}, three_ds_version: #{@three_ds_version},"\
      " token_authentication_verification_value: #{@token_authentication_verification_value},"\
      " trans_status_reason: #{@trans_status_reason}, xid: #{@xid}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} authentication_response: #{@authentication_response.inspect}, cavv:"\
      " #{@cavv.inspect}, cavv_algorithm: #{@cavv_algorithm.inspect}, challenge_cancel:"\
      " #{@challenge_cancel.inspect}, directory_response: #{@directory_response.inspect},"\
      " ds_trans_id: #{@ds_trans_id.inspect}, eci: #{@eci.inspect}, risk_score:"\
      " #{@risk_score.inspect}, three_ds_version: #{@three_ds_version.inspect},"\
      ' token_authentication_verification_value:'\
      " #{@token_authentication_verification_value.inspect}, trans_status_reason:"\
      " #{@trans_status_reason.inspect}, xid: #{@xid.inspect}>"
    end
  end
end
