# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The version of 3D Secure to use. Possible values: * **2.1.0** * **2.2.0**
  class ThreeDsVersion
    THREE_DS_VERSION = [
      # TODO: Write general description for ENUM_210
      ENUM_210 = '2.1.0'.freeze,

      # TODO: Write general description for ENUM_220
      ENUM_220 = '2.2.0'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      THREE_DS_VERSION.include?(value)
    end

    def self.from_value(value, default_value = ENUM_210)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enum_210' then ENUM_210
      when 'enum_220' then ENUM_220
      else
        default_value
      end
    end
  end
end
