# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Ticket Model.
  class Ticket < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The address of the organization that issued the ticket.
    # * minLength: 0 characters
    # * maxLength: 16 characters
    # @return [String]
    attr_accessor :issue_address

    # The date that the ticket was issued to the passenger.
    # * minLength: 10 characters
    # * maxLength: 10 characters
    # * Format [ISO 8601](https://www.w3.org/TR/NOTE-datetime): yyyy-MM-dd
    # @return [Date]
    attr_accessor :issue_date

    # The ticket's unique identifier.
    # * minLength: 1 character
    # * maxLength: 15 characters
    # * Must not start with a space or be all spaces.
    # * Must not be all zeros.
    # @return [String]
    attr_accessor :number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['issue_address'] = 'issueAddress'
      @_hash['issue_date'] = 'issueDate'
      @_hash['number'] = 'number'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        issue_address
        issue_date
        number
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(issue_address: SKIP, issue_date: SKIP, number: SKIP)
      @issue_address = issue_address unless issue_address == SKIP
      @issue_date = issue_date unless issue_date == SKIP
      @number = number unless number == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      issue_address = hash.key?('issueAddress') ? hash['issueAddress'] : SKIP
      issue_date = hash.key?('issueDate') ? hash['issueDate'] : SKIP
      number = hash.key?('number') ? hash['number'] : SKIP

      # Create object from extracted values.
      Ticket.new(issue_address: issue_address,
                 issue_date: issue_date,
                 number: number)
    end

    # Validates an instance of the object from a given value.
    # @param [Ticket | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} issue_address: #{@issue_address}, issue_date: #{@issue_date}, number:"\
      " #{@number}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} issue_address: #{@issue_address.inspect}, issue_date:"\
      " #{@issue_date.inspect}, number: #{@number.inspect}>"
    end
  end
end
