# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Identifies the type of transaction being authenticated. Length: 2
  # characters. Allowed values: * **01** — Goods/Service Purchase * **03** —
  # Check Acceptance * **10** — Account Funding * **11** — Quasi-Cash
  # Transaction * **28** — Prepaid Activation and Load
  class TransType
    TRANS_TYPE = [
      # TODO: Write general description for ENUM_01
      ENUM_01 = '01'.freeze,

      # TODO: Write general description for ENUM_03
      ENUM_03 = '03'.freeze,

      # TODO: Write general description for ENUM_10
      ENUM_10 = '10'.freeze,

      # TODO: Write general description for ENUM_11
      ENUM_11 = '11'.freeze,

      # TODO: Write general description for ENUM_28
      ENUM_28 = '28'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TRANS_TYPE.include?(value)
    end

    def self.from_value(value, default_value = ENUM_01)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enum_01' then ENUM_01
      when 'enum_03' then ENUM_03
      when 'enum_10' then ENUM_10
      when 'enum_11' then ENUM_11
      when 'enum_28' then ENUM_28
      else
        default_value
      end
    end
  end
end
