# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # **molpay**
  class Type33
    TYPE33 = [
      # TODO: Write general description for MOLPAY_EBANKING_FPX_MY
      MOLPAY_EBANKING_FPX_MY = 'molpay_ebanking_fpx_MY'.freeze,

      # TODO: Write general description for MOLPAY_EBANKING_TH
      MOLPAY_EBANKING_TH = 'molpay_ebanking_TH'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE33.include?(value)
    end

    def self.from_value(value, default_value = MOLPAY_EBANKING_FPX_MY)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'molpay_ebanking_fpx_my' then MOLPAY_EBANKING_FPX_MY
      when 'molpay_ebanking_th' then MOLPAY_EBANKING_TH
      else
        default_value
      end
    end
  end
end
