# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # **zip**
  class Type52
    TYPE52 = [
      # TODO: Write general description for ZIP
      ZIP = 'zip'.freeze,

      # TODO: Write general description for ZIP_POS
      ZIP_POS = 'zip_pos'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE52.include?(value)
    end

    def self.from_value(value, default_value = ZIP)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'zip' then ZIP
      when 'zip_pos' then ZIP_POS
      else
        default_value
      end
    end
  end
end
