# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # **billdesk**
  class Type10
    TYPE10 = [
      # TODO: Write general description for BILLDESK_ONLINE
      BILLDESK_ONLINE = 'billdesk_online'.freeze,

      # TODO: Write general description for BILLDESK_WALLET
      BILLDESK_WALLET = 'billdesk_wallet'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE10.include?(value)
    end

    def self.from_value(value, default_value = BILLDESK_ONLINE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'billdesk_online' then BILLDESK_ONLINE
      when 'billdesk_wallet' then BILLDESK_WALLET
      else
        default_value
      end
    end
  end
end
