# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # **econtextvoucher**
  class Type24
    TYPE24 = [
      # TODO: Write general description for ECONTEXT_SEVEN_ELEVEN
      ECONTEXT_SEVEN_ELEVEN = 'econtext_seven_eleven'.freeze,

      # TODO: Write general description for ECONTEXT_ONLINE
      ECONTEXT_ONLINE = 'econtext_online'.freeze,

      # TODO: Write general description for ECONTEXT
      ECONTEXT = 'econtext'.freeze,

      # TODO: Write general description for ECONTEXT_STORES
      ECONTEXT_STORES = 'econtext_stores'.freeze,

      # TODO: Write general description for ECONTEXT_ATM
      ECONTEXT_ATM = 'econtext_atm'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE24.include?(value)
    end

    def self.from_value(value, default_value = ECONTEXT_SEVEN_ELEVEN)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'econtext_seven_eleven' then ECONTEXT_SEVEN_ELEVEN
      when 'econtext_online' then ECONTEXT_ONLINE
      when 'econtext' then ECONTEXT
      when 'econtext_stores' then ECONTEXT_STORES
      when 'econtext_atm' then ECONTEXT_ATM
      else
        default_value
      end
    end
  end
end
