# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # **applepay**
  class Type6
    TYPE6 = [
      # TODO: Write general description for APPLEPAY
      APPLEPAY = 'applepay'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE6.include?(value)
    end

    def self.from_value(value, default_value = APPLEPAY)
      return default_value if value.nil?

      default_value
    end
  end
end
