# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # **payto**
  class Type36
    TYPE36 = [
      # TODO: Write general description for PAYTO
      PAYTO = 'payto'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE36.include?(value)
    end

    def self.from_value(value, default_value = PAYTO)
      return default_value if value.nil?

      default_value
    end
  end
end
