# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # **genericissuer**
  class Type26
    TYPE26 = [
      # TODO: Write general description for ONLINEBANKING_PL
      ONLINEBANKING_PL = 'onlineBanking_PL'.freeze,

      # TODO: Write general description for EPS
      EPS = 'eps'.freeze,

      # TODO: Write general description for ONLINEBANKING_SK
      ONLINEBANKING_SK = 'onlineBanking_SK'.freeze,

      # TODO: Write general description for ONLINEBANKING_CZ
      ONLINEBANKING_CZ = 'onlineBanking_CZ'.freeze,

      # TODO: Write general description for ONLINEBANKING_IN
      ONLINEBANKING_IN = 'onlinebanking_IN'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE26.include?(value)
    end

    def self.from_value(value, default_value = ONLINEBANKING_PL)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'onlinebanking_pl' then ONLINEBANKING_PL
      when 'eps' then EPS
      when 'onlinebanking_sk' then ONLINEBANKING_SK
      when 'onlinebanking_cz' then ONLINEBANKING_CZ
      when 'onlinebanking_in' then ONLINEBANKING_IN
      else
        default_value
      end
    end
  end
end
