# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Default payment method details. Common for scheme payment methods, and for
  # simple payment method details.
  class Type12
    TYPE12 = [
      # TODO: Write general description for BCMC
      BCMC = 'bcmc'.freeze,

      # TODO: Write general description for SCHEME
      SCHEME = 'scheme'.freeze,

      # TODO: Write general description for NETWORKTOKEN
      NETWORKTOKEN = 'networkToken'.freeze,

      # TODO: Write general description for GIFTCARD
      GIFTCARD = 'giftcard'.freeze,

      # TODO: Write general description for CARD
      CARD = 'card'.freeze,

      # TODO: Write general description for CLICKTOPAY
      CLICKTOPAY = 'clicktopay'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE12.include?(value)
    end

    def self.from_value(value, default_value = BCMC)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'bcmc' then BCMC
      when 'scheme' then SCHEME
      when 'networktoken' then NETWORKTOKEN
      when 'giftcard' then GIFTCARD
      when 'card' then CARD
      when 'clicktopay' then CLICKTOPAY
      else
        default_value
      end
    end
  end
end
