# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The payment method type.
  class Type38
    TYPE38 = [
      # TODO: Write general description for ALIPAY
      ALIPAY = 'alipay'.freeze,

      # TODO: Write general description for MULTIBANCO
      MULTIBANCO = 'multibanco'.freeze,

      # TODO: Write general description for BANKTRANSFER
      BANKTRANSFER = 'bankTransfer'.freeze,

      # TODO: Write general description for BANKTRANSFER_IBAN
      BANKTRANSFER_IBAN = 'bankTransfer_IBAN'.freeze,

      # TODO: Write general description for PAYBRIGHT
      PAYBRIGHT = 'paybright'.freeze,

      # TODO: Write general description for PAYNOW
      PAYNOW = 'paynow'.freeze,

      # TODO: Write general description for AFFIRM_POS
      AFFIRM_POS = 'affirm_pos'.freeze,

      # TODO: Write general description for IRIS
      IRIS = 'iris'.freeze,

      # TODO: Write general description for TRUSTLY
      TRUSTLY = 'trustly'.freeze,

      # TODO: Write general description for TRUSTLYVECTOR
      TRUSTLYVECTOR = 'trustlyvector'.freeze,

      # TODO: Write general description for ONEY
      ONEY = 'oney'.freeze,

      # TODO: Write general description for FACILYPAY
      FACILYPAY = 'facilypay'.freeze,

      # TODO: Write general description for FACILYPAY_3X
      FACILYPAY_3X = 'facilypay_3x'.freeze,

      # TODO: Write general description for FACILYPAY_4X
      FACILYPAY_4X = 'facilypay_4x'.freeze,

      # TODO: Write general description for FACILYPAY_6X
      FACILYPAY_6X = 'facilypay_6x'.freeze,

      # TODO: Write general description for FACILYPAY_10X
      FACILYPAY_10X = 'facilypay_10x'.freeze,

      # TODO: Write general description for FACILYPAY_12X
      FACILYPAY_12X = 'facilypay_12x'.freeze,

      # TODO: Write general description for UNIONPAY
      UNIONPAY = 'unionpay'.freeze,

      # TODO: Write general description for KCP_BANKTRANSFER
      KCP_BANKTRANSFER = 'kcp_banktransfer'.freeze,

      # TODO: Write general description for KCP_PAYCO
      KCP_PAYCO = 'kcp_payco'.freeze,

      # TODO: Write general description for KCP_CREDITCARD
      KCP_CREDITCARD = 'kcp_creditcard'.freeze,

      # TODO: Write general description for WECHATPAYSDK
      WECHATPAYSDK = 'wechatpaySDK'.freeze,

      # TODO: Write general description for WECHATPAYQR
      WECHATPAYQR = 'wechatpayQR'.freeze,

      # TODO: Write general description for WECHATPAYWEB
      WECHATPAYWEB = 'wechatpayWeb'.freeze,

      # TODO: Write general description for MOLPAY_BOOST
      MOLPAY_BOOST = 'molpay_boost'.freeze,

      # TODO: Write general description for WALLET_IN
      WALLET_IN = 'wallet_IN'.freeze,

      # TODO: Write general description for PAYU_IN_CASHCARD
      PAYU_IN_CASHCARD = 'payu_IN_cashcard'.freeze,

      # TODO: Write general description for PAYU_IN_NB
      PAYU_IN_NB = 'payu_IN_nb'.freeze,

      # TODO: Write general description for PAYTM
      PAYTM = 'paytm'.freeze,

      # TODO: Write general description for MOLPAY_EBANKING_VN
      MOLPAY_EBANKING_VN = 'molpay_ebanking_VN'.freeze,

      # TODO: Write general description for MOLPAY_EBANKING_MY
      MOLPAY_EBANKING_MY = 'molpay_ebanking_MY'.freeze,

      # TODO: Write general description for MOLPAY_EBANKING_DIRECT_MY
      MOLPAY_EBANKING_DIRECT_MY = 'molpay_ebanking_direct_MY'.freeze,

      # TODO: Write general description for SWISH
      SWISH = 'swish'.freeze,

      # TODO: Write general description for BIZUM
      BIZUM = 'bizum'.freeze,

      # TODO: Write general description for WALLEY
      WALLEY = 'walley'.freeze,

      # TODO: Write general description for WALLEY_B2B
      WALLEY_B2B = 'walley_b2b'.freeze,

      # TODO: Write general description for ALMA
      ALMA = 'alma'.freeze,

      # TODO: Write general description for PAYPO
      PAYPO = 'paypo'.freeze,

      # TODO: Write general description for SCALAPAY
      SCALAPAY = 'scalapay'.freeze,

      # TODO: Write general description for SCALAPAY_3X
      SCALAPAY_3X = 'scalapay_3x'.freeze,

      # TODO: Write general description for SCALAPAY_4X
      SCALAPAY_4X = 'scalapay_4x'.freeze,

      # TODO: Write general description for MOLPAY_FPX
      MOLPAY_FPX = 'molpay_fpx'.freeze,

      # TODO: Write general description for PAYME
      PAYME = 'payme'.freeze,

      # TODO: Write general description for PAYME_POS
      PAYME_POS = 'payme_pos'.freeze,

      # TODO: Write general description for KONBINI
      KONBINI = 'konbini'.freeze,

      # TODO: Write general description for DIRECTEBANKING
      DIRECTEBANKING = 'directEbanking'.freeze,

      # TODO: Write general description for BOLETOBANCARIO
      BOLETOBANCARIO = 'boletobancario'.freeze,

      # TODO: Write general description for CASHTICKET
      CASHTICKET = 'cashticket'.freeze,

      # TODO: Write general description for IKANO
      IKANO = 'ikano'.freeze,

      # TODO: Write general description for KARENMILLEN
      KARENMILLEN = 'karenmillen'.freeze,

      # TODO: Write general description for OASIS
      OASIS = 'oasis'.freeze,

      # TODO: Write general description for WAREHOUSE
      WAREHOUSE = 'warehouse'.freeze,

      # TODO: Write general description for PRIMEIROPAY_BOLETO
      PRIMEIROPAY_BOLETO = 'primeiropay_boleto'.freeze,

      # TODO: Write general description for MADA
      MADA = 'mada'.freeze,

      # TODO: Write general description for BENEFIT
      BENEFIT = 'benefit'.freeze,

      # TODO: Write general description for KNET
      KNET = 'knet'.freeze,

      # TODO: Write general description for OMANNET
      OMANNET = 'omannet'.freeze,

      # TODO: Write general description for GOPAY_WALLET
      GOPAY_WALLET = 'gopay_wallet'.freeze,

      # TODO: Write general description for KCP_NAVERPAY
      KCP_NAVERPAY = 'kcp_naverpay'.freeze,

      # TODO: Write general description for FAWRY
      FAWRY = 'fawry'.freeze,

      # TODO: Write general description for ATOME
      ATOME = 'atome'.freeze,

      # TODO: Write general description for NAPS
      NAPS = 'naps'.freeze,

      # TODO: Write general description for NORDEA
      NORDEA = 'nordea'.freeze,

      # TODO: Write general description for BOLETOBANCARIO_BRADESCO
      BOLETOBANCARIO_BRADESCO = 'boletobancario_bradesco'.freeze,

      # TODO: Write general description for BOLETOBANCARIO_ITAU
      BOLETOBANCARIO_ITAU = 'boletobancario_itau'.freeze,

      # TODO: Write general description for BOLETOBANCARIO_SANTANDER
      BOLETOBANCARIO_SANTANDER = 'boletobancario_santander'.freeze,

      # TODO: Write general description for BOLETOBANCARIO_BANCODOBRASIL
      BOLETOBANCARIO_BANCODOBRASIL = 'boletobancario_bancodobrasil'.freeze,

      # TODO: Write general description for BOLETOBANCARIO_HSBC
      BOLETOBANCARIO_HSBC = 'boletobancario_hsbc'.freeze,

      # TODO: Write general description for MOLPAY_MAYBANK2U
      MOLPAY_MAYBANK2U = 'molpay_maybank2u'.freeze,

      # TODO: Write general description for MOLPAY_CIMB
      MOLPAY_CIMB = 'molpay_cimb'.freeze,

      # TODO: Write general description for MOLPAY_RHB
      MOLPAY_RHB = 'molpay_rhb'.freeze,

      # TODO: Write general description for MOLPAY_AMB
      MOLPAY_AMB = 'molpay_amb'.freeze,

      # TODO: Write general description for MOLPAY_HLB
      MOLPAY_HLB = 'molpay_hlb'.freeze,

      # TODO: Write general description for MOLPAY_AFFIN_EPG
      MOLPAY_AFFIN_EPG = 'molpay_affin_epg'.freeze,

      # TODO: Write general description for MOLPAY_BANKISLAM
      MOLPAY_BANKISLAM = 'molpay_bankislam'.freeze,

      # TODO: Write general description for MOLPAY_PUBLICBANK
      MOLPAY_PUBLICBANK = 'molpay_publicbank'.freeze,

      # TODO: Write general description for FPX_AGROBANK
      FPX_AGROBANK = 'fpx_agrobank'.freeze,

      # TODO: Write general description for TOUCHNGO
      TOUCHNGO = 'touchngo'.freeze,

      # TODO: Write general description for MAYBANK2U_MAE
      MAYBANK2U_MAE = 'maybank2u_mae'.freeze,

      # TODO: Write general description for DUITNOW
      DUITNOW = 'duitnow'.freeze,

      # TODO: Write general description for PROMPTPAY
      PROMPTPAY = 'promptpay'.freeze,

      # TODO: Write general description for TWINT_POS
      TWINT_POS = 'twint_pos'.freeze,

      # TODO: Write general description for ALIPAY_HK
      ALIPAY_HK = 'alipay_hk'.freeze,

      # TODO: Write general description for ALIPAY_HK_WEB
      ALIPAY_HK_WEB = 'alipay_hk_web'.freeze,

      # TODO: Write general description for ALIPAY_HK_WAP
      ALIPAY_HK_WAP = 'alipay_hk_wap'.freeze,

      # TODO: Write general description for ALIPAY_WAP
      ALIPAY_WAP = 'alipay_wap'.freeze,

      # TODO: Write general description for BALANCEPLATFORM
      BALANCEPLATFORM = 'balanceplatform'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE38.include?(value)
    end

    def self.from_value(value, default_value = ALIPAY)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'alipay' then ALIPAY
      when 'multibanco' then MULTIBANCO
      when 'banktransfer' then BANKTRANSFER
      when 'banktransfer_iban' then BANKTRANSFER_IBAN
      when 'paybright' then PAYBRIGHT
      when 'paynow' then PAYNOW
      when 'affirm_pos' then AFFIRM_POS
      when 'iris' then IRIS
      when 'trustly' then TRUSTLY
      when 'trustlyvector' then TRUSTLYVECTOR
      when 'oney' then ONEY
      when 'facilypay' then FACILYPAY
      when 'facilypay_3x' then FACILYPAY_3X
      when 'facilypay_4x' then FACILYPAY_4X
      when 'facilypay_6x' then FACILYPAY_6X
      when 'facilypay_10x' then FACILYPAY_10X
      when 'facilypay_12x' then FACILYPAY_12X
      when 'unionpay' then UNIONPAY
      when 'kcp_banktransfer' then KCP_BANKTRANSFER
      when 'kcp_payco' then KCP_PAYCO
      when 'kcp_creditcard' then KCP_CREDITCARD
      when 'wechatpaysdk' then WECHATPAYSDK
      when 'wechatpayqr' then WECHATPAYQR
      when 'wechatpayweb' then WECHATPAYWEB
      when 'molpay_boost' then MOLPAY_BOOST
      when 'wallet_in' then WALLET_IN
      when 'payu_in_cashcard' then PAYU_IN_CASHCARD
      when 'payu_in_nb' then PAYU_IN_NB
      when 'paytm' then PAYTM
      when 'molpay_ebanking_vn' then MOLPAY_EBANKING_VN
      when 'molpay_ebanking_my' then MOLPAY_EBANKING_MY
      when 'molpay_ebanking_direct_my' then MOLPAY_EBANKING_DIRECT_MY
      when 'swish' then SWISH
      when 'bizum' then BIZUM
      when 'walley' then WALLEY
      when 'walley_b2b' then WALLEY_B2B
      when 'alma' then ALMA
      when 'paypo' then PAYPO
      when 'scalapay' then SCALAPAY
      when 'scalapay_3x' then SCALAPAY_3X
      when 'scalapay_4x' then SCALAPAY_4X
      when 'molpay_fpx' then MOLPAY_FPX
      when 'payme' then PAYME
      when 'payme_pos' then PAYME_POS
      when 'konbini' then KONBINI
      when 'directebanking' then DIRECTEBANKING
      when 'boletobancario' then BOLETOBANCARIO
      when 'cashticket' then CASHTICKET
      when 'ikano' then IKANO
      when 'karenmillen' then KARENMILLEN
      when 'oasis' then OASIS
      when 'warehouse' then WAREHOUSE
      when 'primeiropay_boleto' then PRIMEIROPAY_BOLETO
      when 'mada' then MADA
      when 'benefit' then BENEFIT
      when 'knet' then KNET
      when 'omannet' then OMANNET
      when 'gopay_wallet' then GOPAY_WALLET
      when 'kcp_naverpay' then KCP_NAVERPAY
      when 'fawry' then FAWRY
      when 'atome' then ATOME
      when 'naps' then NAPS
      when 'nordea' then NORDEA
      when 'boletobancario_bradesco' then BOLETOBANCARIO_BRADESCO
      when 'boletobancario_itau' then BOLETOBANCARIO_ITAU
      when 'boletobancario_santander' then BOLETOBANCARIO_SANTANDER
      when 'boletobancario_bancodobrasil' then BOLETOBANCARIO_BANCODOBRASIL
      when 'boletobancario_hsbc' then BOLETOBANCARIO_HSBC
      when 'molpay_maybank2u' then MOLPAY_MAYBANK2U
      when 'molpay_cimb' then MOLPAY_CIMB
      when 'molpay_rhb' then MOLPAY_RHB
      when 'molpay_amb' then MOLPAY_AMB
      when 'molpay_hlb' then MOLPAY_HLB
      when 'molpay_affin_epg' then MOLPAY_AFFIN_EPG
      when 'molpay_bankislam' then MOLPAY_BANKISLAM
      when 'molpay_publicbank' then MOLPAY_PUBLICBANK
      when 'fpx_agrobank' then FPX_AGROBANK
      when 'touchngo' then TOUCHNGO
      when 'maybank2u_mae' then MAYBANK2U_MAE
      when 'duitnow' then DUITNOW
      when 'promptpay' then PROMPTPAY
      when 'twint_pos' then TWINT_POS
      when 'alipay_hk' then ALIPAY_HK
      when 'alipay_hk_web' then ALIPAY_HK_WEB
      when 'alipay_hk_wap' then ALIPAY_HK_WAP
      when 'alipay_wap' then ALIPAY_WAP
      when 'balanceplatform' then BALANCEPLATFORM
      else
        default_value
      end
    end
  end
end
