# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The part of the payment you want to book to the specified `account`.
  # Possible values for the [Balance
  # Platform](https://docs.adyen.com/adyen-for-platforms-model): *
  # **BalanceAccount**: Books part of the payment (specified in `amount`) to the
  # specified `account`. * Transaction fees types that you can book to the
  # specified `account`:    * **AcquiringFees**: The aggregated amount of the
  # interchange and scheme fees.    * **PaymentFee**: The aggregated amount of
  # all transaction fees.    * **AdyenFees**: The aggregated amount of Adyen's
  # commission and markup fees.    * **AdyenCommission**: The transaction fees
  # due to Adyen under [blended
  # rates](https://www.adyen.com/knowledge-hub/interchange-fees-explained).    *
  # **AdyenMarkup**: The transaction fees due to Adyen under [Interchange ++
  # pricing](https://www.adyen.com/knowledge-hub/interchange-fees-explained).
  # * **Interchange**: The fees paid to the issuer for each payment made with
  # the card network.    * **SchemeFee**: The fees paid to the card scheme for
  # using their network.  * **Commission**: Your platform's commission on the
  # payment (specified in `amount`), booked to your liable balance account. *
  # **Remainder**: The amount left over after a currency conversion, booked to
  # the specified `account`. * **Surcharge**: The payment acceptance fee imposed
  # by the card scheme or debit network provider, paid by your user's customer.
  # * **TopUp**: Allows you and your users to top up balance accounts using
  # direct debit, card payments, or other payment methods. * **VAT**: The
  # value-added tax charged on the payment, booked to your platforms liable
  # balance account. * **Default**: In very specific use cases, allows you to
  # book the specified `amount` to the specified `account`. For more
  # information, contact Adyen support. Possible values for the [Classic
  # Platforms integration](https://docs.adyen.com/classic-platforms):
  # **Commission**, **Default**, **MarketPlace**, **PaymentFee**, **VAT**.
  class Type9
    TYPE9 = [
      # TODO: Write general description for ACQUIRINGFEES
      ACQUIRINGFEES = 'AcquiringFees'.freeze,

      # TODO: Write general description for ADYENCOMMISSION
      ADYENCOMMISSION = 'AdyenCommission'.freeze,

      # TODO: Write general description for ADYENFEES
      ADYENFEES = 'AdyenFees'.freeze,

      # TODO: Write general description for ADYENMARKUP
      ADYENMARKUP = 'AdyenMarkup'.freeze,

      # TODO: Write general description for BALANCEACCOUNT
      BALANCEACCOUNT = 'BalanceAccount'.freeze,

      # TODO: Write general description for COMMISSION
      COMMISSION = 'Commission'.freeze,

      # TODO: Write general description for DEFAULT
      DEFAULT = 'Default'.freeze,

      # TODO: Write general description for INTERCHANGE
      INTERCHANGE = 'Interchange'.freeze,

      # TODO: Write general description for MARKETPLACE
      MARKETPLACE = 'MarketPlace'.freeze,

      # TODO: Write general description for PAYMENTFEE
      PAYMENTFEE = 'PaymentFee'.freeze,

      # TODO: Write general description for REMAINDER
      REMAINDER = 'Remainder'.freeze,

      # TODO: Write general description for SCHEMEFEE
      SCHEMEFEE = 'SchemeFee'.freeze,

      # TODO: Write general description for SURCHARGE
      SURCHARGE = 'Surcharge'.freeze,

      # TODO: Write general description for TIP
      TIP = 'Tip'.freeze,

      # TODO: Write general description for TOPUP
      TOPUP = 'TopUp'.freeze,

      # TODO: Write general description for VAT
      VAT = 'VAT'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE9.include?(value)
    end

    def self.from_value(value, default_value = ACQUIRINGFEES)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'acquiringfees' then ACQUIRINGFEES
      when 'adyencommission' then ADYENCOMMISSION
      when 'adyenfees' then ADYENFEES
      when 'adyenmarkup' then ADYENMARKUP
      when 'balanceaccount' then BALANCEACCOUNT
      when 'commission' then COMMISSION
      when 'default' then DEFAULT
      when 'interchange' then INTERCHANGE
      when 'marketplace' then MARKETPLACE
      when 'paymentfee' then PAYMENTFEE
      when 'remainder' then REMAINDER
      when 'schemefee' then SCHEMEFEE
      when 'surcharge' then SURCHARGE
      when 'tip' then TIP
      when 'topup' then TOPUP
      when 'vat' then VAT
      else
        default_value
      end
    end
  end
end
