# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # UpdateStoreRequest Model.
  class UpdateStoreRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The address of the store. It is not possible to update the country of the
    # store.
    # @return [UpdatableAddress1]
    attr_accessor :address

    # The unique identifiers of the [business
    # lines](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/busin
    # essLines__resParam_id) that the store is associated with.
    # @return [Array[String]]
    attr_accessor :business_line_ids

    # The description of the store.
    # @return [String]
    attr_accessor :description

    # The unique identifier of the store, used by certain payment methods and
    # tax authorities.
    # Required for CNPJ in Brazil, in the format 00.000.000/0000-00 separated by
    # dots, slashes, hyphens, or without separators.
    # Optional for SIRET in France, up to 14 digits.
    # Optional for Zip in Australia, up to 50 digits.
    # @return [String]
    attr_accessor :external_reference_id

    # The phone number of the store, including '+' and country code in the
    # [E.164](https://en.wikipedia.org/wiki/E.164) format. If passed in a
    # different format, we convert and validate the phone number against E.164.
    # @return [String]
    attr_accessor :phone_number

    # Rules for Adyen for Platforms merchants to split the transaction amount
    # and fees.
    # @return [StoreSplitConfiguration1]
    attr_accessor :split_configuration

    # The status of the store. Possible values are:
    # - **active**: This value is assigned automatically when a store is
    # created. 
    # - **inactive**: The maximum [transaction limits and number of
    # Store-and-Forward
    # transactions](https://docs.adyen.com/point-of-sale/determine-account-struc
    # ture/configure-features#payment-features) for the store are set to 0. This
    # blocks new transactions, but captures are still possible.
    # - **closed**: The terminals of the store are reassigned to the merchant
    # inventory, so they can't process payments.
    # You can change the status from **active** to **inactive**, and from
    # **inactive** to **active** or **closed**. 
    # Once **closed**, a store can't be reopened.
    # @return [Status41]
    attr_accessor :status

    # The sub-merchant data relevant for registered payment facilitators
    # transacting on standalone terminals.
    # @return [SubMerchantData1]
    attr_accessor :sub_merchant_data

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['address'] = 'address'
      @_hash['business_line_ids'] = 'businessLineIds'
      @_hash['description'] = 'description'
      @_hash['external_reference_id'] = 'externalReferenceId'
      @_hash['phone_number'] = 'phoneNumber'
      @_hash['split_configuration'] = 'splitConfiguration'
      @_hash['status'] = 'status'
      @_hash['sub_merchant_data'] = 'subMerchantData'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        address
        business_line_ids
        description
        external_reference_id
        phone_number
        split_configuration
        status
        sub_merchant_data
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(address: SKIP, business_line_ids: SKIP, description: SKIP,
                   external_reference_id: SKIP, phone_number: SKIP,
                   split_configuration: SKIP, status: SKIP,
                   sub_merchant_data: SKIP)
      @address = address unless address == SKIP
      @business_line_ids = business_line_ids unless business_line_ids == SKIP
      @description = description unless description == SKIP
      @external_reference_id = external_reference_id unless external_reference_id == SKIP
      @phone_number = phone_number unless phone_number == SKIP
      @split_configuration = split_configuration unless split_configuration == SKIP
      @status = status unless status == SKIP
      @sub_merchant_data = sub_merchant_data unless sub_merchant_data == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      address = UpdatableAddress1.from_hash(hash['address']) if hash['address']
      business_line_ids =
        hash.key?('businessLineIds') ? hash['businessLineIds'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      external_reference_id =
        hash.key?('externalReferenceId') ? hash['externalReferenceId'] : SKIP
      phone_number = hash.key?('phoneNumber') ? hash['phoneNumber'] : SKIP
      split_configuration = StoreSplitConfiguration1.from_hash(hash['splitConfiguration']) if
        hash['splitConfiguration']
      status = hash.key?('status') ? hash['status'] : SKIP
      sub_merchant_data = SubMerchantData1.from_hash(hash['subMerchantData']) if
        hash['subMerchantData']

      # Create object from extracted values.
      UpdateStoreRequest.new(address: address,
                             business_line_ids: business_line_ids,
                             description: description,
                             external_reference_id: external_reference_id,
                             phone_number: phone_number,
                             split_configuration: split_configuration,
                             status: status,
                             sub_merchant_data: sub_merchant_data)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} address: #{@address}, business_line_ids: #{@business_line_ids},"\
      " description: #{@description}, external_reference_id: #{@external_reference_id},"\
      " phone_number: #{@phone_number}, split_configuration: #{@split_configuration}, status:"\
      " #{@status}, sub_merchant_data: #{@sub_merchant_data}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} address: #{@address.inspect}, business_line_ids:"\
      " #{@business_line_ids.inspect}, description: #{@description.inspect},"\
      " external_reference_id: #{@external_reference_id.inspect}, phone_number:"\
      " #{@phone_number.inspect}, split_configuration: #{@split_configuration.inspect}, status:"\
      " #{@status.inspect}, sub_merchant_data: #{@sub_merchant_data.inspect}>"
    end
  end
end
