# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # UpdateCompanyUserRequest Model.
  class UpdateCompanyUserRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The list of [account
    # groups](https://docs.adyen.com/account/account-structure#account-groups)
    # associated with this user.
    # @return [Array[String]]
    attr_accessor :account_groups

    # Indicates whether this user is active.
    # @return [TrueClass | FalseClass]
    attr_accessor :active

    # The list of [merchant
    # accounts](https://docs.adyen.com/account/account-structure#merchant-accoun
    # ts) to associate the user with.
    # @return [Array[String]]
    attr_accessor :associated_merchant_accounts

    # The email address of the user.
    # @return [String]
    attr_accessor :email

    # The requested login method for the user. To use SSO, you must already have
    # SSO configured with Adyen before creating the user.
    # Possible values: **Username & account**, **Email**, or **SSO**
    # @return [String]
    attr_accessor :login_method

    # The user's full name.
    # @return [Name22]
    attr_accessor :name

    # The list of [roles](https://docs.adyen.com/account/user-roles) for this
    # user.
    # @return [Array[String]]
    attr_accessor :roles

    # The [tz database
    # name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the
    # time zone of the user. For example, **Europe/Amsterdam**.
    # @return [String]
    attr_accessor :time_zone_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_groups'] = 'accountGroups'
      @_hash['active'] = 'active'
      @_hash['associated_merchant_accounts'] = 'associatedMerchantAccounts'
      @_hash['email'] = 'email'
      @_hash['login_method'] = 'loginMethod'
      @_hash['name'] = 'name'
      @_hash['roles'] = 'roles'
      @_hash['time_zone_code'] = 'timeZoneCode'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_groups
        active
        associated_merchant_accounts
        email
        login_method
        name
        roles
        time_zone_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_groups: SKIP, active: SKIP,
                   associated_merchant_accounts: SKIP, email: SKIP,
                   login_method: SKIP, name: SKIP, roles: SKIP,
                   time_zone_code: SKIP)
      @account_groups = account_groups unless account_groups == SKIP
      @active = active unless active == SKIP
      unless associated_merchant_accounts == SKIP
        @associated_merchant_accounts =
          associated_merchant_accounts
      end
      @email = email unless email == SKIP
      @login_method = login_method unless login_method == SKIP
      @name = name unless name == SKIP
      @roles = roles unless roles == SKIP
      @time_zone_code = time_zone_code unless time_zone_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_groups = hash.key?('accountGroups') ? hash['accountGroups'] : SKIP
      active = hash.key?('active') ? hash['active'] : SKIP
      associated_merchant_accounts =
        hash.key?('associatedMerchantAccounts') ? hash['associatedMerchantAccounts'] : SKIP
      email = hash.key?('email') ? hash['email'] : SKIP
      login_method = hash.key?('loginMethod') ? hash['loginMethod'] : SKIP
      name = Name22.from_hash(hash['name']) if hash['name']
      roles = hash.key?('roles') ? hash['roles'] : SKIP
      time_zone_code = hash.key?('timeZoneCode') ? hash['timeZoneCode'] : SKIP

      # Create object from extracted values.
      UpdateCompanyUserRequest.new(account_groups: account_groups,
                                   active: active,
                                   associated_merchant_accounts: associated_merchant_accounts,
                                   email: email,
                                   login_method: login_method,
                                   name: name,
                                   roles: roles,
                                   time_zone_code: time_zone_code)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_groups: #{@account_groups}, active: #{@active},"\
      " associated_merchant_accounts: #{@associated_merchant_accounts}, email: #{@email},"\
      " login_method: #{@login_method}, name: #{@name}, roles: #{@roles}, time_zone_code:"\
      " #{@time_zone_code}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_groups: #{@account_groups.inspect}, active: #{@active.inspect},"\
      " associated_merchant_accounts: #{@associated_merchant_accounts.inspect}, email:"\
      " #{@email.inspect}, login_method: #{@login_method.inspect}, name: #{@name.inspect}, roles:"\
      " #{@roles.inspect}, time_zone_code: #{@time_zone_code.inspect}>"
    end
  end
end
