# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # User Model.
  class User < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # References to resources connected with this user.
    # @return [Links1]
    attr_accessor :links

    # The list of [account
    # groups](https://docs.adyen.com/account/account-structure#account-groups)
    # associated with this user.
    # @return [Array[String]]
    attr_accessor :account_groups

    # Indicates whether this user is active.
    # @return [TrueClass | FalseClass]
    attr_accessor :active

    # Set of apps available to this user
    # @return [Array[String]]
    attr_accessor :apps

    # The email address of the user.
    # @return [String]
    attr_accessor :email

    # The unique identifier of the user.
    # @return [String]
    attr_accessor :id

    # The user's full name.
    # @return [Name]
    attr_accessor :name

    # The list of [roles](https://docs.adyen.com/account/user-roles) for this
    # user.
    # @return [Array[String]]
    attr_accessor :roles

    # The [tz database
    # name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the
    # time zone of the user. For example, **Europe/Amsterdam**.
    # @return [String]
    attr_accessor :time_zone_code

    # The username for this user.
    # @return [String]
    attr_accessor :username

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['links'] = '_links'
      @_hash['account_groups'] = 'accountGroups'
      @_hash['active'] = 'active'
      @_hash['apps'] = 'apps'
      @_hash['email'] = 'email'
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['roles'] = 'roles'
      @_hash['time_zone_code'] = 'timeZoneCode'
      @_hash['username'] = 'username'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        links
        account_groups
        active
        apps
        name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(email:, id:, roles:, time_zone_code:, username:, links: SKIP,
                   account_groups: SKIP, active: SKIP, apps: SKIP, name: SKIP)
      @links = links unless links == SKIP
      @account_groups = account_groups unless account_groups == SKIP
      @active = active unless active == SKIP
      @apps = apps unless apps == SKIP
      @email = email
      @id = id
      @name = name unless name == SKIP
      @roles = roles
      @time_zone_code = time_zone_code
      @username = username
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      email = hash.key?('email') ? hash['email'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      roles = hash.key?('roles') ? hash['roles'] : nil
      time_zone_code = hash.key?('timeZoneCode') ? hash['timeZoneCode'] : nil
      username = hash.key?('username') ? hash['username'] : nil
      links = Links1.from_hash(hash['_links']) if hash['_links']
      account_groups = hash.key?('accountGroups') ? hash['accountGroups'] : SKIP
      active = hash.key?('active') ? hash['active'] : SKIP
      apps = hash.key?('apps') ? hash['apps'] : SKIP
      name = Name.from_hash(hash['name']) if hash['name']

      # Create object from extracted values.
      User.new(email: email,
               id: id,
               roles: roles,
               time_zone_code: time_zone_code,
               username: username,
               links: links,
               account_groups: account_groups,
               active: active,
               apps: apps,
               name: name)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links}, account_groups: #{@account_groups}, active: #{@active},"\
      " apps: #{@apps}, email: #{@email}, id: #{@id}, name: #{@name}, roles: #{@roles},"\
      " time_zone_code: #{@time_zone_code}, username: #{@username}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} links: #{@links.inspect}, account_groups: #{@account_groups.inspect},"\
      " active: #{@active.inspect}, apps: #{@apps.inspect}, email: #{@email.inspect}, id:"\
      " #{@id.inspect}, name: #{@name.inspect}, roles: #{@roles.inspect}, time_zone_code:"\
      " #{@time_zone_code.inspect}, username: #{@username.inspect}>"
    end
  end
end
