# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # The purpose of a digital wallet transaction.
  class WalletPurpose
    WALLET_PURPOSE = [
      # TODO: Write general description for IDENTIFIEDBOLETO
      IDENTIFIEDBOLETO = 'identifiedBoleto'.freeze,

      # TODO: Write general description for TRANSFERDIFFERENTWALLET
      TRANSFERDIFFERENTWALLET = 'transferDifferentWallet'.freeze,

      # TODO: Write general description for TRANSFEROWNWALLET
      TRANSFEROWNWALLET = 'transferOwnWallet'.freeze,

      # TODO: Write general description for TRANSFERSAMEWALLET
      TRANSFERSAMEWALLET = 'transferSameWallet'.freeze,

      # TODO: Write general description for UNIDENTIFIEDBOLETO
      UNIDENTIFIEDBOLETO = 'unidentifiedBoleto'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      WALLET_PURPOSE.include?(value)
    end

    def self.from_value(value, default_value = IDENTIFIEDBOLETO)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'identifiedboleto' then IDENTIFIEDBOLETO
      when 'transferdifferentwallet' then TRANSFERDIFFERENTWALLET
      when 'transferownwallet' then TRANSFEROWNWALLET
      when 'transfersamewallet' then TRANSFERSAMEWALLET
      when 'unidentifiedboleto' then UNIDENTIFIEDBOLETO
      else
        default_value
      end
    end
  end
end
