# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # AndroidFilesCompanyLevelApi
  class AndroidFilesCompanyLevelApi < BaseApi
    # Returns a list of the Android apps that are available for the company
    # identified in the path.
    # These apps have been uploaded to Adyen and can be installed or uninstalled
    # on Android payment terminals through [terminal
    # actions](https://docs.adyen.com/point-of-sale/automating-terminal-manageme
    # nt/terminal-actions-api).
    # To make this request, your API credential must have one of the following
    # [roles](https://docs.adyen.com/development-resources/api-credentials#api-p
    # ermissions):
    # * Management API—Android files read
    # * Management API—Android files read and write
    # * Management API—Terminal actions read
    # * Management API—Terminal actions read and write
    # In the live environment, requests to this endpoint are subject to [rate
    # limits](https://docs.adyen.com/point-of-sale/automating-terminal-managemen
    # t#rate-limits-in-the-live-environment).
    # @param [String] company_id Required parameter: The unique identifier of
    # the company account.
    # @param [Integer] page_number Optional parameter: The number of the page to
    # fetch.
    # @param [Integer] page_size Optional parameter: The number of items to have
    # on a page, maximum 100. The default is 20 items on a page.
    # @param [String] package_name Optional parameter: The package name that
    # uniquely identifies the Android app.
    # @param [Integer] version_code Optional parameter: The version number of
    # the app.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_android_apps(company_id,
                          page_number: nil,
                          page_size: nil,
                          package_name: nil,
                          version_code: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/companies/{companyId}/androidApps',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(company_id, key: 'companyId')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(page_number, key: 'pageNumber'))
                   .query_param(new_parameter(page_size, key: 'pageSize'))
                   .query_param(new_parameter(package_name, key: 'packageName'))
                   .query_param(new_parameter(version_code, key: 'versionCode'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(AndroidAppsResponse.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Uploads an Android APK file to Adyen.
    # The maximum APK file size is 200 MB.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API—Android files read and write
    # In the live environment, requests to this endpoint are subject to [rate
    # limits](https://docs.adyen.com/point-of-sale/automating-terminal-managemen
    # t#rate-limits-in-the-live-environment).
    # >By choosing to upload, install, or run any third-party applications on an
    # Adyen payment terminal, you accept full responsibility and liability for
    # any consequences of uploading, installing, or running any such
    # applications.
    # @param [String] company_id Required parameter: The unique identifier of
    # the company account.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_android_app(company_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/companies/{companyId}/androidApps',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(company_id, key: 'companyId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UploadAndroidAppResponse.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Returns the details of the Android app identified in the path.
    # These apps have been uploaded to Adyen and can be installed or uninstalled
    # on Android payment terminals through [terminal
    # actions](https://docs.adyen.com/point-of-sale/automating-terminal-manageme
    # nt/terminal-actions-api).
    # To make this request, your API credential must have one of the following
    # [roles](https://docs.adyen.com/development-resources/api-credentials#api-p
    # ermissions):
    # * Management API—Android files read
    # * Management API—Android files read and write
    # In the live environment, requests to this endpoint are subject to [rate
    # limits](https://docs.adyen.com/point-of-sale/automating-terminal-managemen
    # t#rate-limits-in-the-live-environment).
    # @param [String] company_id Required parameter: The unique identifier of
    # the company account.
    # @param [String] id Required parameter: The unique identifier of the app.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_android_app(company_id,
                        id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/companies/{companyId}/androidApps/{id}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(company_id, key: 'companyId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(id, key: 'id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(AndroidApp.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Reuploads the Android app identified in the path.
    # To make this request, your API credential must have this
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API—Android files read and write
    # In the live environment, requests to this endpoint are subject to [rate
    # limits](https://docs.adyen.com/point-of-sale/automating-terminal-managemen
    # t#rate-limits-in-the-live-environment).
    # >By choosing to upload, install, or run any third-party applications on an
    # Adyen payment terminal, you accept full responsibility and liability for
    # any consequences of uploading, installing, or running any such
    # applications.
    # @param [String] company_id Required parameter: The unique identifier of
    # the company account.
    # @param [String] id Required parameter: The unique identifier of the app.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_android_app(company_id,
                           id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::PATCH,
                                     '/companies/{companyId}/androidApps/{id}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(company_id, key: 'companyId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(id, key: 'id')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ReprocessAndroidAppResponse.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Returns a list of the Android certificates that are available for the
    # company identified in the path.
    # Typically, these certificates enable running apps on Android payment
    # terminals. The certificates in the list have been uploaded to Adyen and
    # can be installed or uninstalled on Android terminals through [terminal
    # actions](https://docs.adyen.com/point-of-sale/automating-terminal-manageme
    # nt/terminal-actions-api).
    # To make this request, your API credential must have one of the following
    # [roles](https://docs.adyen.com/development-resources/api-credentials#api-p
    # ermissions):
    # * Management API—Android files read
    # * Management API—Android files read and write
    # * Management API—Terminal actions read
    # * Management API—Terminal actions read and write
    # In the live environment, requests to this endpoint are subject to [rate
    # limits](https://docs.adyen.com/point-of-sale/automating-terminal-managemen
    # t#rate-limits-in-the-live-environment).
    # @param [String] company_id Required parameter: The unique identifier of
    # the company account.
    # @param [Integer] page_number Optional parameter: The number of the page to
    # fetch.
    # @param [Integer] page_size Optional parameter: The number of items to have
    # on a page, maximum 100. The default is 20 items on a page.
    # @param [String] certificate_name Optional parameter: The name of the
    # certificate.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_android_certificates(company_id,
                                  page_number: nil,
                                  page_size: nil,
                                  certificate_name: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/companies/{companyId}/androidCertificates',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(company_id, key: 'companyId')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(page_number, key: 'pageNumber'))
                   .query_param(new_parameter(page_size, key: 'pageSize'))
                   .query_param(new_parameter(certificate_name, key: 'certificateName'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(AndroidCertificatesResponse.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Uploads an Android Certificate file to Adyen.
    # In the live environment, requests to this endpoint are subject to [rate
    # limits](https://docs.adyen.com/point-of-sale/automating-terminal-managemen
    # t#rate-limits-in-the-live-environment).
    # @param [String] company_id Required parameter: The unique identifier of
    # the company account.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def upload_android_certificate(company_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/companies/{companyId}/androidCertificates',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(company_id, key: 'companyId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UploadAndroidCertificateResponse.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end
  end
end
