# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # SplitConfigurationMerchantLevelApi
  class SplitConfigurationMerchantLevelApi < BaseApi
    # Returns the list of split configuration profiles for the merchant account.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_split_configurations(merchant_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/merchants/{merchantId}/splitConfigurations',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfigurationList.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Creates a split configuration profile to [split payments
    # automatically](https://docs.adyen.com/platforms/automatic-split-configurat
    # ion/). After you [associate it with a
    # store](https://docs.adyen.com/api-explorer/Management/latest/patch/merchan
    # ts/(merchantId)/stores/(storeId)#request-splitConfiguration) in your
    # merchant account, it splits the funds of all transactions processed
    # through that store between your liable balance account and [your user's
    # balance
    # account](https://docs.adyen.com/api-explorer/Management/latest/patch/merch
    # ants/(merchantId)/stores/(storeId)#request-splitConfiguration-balanceAccou
    # ntId).
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [SplitConfiguration] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_split_configuration(merchant_id,
                                   body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/merchants/{merchantId}/splitConfigurations',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Deletes the split configuration profile specified in the path.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [String] split_configuration_id Required parameter: The unique
    # identifier of the split configuration.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_split_configuration(merchant_id,
                                   split_configuration_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/merchants/{merchantId}/splitConfigurations/{splitConfigurationId}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_configuration_id, key: 'splitConfigurationId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Returns the details of the split configuration profile specified in the
    # path.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [String] split_configuration_id Required parameter: The unique
    # identifier of the split configuration.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_split_configuration(merchant_id,
                                split_configuration_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/merchants/{merchantId}/splitConfigurations/{splitConfigurationId}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_configuration_id, key: 'splitConfigurationId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Changes the description of the split configuration profile specified in
    # the path.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [String] split_configuration_id Required parameter: The unique
    # identifier of the split configuration.
    # @param [UpdateSplitConfigurationRequest] body Optional parameter: TODO:
    # type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_split_configuration(merchant_id,
                                   split_configuration_id,
                                   body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::PATCH,
                                     '/merchants/{merchantId}/splitConfigurations/{splitConfigurationId}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_configuration_id, key: 'splitConfigurationId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # [Creates a
    # rule](https://docs.adyen.com/platforms/automatic-split-configuration/manag
    # e-split-configurations/api/#create-rule) in the split configuration
    # profile specified in the path.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [String] split_configuration_id Required parameter: The unique
    # identifier of the split configuration.
    # @param [SplitConfigurationRule] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_split_configuration_rule(merchant_id,
                                        split_configuration_id,
                                        body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/merchants/{merchantId}/splitConfigurations/{splitConfigurationId}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_configuration_id, key: 'splitConfigurationId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Deletes the rule specified in the path.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [String] split_configuration_id Required parameter: The unique
    # identifier of the split configuration.
    # @param [String] rule_id Required parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_split_configuration_rule(merchant_id,
                                        split_configuration_id,
                                        rule_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/merchants/{merchantId}/splitConfigurations/{splitConfigurationId}/rules/{ruleId}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_configuration_id, key: 'splitConfigurationId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(rule_id, key: 'ruleId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Changes the [split conditions of the
    # rule](https://docs.adyen.com/platforms/automatic-split-configuration/manag
    # e-split-configurations/api/#update-condition) specified in the path.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [String] split_configuration_id Required parameter: The identifier
    # of the split configuration.
    # @param [String] rule_id Required parameter: The unique identifier of the
    # split configuration rule.
    # @param [UpdateSplitConfigurationRuleRequest] body Optional parameter:
    # TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_split_configuration_rule(merchant_id,
                                        split_configuration_id,
                                        rule_id,
                                        body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::PATCH,
                                     '/merchants/{merchantId}/splitConfigurations/{splitConfigurationId}/rules/{ruleId}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_configuration_id, key: 'splitConfigurationId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(rule_id, key: 'ruleId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end

    # Changes the [split
    # logic](https://docs.adyen.com/platforms/automatic-split-configuration/mana
    # ge-split-configurations/api/#update-split-logic) specified in the path.
    # To make this request, your API credential must have the following
    # [role](https://docs.adyen.com/development-resources/api-credentials#api-pe
    # rmissions):
    # * Management API - SplitConfiguration read and write
    # @param [String] merchant_id Required parameter: The unique identifier of
    # the merchant account.
    # @param [String] split_configuration_id Required parameter: The unique
    # identifier of the split configuration.
    # @param [String] rule_id Required parameter: The unique identifier of the
    # split configuration rule.
    # @param [String] split_logic_id Required parameter: The unique identifier
    # of the split configuration split.
    # @param [UpdateSplitConfigurationLogicRequest] body Optional parameter:
    # TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_split_logic(merchant_id,
                           split_configuration_id,
                           rule_id,
                           split_logic_id,
                           body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::PATCH,
                                     '/merchants/{merchantId}/splitConfigurations/{splitConfigurationId}/rules/{ruleId}/splitLogic/{splitLogicId}',
                                     Server::DEFAULT1)
                   .template_param(new_parameter(merchant_id, key: 'merchantId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_configuration_id, key: 'splitConfigurationId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(rule_id, key: 'ruleId')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(split_logic_id, key: 'splitLogicId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('BasicAuth', 'ApiKeyAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SplitConfiguration.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request - a problem reading or understanding the request.',
                                 RestServiceErrorException)
                    .local_error('401',
                                 'Unauthorized - authentication required.',
                                 RestServiceErrorException)
                    .local_error('403',
                                 'Forbidden - insufficient permissions to process the request.',
                                 RestServiceErrorException)
                    .local_error('422',
                                 'Unprocessable Entity - a request validation error.',
                                 RestServiceErrorException)
                    .local_error('500',
                                 'Internal Server Error - the server could not process the'\
                                  ' request.',
                                 RestServiceErrorException))
        .execute
    end
  end
end
