# adyen_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module AdyenApIs
  # Standardized error response following RFC-7807 format
  class DefaultErrorResponseEntityException < APIException
    SKIP = Object.new
    private_constant :SKIP

    # A human-readable explanation specific to this occurrence of the problem.
    # @return [String]
    attr_accessor :detail

    # Unique business error code.
    # @return [String]
    attr_accessor :error_code

    # A URI that identifies the specific occurrence of the problem if
    # applicable.
    # @return [String]
    attr_accessor :instance

    # Array of fields with validation errors when applicable.
    # @return [Array[InvalidField]]
    attr_accessor :invalid_fields

    # The unique reference for the request.
    # @return [String]
    attr_accessor :request_id

    # The HTTP status code.
    # @return [Integer]
    attr_accessor :status

    # A short, human-readable summary of the problem type.
    # @return [String]
    attr_accessor :title

    # A URI that identifies the validation error type. It points to
    # human-readable documentation for the problem type.
    # @return [String]
    attr_accessor :type

    # The constructor.
    # @param [String] reason The reason for raising an exception.
    # @param [HttpResponse] response The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] hash The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      return nil unless hash

      @detail = hash.key?('detail') ? hash['detail'] : SKIP
      @error_code = hash.key?('errorCode') ? hash['errorCode'] : SKIP
      @instance = hash.key?('instance') ? hash['instance'] : SKIP
      # Parameter is an array, so we need to iterate through it
      @invalid_fields = nil
      unless hash['invalidFields'].nil?
        @invalid_fields = []
        hash['invalidFields'].each do |structure|
          @invalid_fields << (InvalidField.from_hash(structure) if structure)
        end
      end

      @invalid_fields = SKIP unless hash.key?('invalidFields')
      @request_id = hash.key?('requestId') ? hash['requestId'] : SKIP
      @status = hash.key?('status') ? hash['status'] : SKIP
      @title = hash.key?('title') ? hash['title'] : SKIP
      @type = hash.key?('type') ? hash['type'] : SKIP
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} detail: #{@detail}, error_code: #{@error_code}, instance: #{@instance},"\
      " invalid_fields: #{@invalid_fields}, request_id: #{@request_id}, status: #{@status}, title:"\
      " #{@title}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} detail: #{@detail.inspect}, error_code: #{@error_code.inspect}, instance:"\
      " #{@instance.inspect}, invalid_fields: #{@invalid_fields.inspect}, request_id:"\
      " #{@request_id.inspect}, status: #{@status.inspect}, title: #{@title.inspect}, type:"\
      " #{@type.inspect}>"
    end
  end
end
